-- TABLES d'ANNOTATIONS POUR LE CONTEXTE/CATALOGUE BANQUE DE TISSUS OSSEUX
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE TABLE_ANNOTATION modify TABLE_ANNOTATION_ID int(10) NOT NULL auto_increment;
ALTER TABLE CHAMP_ANNOTATION modify CHAMP_ANNOTATION_ID int(10) NOT NULL auto_increment;
ALTER TABLE ANNOTATION_DEFAUT modify ANNOTATION_DEFAUT_ID int(10) NOT NULL auto_increment;
ALTER TABLE ITEM modify ITEM_ID int(10) NOT NULL auto_increment;

-- Ajout du contexte banque de tissus osseux
ALTER TABLE CONTEXTE modify CONTEXTE_ID int(10) NOT NULL auto_increment;
INSERT INTO CONTEXTE (NOM) VALUES ('BTO');
ALTER TABLE CONTEXTE modify CONTEXTE_ID int(10) NOT NULL;-- enleve l'auto_increment

-- Catalogue d'annotations associé au contexte BTO
ALTER TABLE CATALOGUE modify CATALOGUE_ID int(10) NOT NULL auto_increment;
INSERT INTO CATALOGUE (NOM, DESCRIPTION, ICONE) VALUES('BTO', 'Banque de tissus osseux', 'bto');
ALTER TABLE CATALOGUE modify CATALOGUE_ID int(10) NOT NULL;-- enleve l'auto_increment

-- Liaison CATALOGUE BTO au CONTEXTE BTO
INSERT INTO CATALOGUE_CONTEXTE (CATALOGUE_ID, CONTEXTE_ID) VALUES((SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'), (SELECT CONTEXTE_ID FROM CONTEXTE WHERE NOM='BTO'));

-- Ajout dans la table NATURE
ALTER TABLE NATURE modify NATURE_ID int(10) NOT NULL auto_increment;
INSERT INTO NATURE (NATURE, PLATEFORME_ID) VALUES
  ('TÊTE FÉMORALE', 1),
  ('AUTRE TISSU', 1);
ALTER TABLE NATURE modify NATURE_ID int(10) NOT NULL;-- enleve l'auto_increment

-- Ajout dans la table ECHANTILLON_TYPE
ALTER TABLE ECHANTILLON_TYPE modify ECHANTILLON_TYPE_ID int(2) NOT NULL auto_increment;
INSERT INTO ECHANTILLON_TYPE (TYPE, INCA_CAT, PLATEFORME_ID) VALUES ('EN ATTENTE', null, 1);
INSERT INTO ECHANTILLON_TYPE (TYPE, INCA_CAT, PLATEFORME_ID) VALUES ('TÊTE CRYOPRÉSERVÉE', null, 1);
INSERT INTO ECHANTILLON_TYPE (TYPE, INCA_CAT, PLATEFORME_ID) VALUES ('TÊTE À VIRO-INACTIVER', null, 1);
ALTER TABLE ECHANTILLON_TYPE modify ECHANTILLON_TYPE_ID int(2) NOT NULL;-- enleve l'auto_increment

-- ------------------------------------------
-- Table d'annotations Patient - Informations
-- ------------------------------------------
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Informations', 'Informations complémentaires du donneur', 1, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

-- Groupe sanguin
INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Groupe sanguin', 7, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('A+', 'A+', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('A-', 'A-', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('B+', 'B+', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('B-', 'B-', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('AB+', 'AB+', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('AB-', 'AB-', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('O+', 'O+', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('O-', 'O-', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));

-- Autologue
INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Autologue', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);

-- ----------------------------------------
-- Table d'annotations Patient - Conformité
-- ----------------------------------------
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Conformité', 'Conformité des données du patient', 1, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Antécédents conformes', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Consentement conforme', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 3, 1);



-- table d'annotations Patient - Validation
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Validation', 'Validation du donneur', 1, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Valide', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Personne respondable', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);



-- table d'annotations Prélèvements - Informations
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Informations', 'Informations complémentaires du don', 2, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Indication au prélèvement', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Délai d''acheminement greffon', 7, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('< 12h', '< 12h', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('< 24h', '< 24h', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('non conforme', 'non conforme', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));



-- table d'annotations Prélèvements - Prélèvements sanguins
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Prélèvements sanguins', 'Information sur la conformité des prélèvements sanguins', 2, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité (emballage)', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 1, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date prélèvement sanguin', 3, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Arrivée du prélèvement sanguin à la BTO', 3, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Délai d''acheminement', 7, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('< à 12h', '< à 12h', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('non conforme', 'non conforme', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Prélèvements sanguins conformes à l''arrivée (tubes et température)', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 5, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité (prélèvements sanguins)', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 6, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Prélèvement bactério conforme (tubes et température)', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 7, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité (bactério)', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 8, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Température de conservation et d''acheminement conforme', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 9, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité (température)', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 10, 1);



-- table d'annotations Prélèvements - Validation
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Validation', 'Validation des conditions globales d''acheminement', 2, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Conforme', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 2, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date', 3, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Personne responsable', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);


-- table d'annotations Echantillons - Sécurisation Virologique
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Sécurisation virologique', 'Bilan de Sécurisation Virologique', 3, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date d''envoi', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Sérothèque', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Ag+AC anti-VIH1 et 2', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('AG HBs', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('AC anti-HBc', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 5, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Sérologie Hépatite C (recherche d’AC anti HCV)', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 6, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Sérologie HTLV I et II', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 7, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Syphilis', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 8, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Génome Viral HIV', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 9, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Génome viral HBV', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 10, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Génome viral HCV', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 11, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);


-- table d'annotations Echantillons - Sécurisation bactério
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Sécurisation bactériologique', 'Bilan de sécurisation bactériologique', 3, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date d''envoi', 3, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Résultat', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Conforme', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);


-- table d'annotations Echantillons - Validation Finale
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Validation Finale', NULL, 3, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Valide', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Personne responsable', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);

-- table d'annotation Cession - Distribution et implantation
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Distribution et Implantation', NULL, 5, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Personne responsable de la préparation', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);

-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date de proposition', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date d''envoi prévue', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date d''implantation prévue', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nom du receveur', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 5, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Prénom du receveur', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 6, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date de naissance du receveur', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 7, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date de la greffe', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 8, 1);

-- Cession type : Implantation
ALTER TABLE CESSION_TYPE modify CESSION_TYPE_ID int(2) NOT NULL auto_increment;
INSERT INTO CESSION_TYPE (CESSION_TYPE_ID, TYPE) VALUES ('4', 'Implantation');
ALTER TABLE CESSION_TYPE modify CESSION_TYPE_ID int(2) NOT NULL;-- enleve l'auto_increment

ALTER TABLE TABLE_ANNOTATION modify TABLE_ANNOTATION_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE CHAMP_ANNOTATION modify CHAMP_ANNOTATION_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE ANNOTATION_DEFAUT modify ANNOTATION_DEFAUT_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE ITEM modify ITEM_ID int(10) NOT NULL;-- enleve l'auto_increment
SET FOREIGN_KEY_CHECKS=1;