-- TABLES d'ANNOTATIONS POUR LE CONTEXTE/CATALOGUE BANQUE DE TISSUS OSSEUX
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE TABLE_ANNOTATION modify TABLE_ANNOTATION_ID int(10) NOT NULL auto_increment;
ALTER TABLE CHAMP_ANNOTATION modify CHAMP_ANNOTATION_ID int(10) NOT NULL auto_increment;
ALTER TABLE ANNOTATION_DEFAUT modify ANNOTATION_DEFAUT_ID int(10) NOT NULL auto_increment;
ALTER TABLE ITEM modify ITEM_ID int(10) NOT NULL auto_increment;
ALTER TABLE CHAMP modify CHAMP_ID int(10) NOT NULL auto_increment;
ALTER TABLE CHAMP_CALCULE modify CHAMP_CALCULE_ID int(10) NOT NULL auto_increment;
ALTER TABLE NON_CONFORMITE modify NON_CONFORMITE_ID int(10) NOT NULL auto_increment;

-- Ajout du contexte banque de tissus osseux
ALTER TABLE CONTEXTE modify CONTEXTE_ID int(10) NOT NULL auto_increment;
INSERT INTO CONTEXTE (NOM) VALUES ('BTO');
ALTER TABLE CONTEXTE modify CONTEXTE_ID int(10) NOT NULL;-- enleve l'auto_increment

-- Catalogue d'annotations associé au contexte BTO
ALTER TABLE CATALOGUE modify CATALOGUE_ID int(10) NOT NULL auto_increment;
INSERT INTO CATALOGUE (NOM, DESCRIPTION, ICONE) VALUES('BTO', 'Banque de tissus osseux', 'bto');
ALTER TABLE CATALOGUE modify CATALOGUE_ID int(10) NOT NULL;-- enleve l'auto_increment

-- Liaison CATALOGUE BTO au CONTEXTE BTO
INSERT INTO CATALOGUE_CONTEXTE (CATALOGUE_ID, CONTEXTE_ID) VALUES((SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'), (SELECT CONTEXTE_ID FROM CONTEXTE WHERE NOM='BTO'));

-- Ajout dans la table NATURE
ALTER TABLE NATURE modify NATURE_ID int(10) NOT NULL auto_increment;
INSERT INTO NATURE (NATURE, PLATEFORME_ID) VALUES
  ('TÊTE FÉMORALE', 1),
  ('AUTRE TISSU', 1);
ALTER TABLE NATURE modify NATURE_ID int(10) NOT NULL;-- enleve l'auto_increment

-- Ajout dans la table ECHANTILLON_TYPE
ALTER TABLE ECHANTILLON_TYPE modify ECHANTILLON_TYPE_ID int(2) NOT NULL auto_increment;
INSERT INTO ECHANTILLON_TYPE (TYPE, INCA_CAT, PLATEFORME_ID) VALUES ('EN ATTENTE', null, 1);
INSERT INTO ECHANTILLON_TYPE (TYPE, INCA_CAT, PLATEFORME_ID) VALUES ('TÊTE CRYOPRÉSERVÉE', null, 1);
INSERT INTO ECHANTILLON_TYPE (TYPE, INCA_CAT, PLATEFORME_ID) VALUES ('TÊTE À VIRO-INACTIVER', null, 1);
ALTER TABLE ECHANTILLON_TYPE modify ECHANTILLON_TYPE_ID int(2) NOT NULL;-- enleve l'auto_increment

-- Ajout du type de consentement GREFFON dans la table CONSENT_TYPE
ALTER TABLE CONSENT_TYPE modify CONSENT_TYPE_ID int(10) NOT NULL auto_increment;
INSERT INTO CONSENT_TYPE (TYPE, PLATEFORME_ID) VALUES ('GREFFON', 1);
ALTER TABLE CONSENT_TYPE modify CONSENT_TYPE_ID int(10) NOT NULL;-- enleve l'auto_increment

-- ------------------------------------------
-- Table d'annotations Patient - Informations
-- ------------------------------------------
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Informations', 'Informations complémentaires du donneur', 1, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

-- Groupe sanguin
INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Groupe sanguin', 7, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('A+', 'A+', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('A-', 'A-', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('B+', 'B+', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('B-', 'B-', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('AB+', 'AB+', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('AB-', 'AB-', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('O+', 'O+', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));
INSERT INTO ITEM
(LABEL, VALEUR, CHAMP_ANNOTATION_ID)
VALUES('O-', 'O-', (SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION));

-- Autologue
INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Autologue', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);

-- ----------------------------------------
-- Table d'annotations Patient - Conformité
-- ----------------------------------------
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Conformité', 'Conformité des données du patient', 1, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Antécédents conformes', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Consentement conforme', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 3, 1);



-- table d'annotations Patient - Validation
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Validation', 'Validation du donneur', 1, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Valide', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Personne respondable', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);

-- table d'annotations Prélèvements - Informations
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Informations', 'Informations complémentaires du don', 2, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Indication au prélèvement', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Délai d''acheminement greffon', (SELECT DATA_TYPE_ID FROM DATA_TYPE WHERE TYPE LIKE 'calcule'), (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);

INSERT INTO CHAMP
(CHAMP_ENTITE_ID)
VALUES(38);
	
INSERT INTO CHAMP
(CHAMP_ENTITE_ID)
VALUES(35);
	
INSERT INTO CHAMP_CALCULE
(CHAMP_ANNOTATION_ID, CHAMP1_ID, OPERATEUR, CHAMP2_ID, VALEUR, DATA_TYPE_ID)
VALUES((SELECT CHAMP_ANNOTATION_ID FROM CHAMP_ANNOTATION WHERE NOM LIKE 'Délai d''acheminement greffon'), (SELECT MAX(CHAMP_ID) FROM CHAMP)-1, '-', (SELECT MAX(CHAMP_ID) FROM CHAMP), null, (SELECT DATA_TYPE_ID FROM DATA_TYPE WHERE TYPE LIKE 'duree'));
	
INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date de péremption', (SELECT DATA_TYPE_ID FROM DATA_TYPE WHERE TYPE LIKE 'calcule'), (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);

INSERT INTO CHAMP
(CHAMP_ENTITE_ID)
VALUES(30);
	
INSERT INTO CHAMP_CALCULE
(CHAMP_ANNOTATION_ID, CHAMP1_ID, OPERATEUR, CHAMP2_ID, VALEUR, DATA_TYPE_ID)
VALUES((SELECT CHAMP_ANNOTATION_ID FROM CHAMP_ANNOTATION WHERE NOM LIKE 'Date de péremption'), (SELECT MAX(CHAMP_ID) FROM CHAMP), '+', null, '157680000', (SELECT DATA_TYPE_ID FROM DATA_TYPE WHERE TYPE LIKE 'date'));



-- table d'annotations Prélèvements - Prélèvements sanguins
INSERT INTO NON_CONFORMITE
(CONFORMITE_TYPE_ID, PLATEFORME_ID, NOM)
VALUES(1,1,'Conditionnement dégradé');

INSERT INTO NON_CONFORMITE
(CONFORMITE_TYPE_ID, PLATEFORME_ID, NOM)
VALUES(1,1,'Non stérilité du conditionnement (péremption, pots mal fermés...)');

INSERT INTO NON_CONFORMITE
(CONFORMITE_TYPE_ID, PLATEFORME_ID, NOM)
VALUES(1,1, 'Anonymisation impossible (étiquette patient sur pot intérieur)');
	
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Prélèvements sanguins', 'Information sur la conformité des prélèvements sanguins', 2, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date prélèvement sanguin', 3, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Arrivée du prélèvement sanguin à la BTO', 3, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Délai d''acheminement', (SELECT DATA_TYPE_ID FROM DATA_TYPE WHERE TYPE LIKE 'calcule'), (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);

INSERT INTO CHAMP
(CHAMP_ANNOTATION_ID)
VALUES((SELECT CHAMP_ANNOTATION_ID FROM CHAMP_ANNOTATION WHERE NOM like 'Arrivée du prélèvement sanguin à la BTO'));

INSERT INTO CHAMP
(CHAMP_ANNOTATION_ID)
VALUES((SELECT CHAMP_ANNOTATION_ID FROM CHAMP_ANNOTATION WHERE NOM like 'Date prélèvement sanguin'));

INSERT INTO CHAMP_CALCULE
(CHAMP_ANNOTATION_ID, CHAMP1_ID, OPERATEUR, CHAMP2_ID, VALEUR, DATA_TYPE_ID)
VALUES((SELECT CHAMP_ANNOTATION_ID FROM CHAMP_ANNOTATION WHERE NOM LIKE 'Délai d''acheminement'), (SELECT MAX(CHAMP_ID) FROM CHAMP)-1, '-', (SELECT MAX(CHAMP_ID) FROM CHAMP), null, (SELECT DATA_TYPE_ID FROM DATA_TYPE WHERE TYPE LIKE 'duree'));
	
INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Prélèvements sanguins conformes à l''arrivée (tubes et température)', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 5, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité (prélèvements sanguins)', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 6, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Prélèvement bactério conforme (tubes et température)', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 7, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité (bactério)', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 8, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Température de conservation et d''acheminement conforme', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 9, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité (température)', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 10, 1);



-- table d'annotations Prélèvements - Validation
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Validation', 'Validation des conditions globales d''acheminement', 2, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Conforme', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nature de la non conformité', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 1, 2, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date', 3, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Personne responsable', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);


-- table d'annotations Echantillons - Sécurisation Virologique
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Sécurisation virologique', 'Bilan de Sécurisation Virologique', 3, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date d''envoi', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Sérothèque', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Ag+AC anti-VIH1 et 2', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('AG HBs', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('AC anti-HBc', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 5, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('AC anti-HBs', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 6, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Sérologie Hépatite C (recherche d’AC anti HCV)', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 7, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Sérologie HTLV I et II', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 8, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Syphilis', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 9, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Génome viral HIV', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 10, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Génome viral HBV', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 11, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Génome viral HCV', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 12, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);


-- table d'annotations Echantillons - Sécurisation bactério
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Sécurisation bactériologique', 'Bilan de sécurisation bactériologique', 3, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date d''envoi', 3, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Résultat', 6, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Conforme', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);


-- table d'annotations Echantillons - Validation Finale
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Validation Finale', NULL, 3, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Valide', 2, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);
-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Personne responsable', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);

-- table d'annotation Cession - Distribution et implantation
INSERT INTO TABLE_ANNOTATION
(NOM, DESCRIPTION, ENTITE_ID, CATALOGUE_ID)
VALUES('Distribution et Implantation', NULL, 5, (SELECT CATALOGUE_ID FROM CATALOGUE WHERE NOM='BTO'));

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Personne responsable de la préparation', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 1, 1);

-- INSERT INTO ANNOTATION_DEFAUT
-- (CHAMP_ANNOTATION_ID, OBLIGATOIRE)
-- VALUES((SELECT MAX(CHAMP_ANNOTATION_ID) FROM CHAMP_ANNOTATION), 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date de proposition', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 2, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date d''envoi prévue', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 3, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date d''implantation prévue', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 4, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Nom du receveur', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 5, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Prénom du receveur', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 6, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date de naissance du receveur', 1, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 7, 1);

INSERT INTO CHAMP_ANNOTATION
(NOM, DATA_TYPE_ID, TABLE_ANNOTATION_ID, COMBINE, ORDRE, EDIT)
VALUES('Date de la greffe', 11, (SELECT MAX(TABLE_ANNOTATION_ID) FROM TABLE_ANNOTATION), 0, 8, 1);

-- Cession type : Implantation
ALTER TABLE CESSION_TYPE modify CESSION_TYPE_ID int(2) NOT NULL auto_increment;
INSERT INTO CESSION_TYPE (TYPE) VALUES ('Implantation');
ALTER TABLE CESSION_TYPE modify CESSION_TYPE_ID int(2) NOT NULL;-- enleve l'auto_increment

ALTER TABLE TABLE_ANNOTATION modify TABLE_ANNOTATION_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE CHAMP_ANNOTATION modify CHAMP_ANNOTATION_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE ANNOTATION_DEFAUT modify ANNOTATION_DEFAUT_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE ITEM modify ITEM_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE CHAMP modify CHAMP_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE CHAMP_CALCULE modify CHAMP_CALCULE_ID int(10) NOT NULL;-- enleve l'auto_increment
ALTER TABLE NON_CONFORMITE modify NON_CONFORMITE_ID int(10) NOT NULL;-- enleve l'auto_increment

-- ------------------------------------------------------
-- DML pour le système de validation pour le contexte BTO
-- ------------------------------------------------------
-- Préparation de l'insertion des données
ALTER TABLE `CHAMP` modify `CHAMP_ID` int(10) NOT NULL auto_increment; -- auto_increment
ALTER TABLE `ACTION` modify `ACTION_ID` int(10) NOT NULL auto_increment; -- auto_increment
ALTER TABLE `VALIDATION` modify `VALIDATION_ID` int(10) NOT NULL auto_increment; -- auto_increment
ALTER TABLE `CRITERE_VALIDATION` modify `CRITERE_VALIDATION_ID` int(10) NOT NULL auto_increment; -- auto_increment

-- Initialisation des niveaux de validation
INSERT INTO `NIVEAU_VALIDATION` (`NIVEAU_VALIDATION_ID`, `LIBELLE`, `COULEUR`, `CLE_MESSAGE`, `CRITICITE`) VALUES (1, 'UNDEFINED', 'red', 'validation.popup.message.undefined', 0);
INSERT INTO `NIVEAU_VALIDATION` (`NIVEAU_VALIDATION_ID`, `LIBELLE`, `COULEUR`, `CLE_MESSAGE`, `CRITICITE`) VALUES (2, 'KO', 'red', 'validation.popup.message.ko', 1);
INSERT INTO `NIVEAU_VALIDATION` (`NIVEAU_VALIDATION_ID`, `LIBELLE`, `COULEUR`, `CLE_MESSAGE`, `CRITICITE`) VALUES (3, 'WARN', 'orange', 'validation.popup.message.warn', 2);
INSERT INTO `NIVEAU_VALIDATION` (`NIVEAU_VALIDATION_ID`, `LIBELLE`, `COULEUR`, `CLE_MESSAGE`, `CRITICITE`) VALUES (4, 'OK', 'green', 'validation.popup.message.ok', 3);

-- Initialisation de la validation pour l'entité Patient
INSERT INTO `ACTION` (`ENTITE_ID`,`TYPE_ACTION`,`LIBELLE`) VALUES ((SELECT `ENTITE_ID` FROM `ENTITE` WHERE `NOM` = 'Patient'), 'VALIDATION', 'Validation patient');

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Consentement conforme', null, 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Consentement conforme' AND tbl.`NOM` = 'Conformité' AND entite.`NOM` = 'Patient'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Consentement non-conforme', 'OR', 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Consentement conforme' AND tbl.`NOM` = 'Conformité' AND entite.`NOM` = 'Patient'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', null, null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Consentement conforme' AND tbl.`NOM` = 'Conformité' AND entite.`NOM` = 'Patient'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'false', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Antécédents conformes', null, 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Antécédents conformes' AND tbl.`NOM` = 'Conformité' AND entite.`NOM` = 'Patient'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Antécédents non-conformes', 'OR', 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Antécédents conformes' AND tbl.`NOM` = 'Conformité' AND entite.`NOM` = 'Patient'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', null, null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Antécédents conformes' AND tbl.`NOM` = 'Conformité' AND entite.`NOM` = 'Patient'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'false', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

-- Initialisation de la validation pour l'entité Prélèvement
INSERT INTO `ACTION` (`ENTITE_ID`,`TYPE_ACTION`,`LIBELLE`) VALUES ((SELECT `ENTITE_ID` FROM `ENTITE` WHERE `NOM` = 'Prelevement'), 'VALIDATION', 'Validation prélèvement');

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Fiche prélèvement incomplète', 'OR', 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Fiche prélèvement non-conforme', null, null);
INSERT INTO `SOUS_VALIDATION` (`VALIDATION_ID`, `SOUS_VALIDATION_ID`) VALUES ( (SELECT MAX(`VALIDATION_ID`)-1 FROM `VALIDATION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Conforme' AND tbl.`NOM` = 'Validation' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'false', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Fiche prélèvement non datée', null, null);
INSERT INTO `SOUS_VALIDATION` (`VALIDATION_ID`, `SOUS_VALIDATION_ID`) VALUES ( (SELECT MAX(`VALIDATION_ID`)-2 FROM `VALIDATION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Date' AND tbl.`NOM` = 'Validation' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', null, null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Fiche prélèvement non signée', null, null);
INSERT INTO `SOUS_VALIDATION` (`VALIDATION_ID`, `SOUS_VALIDATION_ID`) VALUES ( (SELECT MAX(`VALIDATION_ID`)-3 FROM `VALIDATION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Personne Responsable' AND tbl.`NOM` = 'Validation' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', null, null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Transport prélèvement conforme', 'OR', 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Transport prlt <12h à 4°C', 'AND', null);
INSERT INTO `SOUS_VALIDATION` (`VALIDATION_ID`, `SOUS_VALIDATION_ID`) VALUES ( (SELECT MAX(`VALIDATION_ID`)-1 FROM `VALIDATION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement greffon' AND tbl.`NOM` = 'Informations' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'INFERIEUR', '43200', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES (null, (SELECT ch.`CHAMP_ENTITE_ID` FROM `CHAMP_ENTITE` ch JOIN ENTITE e ON e.`ENTITE_ID` = ch.`ENTITE_ID` WHERE ch.`NOM` = 'TransportTemp' AND e.`NOM` = 'Prelevement'), null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'INFERIEUR_EGAL', '4', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Transport prlt <24h à -30°C', 'AND', null);
INSERT INTO `SOUS_VALIDATION` (`VALIDATION_ID`, `SOUS_VALIDATION_ID`) VALUES ( (SELECT MAX(`VALIDATION_ID`)-2 FROM `VALIDATION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement greffon' AND tbl.`NOM` = 'Informations' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'INFERIEUR', '86400', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES (null, (SELECT ch.`CHAMP_ENTITE_ID` FROM `CHAMP_ENTITE` ch JOIN ENTITE e ON e.`ENTITE_ID` = ch.`ENTITE_ID` WHERE ch.`NOM` = 'TransportTemp' AND e.`NOM` = 'Prelevement'), null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'INFERIEUR_EGAL', '-30', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Transport prélèvement warning', 'AND', 3);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement greffon' AND tbl.`NOM` = 'Informations' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'SUPERIEUR_EGAL', '43200', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement greffon' AND tbl.`NOM` = 'Informations' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'INFERIEUR_EGAL', '172800', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES (null, (SELECT ch.`CHAMP_ENTITE_ID` FROM `CHAMP_ENTITE` ch JOIN ENTITE e ON e.`ENTITE_ID` = ch.`ENTITE_ID` WHERE ch.`NOM` = 'TransportTemp' AND e.`NOM` = 'Prelevement'), null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'INFERIEUR_EGAL', '-30', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Transport prélèvement non-conforme', 'OR', 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement greffon' AND tbl.`NOM` = 'Informations' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'SUPERIEUR', '172800', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement greffon' AND tbl.`NOM` = 'Informations' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', null, null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES (null, (SELECT ch.`CHAMP_ENTITE_ID` FROM `CHAMP_ENTITE` ch JOIN ENTITE e ON e.`ENTITE_ID` = ch.`ENTITE_ID` WHERE ch.`NOM` = 'TransportTemp' AND e.`NOM` = 'Prelevement'), null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', null, null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Prélèvement sanguin conforme', 'AND', 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement' AND tbl.`NOM` = 'Prélèvements sanguins' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'INFERIEUR', '21600', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Prélèvements sanguins conformes à l''arrivée (tubes et température)' AND tbl.`NOM` = 'Prélèvements sanguins' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Prélèvement sanguin warning', 'AND', 3);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement' AND tbl.`NOM` = 'Prélèvements sanguins' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'SUPERIEUR_EGAL', '21600', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement' AND tbl.`NOM` = 'Prélèvements sanguins' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'INFERIEUR_EGAL', '259200', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Prélèvement sanguin non-conforme', null, 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Délai d''acheminement' AND tbl.`NOM` = 'Prélèvements sanguins' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'SUPERIEUR', '259200', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Prélèvement bactério conforme', null, 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Prélèvement bactério conforme (tubes et température)' AND tbl.`NOM` = 'Prélèvements sanguins' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Prélèvement bactério non-conforme', null, 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` entite ON tbl.`ENTITE_ID` = entite.`ENTITE_ID` WHERE anno.`NOM` = 'Prélèvement bactério conforme (tubes et température)' AND tbl.`NOM` = 'Prélèvements sanguins' AND entite.`NOM` = 'Prelevement'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'false', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Conditionnement de la TF conforme', null, 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES (null, (SELECT ch.`CHAMP_ENTITE_ID` FROM `CHAMP_ENTITE` ch JOIN ENTITE e ON e.`ENTITE_ID` = ch.`ENTITE_ID` WHERE ch.`NOM` = 'ConformeArrivee' AND e.`NOM` = 'Prelevement'), null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Conditionnement de la TF non-conforme', null, 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES (null, (SELECT ch.`CHAMP_ENTITE_ID` FROM `CHAMP_ENTITE` ch JOIN ENTITE e ON e.`ENTITE_ID` = ch.`ENTITE_ID` WHERE ch.`NOM` = 'ConformeArrivee' AND e.`NOM` = 'Prelevement'), null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'false', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

-- Initialisation de la validation pour l'entité Echantillon
INSERT INTO `ACTION` (`ENTITE_ID`,`TYPE_ACTION`,`LIBELLE`) VALUES ((SELECT `ENTITE_ID` FROM `ENTITE` WHERE `NOM` = 'Echantillon'), 'VALIDATION', 'Validation échantillon');

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Bilan bactériologique conforme', null, 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` e ON tbl.`ENTITE_ID` = e.`ENTITE_ID` WHERE anno.`NOM` = 'Conforme' AND tbl.`NOM` = 'Sécurisation bactériologique' AND e.`NOM` = 'Echantillon'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Bilan bactériologique non-conforme', null, 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` e ON tbl.`ENTITE_ID` = e.`ENTITE_ID` WHERE anno.`NOM` = 'Conforme' AND tbl.`NOM` = 'Sécurisation bactériologique' AND e.`NOM` = 'Echantillon'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'false', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Sérologie HTLV I et II négative', null, 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` e ON tbl.`ENTITE_ID` = e.`ENTITE_ID` WHERE anno.`NOM` = 'Sérologie HTLV I et II' AND tbl.`NOM` = 'Sécurisation Virologique' AND e.`NOM` = 'Echantillon'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'false', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Sérologie HTLV I et II positive', null, 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` e ON tbl.`ENTITE_ID` = e.`ENTITE_ID` WHERE anno.`NOM` = 'Sérologie HTLV I et II' AND tbl.`NOM` = 'Sécurisation Virologique' AND e.`NOM` = 'Echantillon'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Sérologie Syphilis négative', null, 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` e ON tbl.`ENTITE_ID` = e.`ENTITE_ID` WHERE anno.`NOM` = 'Syphilis' AND tbl.`NOM` = 'Sécurisation Virologique' AND e.`NOM` = 'Echantillon'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'false', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Sérologie Syphilis négative positive', null, 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` e ON tbl.`ENTITE_ID` = e.`ENTITE_ID` WHERE anno.`NOM` = 'Syphilis' AND tbl.`NOM` = 'Sécurisation Virologique' AND e.`NOM` = 'Echantillon'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Sérologie HCV négative', null, 4);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` e ON tbl.`ENTITE_ID` = e.`ENTITE_ID` WHERE anno.`NOM` LIKE 'Sérologie Hépatite C%' AND tbl.`NOM` = 'Sécurisation Virologique' AND e.`NOM` = 'Echantillon'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'f', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

INSERT INTO `VALIDATION` (`LIBELLE`, `OPERATEUR`, `NIVEAU_VALIDATION_ID`) VALUES ('Sérologie HCV positive', null, 2);
INSERT INTO `ACTION_VALIDATION` (`ACTION_ID`, `VALIDATION_ID`) VALUES ( (SELECT MAX(`ACTION_ID`) FROM `ACTION`) , (SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`));
INSERT INTO `CHAMP` (`CHAMP_ANNOTATION_ID`, `CHAMP_ENTITE_ID`, `CHAMP_PARENT_ID`) VALUES ((SELECT anno.`CHAMP_ANNOTATION_ID` FROM `CHAMP_ANNOTATION` anno JOIN `TABLE_ANNOTATION` tbl ON tbl.`TABLE_ANNOTATION_ID` = anno.`TABLE_ANNOTATION_ID` JOIN `ENTITE` e ON tbl.`ENTITE_ID` = e.`ENTITE_ID` WHERE anno.`NOM` LIKE 'Sérologie Hépatite C%' AND tbl.`NOM` = 'Sécurisation Virologique' AND e.`NOM` = 'Echantillon'), null, null);
INSERT INTO `CRITERE_VALIDATION` (`CHAMP_ID`, `OPERATEUR`, `VALEUR_REF`, `CHAMP_REF_ID`) VALUES ((SELECT MAX(`CHAMP_ID`) FROM `CHAMP`), 'EGAL', 'true', null);
INSERT INTO `VALIDATION_CRITERE_VALIDATION` (`VALIDATION_ID`, `CRITERE_VALIDATION_ID`) VALUES ((SELECT MAX(`VALIDATION_ID`) FROM `VALIDATION`), (SELECT MAX(`CRITERE_VALIDATION_ID`) FROM `CRITERE_VALIDATION`));

ALTER TABLE `CHAMP` modify `CHAMP_ID` int(10) NOT NULL; -- enleve l'auto_increment
ALTER TABLE `ACTION` modify `ACTION_ID` int(10) NOT NULL; -- enleve l'auto_increment
ALTER TABLE `VALIDATION` modify `VALIDATION_ID` int(10) NOT NULL; -- enleve l'auto_increment
ALTER TABLE `CRITERE_VALIDATION` modify `CRITERE_VALIDATION_ID` int(10) NOT NULL; -- enleve l'auto_increment

-- Ajout des types d'action "ValidationEntite" et "InvalidationEntite" dans la table OPERATION_TYPE
ALTER TABLE OPERATION_TYPE modify OPERATION_TYPE_ID int(10) NOT NULL auto_increment;
INSERT INTO `OPERATION_TYPE` (`NOM`, `PROFILABLE`) VALUES ( 'ValidationEntite', 1);
INSERT INTO `OPERATION_TYPE` (`NOM`, `PROFILABLE`) VALUES ( 'InvalidationEntite', 1);
ALTER TABLE OPERATION_TYPE modify OPERATION_TYPE_ID int(10) NOT NULL; -- enleve l'auto_increment
-- ------------------------------------------------------------
-- END - DML pour le système de validation pour le contexte BTO
-- ------------------------------------------------------------

SET FOREIGN_KEY_CHECKS=1;
