DROP TABLE IF EXISTS PRELEVEMENT_SERO;
DROP TABLE IF EXISTS PRELEVEMENT_SERO_PROTOCOLE;
DROP TABLE IF EXISTS PRELEVEMENT_XENO;
DROP TABLE IF EXISTS PRELEVEMENT_DELEGATE;

DROP TABLE IF EXISTS MALADIE_SERO;
DROP TABLE IF EXISTS MALADIE_DELEGATE;

DROP TABLE IF EXISTS PATIENT_DELEGATE;
DROP TABLE IF EXISTS ECHANTILLON_DELEGATE;
DROP TABLE IF EXISTS PROD_DERIVE_DELEGATE;
DROP TABLE IF EXISTS CESSION_DELEGATE;


ALTER TABLE CHAMP DROP CONSTRAINT FK_CHAMP_CHAMP_DELEGUE_ID;
ALTER TABLE CHAMP DROP COLUMN CHAMP_DELEGUE_ID;

DROP TABLE IF EXISTS CHAMP_DELEGUE;

-- TK-836 lié à TK-520 : 
ALTER TABLE DIAGNOSTIC DROP CONSTRAINT FK_DIAGNOSTIC_PLATEFORME_ID;
ALTER TABLE DIAGNOSTIC DROP COLUMN PLATEFORME_ID;
