ALTER TABLE ETABLISSEMENT
  ADD CONSTRAINT FK_ETABLISSEMENT_COORDONNEE_ID
      FOREIGN KEY (COORDONNEE_ID)
      REFERENCES COORDONNEE (COORDONNEE_ID);

ALTER TABLE ETABLISSEMENT
  ADD CONSTRAINT FK_ETABLISSEMENT_CATEGORIE_ID
      FOREIGN KEY (CATEGORIE_ID)
      REFERENCES CATEGORIE (CATEGORIE_ID) 
      ON DELETE SET NULL;

ALTER TABLE COLLABORATEUR
  ADD CONSTRAINT FK_COLLABORATEUR_SPECIALITE_ID
      FOREIGN KEY (SPECIALITE_ID)
      REFERENCES SPECIALITE (SPECIALITE_ID)
      ON DELETE SET NULL;

ALTER TABLE COLLABORATEUR
  ADD CONSTRAINT FK_COLLABORATEUR_TITRE_ID
      FOREIGN KEY (TITRE_ID)
      REFERENCES TITRE (TITRE_ID);

ALTER TABLE COLLABORATEUR_COORDONNEE
  ADD CONSTRAINT FK_COLLABORATEUR_COORDONNEE_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE COLLABORATEUR_COORDONNEE
  ADD CONSTRAINT FK_COLLABORATEUR_COORDONNEE_COORDONNEE_ID
      FOREIGN KEY (COORDONNEE_ID)
      REFERENCES COORDONNEE (COORDONNEE_ID);

ALTER TABLE COLLABORATEUR
  ADD CONSTRAINT FK_COLLABORATEUR_ETABLISSEMENT_ID
      FOREIGN KEY (ETABLISSEMENT_ID)
      REFERENCES ETABLISSEMENT (ETABLISSEMENT_ID);

ALTER TABLE TRANSPORTEUR
  ADD CONSTRAINT FK_TRANSPORTEUR_COORDONNEE_ID
      FOREIGN KEY (COORDONNEE_ID)
      REFERENCES COORDONNEE (COORDONNEE_ID);

ALTER TABLE SERVICE
  ADD CONSTRAINT FK_SERVICE_COORDONNEE_ID
      FOREIGN KEY (COORDONNEE_ID)
      REFERENCES COORDONNEE (COORDONNEE_ID);

ALTER TABLE SERVICE
  ADD CONSTRAINT FK_SERVICE_ETABLISSEMENT_ID
      FOREIGN KEY (ETABLISSEMENT_ID)
      REFERENCES ETABLISSEMENT (ETABLISSEMENT_ID);

ALTER TABLE PLATEFORME
  ADD CONSTRAINT FK_PLATEFORME_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE ENCEINTE
  ADD CONSTRAINT FK_ENCEINTE_CONTENEUR_ID
      FOREIGN KEY (CONTENEUR_ID)
      REFERENCES CONTENEUR (CONTENEUR_ID);

ALTER TABLE ENCEINTE
  ADD CONSTRAINT FK_ENCEINTE_ENCEINTE_PERE_ID
      FOREIGN KEY (ENCEINTE_PERE_ID)
      REFERENCES ENCEINTE (ENCEINTE_ID);

ALTER TABLE ENCEINTE
  ADD CONSTRAINT FK_ENCEINTE_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE ENCEINTE
  ADD CONSTRAINT FK_ENCEINTE_ENCEINTE_TYPE_ID
      FOREIGN KEY (ENCEINTE_TYPE_ID)
      REFERENCES ENCEINTE_TYPE (ENCEINTE_TYPE_ID);

ALTER TABLE ENCEINTE
  ADD CONSTRAINT FK_ENCEINTE_COULEUR_ID
      FOREIGN KEY (COULEUR_ID)
      REFERENCES COULEUR (COULEUR_ID);

ALTER TABLE TERMINALE
  ADD CONSTRAINT FK_TERMINALE_TERMINALE_TYPE_ID
      FOREIGN KEY (TERMINALE_TYPE_ID)
      REFERENCES TERMINALE_TYPE (TERMINALE_TYPE_ID);

ALTER TABLE TERMINALE
  ADD CONSTRAINT FK_TERMINALE_ENCEINTE_ID
      FOREIGN KEY (ENCEINTE_ID)
      REFERENCES ENCEINTE (ENCEINTE_ID);

ALTER TABLE TERMINALE
  ADD CONSTRAINT FK_TERMINALE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID)
      ON DELETE SET NULL;

ALTER TABLE TERMINALE
  ADD CONSTRAINT FK_TERMINALE_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE TERMINALE
  ADD CONSTRAINT FK_TERMINALE_TERMINALE_NUMEROTATION_ID
      FOREIGN KEY (TERMINALE_NUMEROTATION_ID)
      REFERENCES TERMINALE_NUMEROTATION (TERMINALE_NUMEROTATION_ID);

ALTER TABLE TERMINALE
  ADD CONSTRAINT FK_TERMINALE_COULEUR_ID
      FOREIGN KEY (COULEUR_ID)
      REFERENCES COULEUR (COULEUR_ID);

ALTER TABLE EMPLACEMENT
  ADD CONSTRAINT FK_EMPLACEMENT_TERMINALE_ID
      FOREIGN KEY (TERMINALE_ID)
      REFERENCES TERMINALE (TERMINALE_ID);

ALTER TABLE EMPLACEMENT
  ADD CONSTRAINT FK_EMPLACEMENT_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE TRANSFORMATION
  ADD CONSTRAINT FK_TRANSFORMATION_QUANTITE_UNITE_ID
      FOREIGN KEY (QUANTITE_UNITE_ID)
      REFERENCES UNITE (UNITE_ID);

ALTER TABLE TRANSFORMATION
  ADD CONSTRAINT FK_TRANSFORMATION_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE CONTENEUR
  ADD CONSTRAINT FK_CONTENEUR_CONTENEUR_TYPE_ID
      FOREIGN KEY (CONTENEUR_TYPE_ID)
      REFERENCES CONTENEUR_TYPE (CONTENEUR_TYPE_ID) 
      ON DELETE SET NULL;
      
 ALTER TABLE CONTENEUR
  ADD CONSTRAINT FK_CONTENEUR_PF_ORIG_ID
      FOREIGN KEY (PLATEFORME_ORIG_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE CONTENEUR
  ADD CONSTRAINT FK_CONTENEUR_SERVICE_ID
      FOREIGN KEY (SERVICE_ID)
      REFERENCES SERVICE (SERVICE_ID);

ALTER TABLE BANQUE
  ADD CONSTRAINT FK_BANQUE_PLATERORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE BANQUE
  ADD CONSTRAINT FK_BANQUE_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE BANQUE
  ADD CONSTRAINT FK_BANQUE_PROPRIETAIRE_ID
      FOREIGN KEY (PROPRIETAIRE_ID)
      REFERENCES SERVICE (SERVICE_ID);

ALTER TABLE BANQUE
  ADD CONSTRAINT FK_BANQUE_CONTACT_ID
      FOREIGN KEY (CONTACT_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE BANQUE
  ADD CONSTRAINT FK_BANQUE_CONTEXTE_ID
      FOREIGN KEY (CONTEXTE_ID)
      REFERENCES CONTEXTE (CONTEXTE_ID);

ALTER TABLE BANQUE
  ADD CONSTRAINT FK_BANQUE_ECHANTILLON_COULEUR_ID 
	  FOREIGN KEY (ECHANTILLON_COULEUR_ID)
      REFERENCES COULEUR (COULEUR_ID);

ALTER TABLE BANQUE
  ADD CONSTRAINT FK_BANQUE_PROD_DERIVE_COULEUR_ID 
      FOREIGN KEY (PROD_DERIVE_COULEUR_ID)
      REFERENCES COULEUR (COULEUR_ID);

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_OBJET_STATUT_ID
      FOREIGN KEY (OBJET_STATUT_ID)
      REFERENCES OBJET_STATUT (OBJET_STATUT_ID);
      
ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_ECHAN_QUALITE_ID
      FOREIGN KEY (ECHAN_QUALITE_ID)
      REFERENCES ECHAN_QUALITE (ECHAN_QUALITE_ID) 
      ON DELETE SET NULL;

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_MODE_PREPA_ID
      FOREIGN KEY (MODE_PREPA_ID)
      REFERENCES MODE_PREPA (MODE_PREPA_ID) 
      ON DELETE SET NULL;

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_QUANTITE_UNITE_ID
      FOREIGN KEY (QUANTITE_UNITE_ID)
      REFERENCES UNITE (UNITE_ID);

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_EMPLACEMENT_ID
      FOREIGN KEY (EMPLACEMENT_ID)
      REFERENCES EMPLACEMENT (EMPLACEMENT_ID);

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_CR_ANAPATH_ID
      FOREIGN KEY (CR_ANAPATH_ID)
      REFERENCES FICHIER (FICHIER_ID)
      ON DELETE SET NULL;

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_RESERVATION_ID
      FOREIGN KEY (RESERVATION_ID)
      REFERENCES RESERVATION (RESERVATION_ID);

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_ECHANTILLON_TYPE_ID
      FOREIGN KEY (ECHANTILLON_TYPE_ID)
      REFERENCES ECHANTILLON_TYPE (ECHANTILLON_TYPE_ID);

ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_PRELEVEMENT_ID
      FOREIGN KEY (PRELEVEMENT_ID)
      REFERENCES PRELEVEMENT (PRELEVEMENT_ID);
      
-- ALTER TABLE ECHANTILLON
--  ADD CONSTRAINT FK_ECHANTILLON_CODE_LES_EXPORT_ID
--      FOREIGN KEY (CODE_LES_EXPORT_ID)
--      REFERENCES CODE_ASSIGNE (CODE_ASSIGNE_ID) 
--      ON DELETE SET NULL;
--
-- ALTER TABLE ECHANTILLON
--  ADD CONSTRAINT FK_ECHANTILLON_CODE_ORGANE_EXPORT_ID
--      FOREIGN KEY (CODE_ORGANE_EXPORT_ID)
--      REFERENCES CODE_ASSIGNE (CODE_ASSIGNE_ID) 
--      ON DELETE SET NULL;

ALTER TABLE RESERVATION
  ADD CONSTRAINT FK_RESERVATION_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);      
      
ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_QUANTITE_UNITE_ID
      FOREIGN KEY (QUANTITE_UNITE_ID)
      REFERENCES UNITE (UNITE_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_CONC_UNITE_ID
      FOREIGN KEY (CONC_UNITE_ID)
      REFERENCES UNITE (UNITE_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_PROD_TYPE_ID
      FOREIGN KEY (PROD_TYPE_ID)
      REFERENCES PROD_TYPE (PROD_TYPE_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_OBJET_STATUT_ID
      FOREIGN KEY (OBJET_STATUT_ID)
      REFERENCES OBJET_STATUT (OBJET_STATUT_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_PROD_QUALITE_ID
      FOREIGN KEY (PROD_QUALITE_ID)
      REFERENCES PROD_QUALITE (PROD_QUALITE_ID) 
      ON DELETE SET NULL;

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_EMPLACEMENT_ID
      FOREIGN KEY (EMPLACEMENT_ID)
      REFERENCES EMPLACEMENT (EMPLACEMENT_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_RESERVATION_ID
      FOREIGN KEY (RESERVATION_ID)
      REFERENCES RESERVATION (RESERVATION_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_VOLUME_UNITE_ID
      FOREIGN KEY (VOLUME_UNITE_ID)
      REFERENCES UNITE (UNITE_ID);
      
ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_TRANSFORMATION_ID
      FOREIGN KEY (TRANSFORMATION_ID)
      REFERENCES TRANSFORMATION (TRANSFORMATION_ID);

ALTER TABLE PROD_DERIVE
  ADD CONSTRAINT FK_PROD_DERIVE_MODE_PREPA_DERIVE_ID
      FOREIGN KEY (MODE_PREPA_DERIVE_ID)
      REFERENCES MODE_PREPA_DERIVE (MODE_PREPA_DERIVE_ID) 
      ON DELETE SET NULL;

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_CESSION_TYPE_ID
      FOREIGN KEY (CESSION_TYPE_ID)
      REFERENCES CESSION_TYPE (CESSION_TYPE_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_CESSION_EXAMEN_ID
      FOREIGN KEY (CESSION_EXAMEN_ID)
      REFERENCES CESSION_EXAMEN (CESSION_EXAMEN_ID) 
      ON DELETE SET NULL;

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_CONTRAT_ID
      FOREIGN KEY (CONTRAT_ID)
      REFERENCES CONTRAT (CONTRAT_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_DESTINATAIRE_ID
      FOREIGN KEY (DESTINATAIRE_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_SERVICE_DEST_ID
      FOREIGN KEY (SERVICE_DEST_ID)
      REFERENCES SERVICE (SERVICE_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_DEMANDEUR_ID
      FOREIGN KEY (DEMANDEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_CESSION_STATUT_ID
      FOREIGN KEY (CESSION_STATUT_ID)
      REFERENCES CESSION_STATUT (CESSION_STATUT_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_EXECUTANT_ID
      FOREIGN KEY (EXECUTANT_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_TRANSPORTEUR_ID
      FOREIGN KEY (TRANSPORTEUR_ID)
      REFERENCES TRANSPORTEUR (TRANSPORTEUR_ID);

ALTER TABLE CESSION
  ADD CONSTRAINT FK_CESSION_DESTRUCTION_MOTIF_ID
      FOREIGN KEY (DESTRUCTION_MOTIF_ID)
      REFERENCES DESTRUCTION_MOTIF (DESTRUCTION_MOTIF_ID) 
      ON DELETE SET NULL;

ALTER TABLE INCIDENT
  ADD CONSTRAINT FK_INCIDENT_CONTENEUR_ID
      FOREIGN KEY (CONTENEUR_ID)
      REFERENCES CONTENEUR (CONTENEUR_ID);
      
ALTER TABLE INCIDENT 
	ADD CONSTRAINT FK_INCIDENT_ENCEINTE_ID 
	FOREIGN KEY (ENCEINTE_ID) 
	REFERENCES ENCEINTE (ENCEINTE_ID);
	
ALTER TABLE INCIDENT 
	ADD CONSTRAINT FK_INCIDENT_TERMINALE_ID 
	FOREIGN KEY (TERMINALE_ID) 
	REFERENCES TERMINALE (TERMINALE_ID);

ALTER TABLE MODELE
  ADD CONSTRAINT FK_MODELE_MODELE_TYPE_ID
      FOREIGN KEY (MODELE_TYPE_ID)
      REFERENCES MODELE_TYPE (MODELE_TYPE_ID);

ALTER TABLE MODELE
  ADD CONSTRAINT FK_MODELE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE LIGNE_ETIQUETTE
  ADD CONSTRAINT FK_LIGNE_ETIQUETTE_MODELE
      FOREIGN KEY (MODELE_ID)
      REFERENCES MODELE (MODELE_ID);

ALTER TABLE CHAMP_LIGNE_ETIQUETTE
  ADD CONSTRAINT FK_CHAMP_LIGNE_ETIQUETTE_LIGNE_ETIQUETTE
      FOREIGN KEY (LIGNE_ETIQUETTE_ID)
      REFERENCES LIGNE_ETIQUETTE (LIGNE_ETIQUETTE_ID);

ALTER TABLE CHAMP_LIGNE_ETIQUETTE
  ADD CONSTRAINT FK_CHAMP_LIGNE_ETIQUETTE_CHAMP_ID
        FOREIGN KEY (CHAMP_ID)
        REFERENCES CHAMP (CHAMP_ID);

ALTER TABLE CHAMP_LIGNE_ETIQUETTE
  ADD CONSTRAINT FK_CHAMP_LIGNE_ETIQUETTE_ENTITE
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE UTILISATEUR
  ADD CONSTRAINT FK_UTILISATEUR_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE MALADIE
  ADD CONSTRAINT FK_MALADIE_PATIENT_ID
      FOREIGN KEY (PATIENT_ID)
      REFERENCES PATIENT (PATIENT_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_NATURE_ID
      FOREIGN KEY (NATURE_ID)
      REFERENCES NATURE (NATURE_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_PRELEVEMENT_TYPE_ID
      FOREIGN KEY (PRELEVEMENT_TYPE_ID)
      REFERENCES PRELEVEMENT_TYPE (PRELEVEMENT_TYPE_ID)
      ON DELETE SET NULL;

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_CONDIT_TYPE_ID
      FOREIGN KEY (CONDIT_TYPE_ID)
      REFERENCES CONDIT_TYPE (CONDIT_TYPE_ID)
      ON DELETE SET NULL;

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_CONDIT_MILIEU_ID
      FOREIGN KEY (CONDIT_MILIEU_ID)
      REFERENCES CONDIT_MILIEU (CONDIT_MILIEU_ID)
      ON DELETE SET NULL;

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_PRELEVEUR_ID
      FOREIGN KEY (PRELEVEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_SERVICE_PRELEVEUR_ID
      FOREIGN KEY (SERVICE_PRELEVEUR_ID)
      REFERENCES SERVICE (SERVICE_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_TRANSPORTEUR_ID
      FOREIGN KEY (TRANSPORTEUR_ID)
      REFERENCES TRANSPORTEUR (TRANSPORTEUR_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_OPERATEUR_ID
      FOREIGN KEY (OPERATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_QUANTITE_UNITE_ID
      FOREIGN KEY (QUANTITE_UNITE_ID)
      REFERENCES UNITE (UNITE_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_CONSENT_TYPE_ID
      FOREIGN KEY (CONSENT_TYPE_ID)
      REFERENCES CONSENT_TYPE (CONSENT_TYPE_ID);

ALTER TABLE PRELEVEMENT
  ADD CONSTRAINT FK_PRELEVEMENT_MALADIE_ID
      FOREIGN KEY (MALADIE_ID)
      REFERENCES MALADIE (MALADIE_ID);

ALTER TABLE TABLE_ANNOTATION
  ADD CONSTRAINT FK_TABLE_ANNOTATION_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);
      
ALTER TABLE TABLE_ANNOTATION
  ADD CONSTRAINT FK_TABLE_ANNOTATION_CATALOGUE
      FOREIGN KEY (CATALOGUE_ID)
      REFERENCES CATALOGUE (CATALOGUE_ID);

ALTER TABLE TABLE_ANNOTATION
  ADD CONSTRAINT FK_TABLE_ANNOTATION_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE CATALOGUE_CONTEXTE
  ADD CONSTRAINT FK_CATALOGUE_CONTEXTE_CATALOGUE
      FOREIGN KEY (CATALOGUE_ID)
      REFERENCES CATALOGUE (CATALOGUE_ID);

ALTER TABLE CATALOGUE_CONTEXTE
  ADD CONSTRAINT FK_CATALOGUE_CONTEXTE_CONTEXTE
      FOREIGN KEY (CONTEXTE_ID)
      REFERENCES CONTEXTE (CONTEXTE_ID);

ALTER TABLE CHAMP_ANNOTATION
  ADD CONSTRAINT FK_CHAMP_ANNOTATION_DATA_TYPE_ID
      FOREIGN KEY (DATA_TYPE_ID)
      REFERENCES DATA_TYPE (DATA_TYPE_ID);

ALTER TABLE CHAMP_ANNOTATION
  ADD CONSTRAINT FK_CHAMP_ANNOTATION_TABLE_ANNOTATION_ID
      FOREIGN KEY (TABLE_ANNOTATION_ID)
      REFERENCES TABLE_ANNOTATION (TABLE_ANNOTATION_ID);

ALTER TABLE INDICATEUR
  ADD CONSTRAINT FK_INDICATEUR_TIMER_ID
      FOREIGN KEY (TIMER_ID)
      REFERENCES TIMER (TIMER_ID);

ALTER TABLE TEMPLATE
  ADD CONSTRAINT FK_TEMPLATE_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE TEMPLATE
  ADD CONSTRAINT FK_TEMPLATE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE BLOC_IMPRESSION
  ADD CONSTRAINT FK_BLOC_IMPRESSION_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE BLOC_IMPRESSION_TEMPLATE
  ADD CONSTRAINT FK_BLOC_IMPRESSION_TEMPLATE_TEMPLATE_ID
      FOREIGN KEY (TEMPLATE_ID)
      REFERENCES TEMPLATE (TEMPLATE_ID);

ALTER TABLE BLOC_IMPRESSION_TEMPLATE
  ADD CONSTRAINT FK_BLOC_IMPRESSION_TEMPLATE_BLOC_ID
      FOREIGN KEY (BLOC_IMPRESSION_ID)
      REFERENCES BLOC_IMPRESSION (BLOC_IMPRESSION_ID);

ALTER TABLE TABLE_ANNOTATION_TEMPLATE
  ADD CONSTRAINT FK_TABLE_ANNOTATION_TEMPLATE_TEMPLATE_ID
      FOREIGN KEY (TEMPLATE_ID)
      REFERENCES TEMPLATE (TEMPLATE_ID);

ALTER TABLE TABLE_ANNOTATION_TEMPLATE
  ADD CONSTRAINT FK_TABLE_ANNOTATION_TEMPLATE_TABLE_ID
      FOREIGN KEY (TABLE_ANNOTATION_ID)
      REFERENCES TABLE_ANNOTATION (TABLE_ANNOTATION_ID);

ALTER TABLE CHAMP_IMPRIME
  ADD CONSTRAINT FK_CHAMP_IMPRIME_TEMPLATE_ID
      FOREIGN KEY (TEMPLATE_ID)
      REFERENCES TEMPLATE (TEMPLATE_ID);

ALTER TABLE CHAMP_IMPRIME
  ADD CONSTRAINT FK_CHAMP_IMPRIME_BLOC_IMPRESSION_ID
      FOREIGN KEY (BLOC_IMPRESSION_ID)
      REFERENCES BLOC_IMPRESSION (BLOC_IMPRESSION_ID);

ALTER TABLE CHAMP_IMPRIME
  ADD CONSTRAINT FK_CHAMP_IMPRIME_CHAMP_ENTITE_ID
      FOREIGN KEY (CHAMP_ENTITE_ID)
      REFERENCES CHAMP_ENTITE (CHAMP_ENTITE_ID);

ALTER TABLE CHAMP_ENTITE_BLOC
  ADD CONSTRAINT FK_CHAMP_ENTITE_BLOC_BLOC_ID
      FOREIGN KEY (BLOC_IMPRESSION_ID)
      REFERENCES BLOC_IMPRESSION (BLOC_IMPRESSION_ID);

ALTER TABLE CHAMP_ENTITE_BLOC
  ADD CONSTRAINT FK_CHAMP_ENTITE_BLOC_CHAMP_ID
      FOREIGN KEY (CHAMP_ENTITE_ID)
      REFERENCES CHAMP_ENTITE (CHAMP_ENTITE_ID);

ALTER TABLE ITEM
  ADD CONSTRAINT FK_ITEM_CHAMP_ANNOTATION_ID
      FOREIGN KEY (CHAMP_ANNOTATION_ID)
      REFERENCES CHAMP_ANNOTATION (CHAMP_ANNOTATION_ID);
      
ALTER TABLE ITEM
  ADD CONSTRAINT FK_ITEM_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE CODE_SELECT
  ADD CONSTRAINT FK_CODE_SELECT_TABLE_CODAGE_ID
      FOREIGN KEY (TABLE_CODAGE_ID)
      REFERENCES TABLE_CODAGE (TABLE_CODAGE_ID);

ALTER TABLE CODE_SELECT
  ADD CONSTRAINT FK_CODE_SELECT_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);
      
ALTER TABLE CODE_SELECT
  ADD CONSTRAINT FK_CODE_SELECT_CODE_DOSSIER_ID
      FOREIGN KEY (CODE_DOSSIER_ID)
      REFERENCES CODE_DOSSIER (CODE_DOSSIER_ID);

ALTER TABLE CODE_SELECT
  ADD CONSTRAINT FK_CODE_SELECT_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE CODE_ASSIGNE
  ADD CONSTRAINT FK_CODE_ASSIGNE_TABLE_CODAGE_ID
      FOREIGN KEY (TABLE_CODAGE_ID)
      REFERENCES TABLE_CODAGE (TABLE_CODAGE_ID);

ALTER TABLE CODE_ASSIGNE
  ADD CONSTRAINT FK_CODE_ASSIGNE_ECHANTILLON_ID
     FOREIGN KEY (ECHANTILLON_ID)
      REFERENCES ECHANTILLON (ECHANTILLON_ID);
      
ALTER TABLE CODE_DOSSIER
  ADD CONSTRAINT FK_CODE_DOSSIER_DOSSIER_PARENT_ID
      FOREIGN KEY (DOSSIER_PARENT_ID)
      REFERENCES CODE_DOSSIER (CODE_DOSSIER_ID);

ALTER TABLE CODE_DOSSIER
  ADD CONSTRAINT FK_CODE_DOSSIER_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE CODE_DOSSIER
  ADD CONSTRAINT FK_CODE_DOSSIER_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);
      
ALTER TABLE CODE_UTILISATEUR
  ADD CONSTRAINT FK_CODE_UTILISATEUR_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);
      
ALTER TABLE CODE_UTILISATEUR
  ADD CONSTRAINT FK_CODE_PARENT_CODE_UTILISATEUR_ID
      FOREIGN KEY (CODE_PARENT_ID)
      REFERENCES CODE_UTILISATEUR (CODE_UTILISATEUR_ID);

ALTER TABLE CODE_UTILISATEUR
  ADD CONSTRAINT FK_CODE_UTILISATEUR_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);
      
ALTER TABLE CODE_UTILISATEUR
  ADD CONSTRAINT FK_CODE_UTILISATEUR_CODE_DOSSIER_ID
      FOREIGN KEY (CODE_DOSSIER_ID)
      REFERENCES CODE_DOSSIER (CODE_DOSSIER_ID);

ALTER TABLE SERVICE_COLLABORATEUR
  ADD CONSTRAINT FK_SERVICE_COLLABORATEUR_SERVICE_ID
      FOREIGN KEY (SERVICE_ID)
      REFERENCES SERVICE (SERVICE_ID);

ALTER TABLE SERVICE_COLLABORATEUR
  ADD CONSTRAINT FK_SERVICE_COLLABORATEUR_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE NUMEROTATION
  ADD CONSTRAINT FK_NUMEROTATION_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE NUMEROTATION
  ADD CONSTRAINT FK_NUMEROTATION_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

-- ALTER TABLE BANQUE_STOCKAGE
--  ADD CONSTRAINT FK_BANQUE_STOCKAGE_BANQUE_ID
--      FOREIGN KEY (BANQUE_ID)
--      REFERENCES BANQUE (BANQUE_ID);
--
-- ALTER TABLE BANQUE_STOCKAGE
--  ADD CONSTRAINT FK_BANQUE_STOCKAGE_SERVICE_ID
--      FOREIGN KEY (SERVICE_ID)
--      REFERENCES SERVICE (SERVICE_ID);

ALTER TABLE CEDER_OBJET
  ADD CONSTRAINT FK_CEDER_OBJET_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE CEDER_OBJET
  ADD CONSTRAINT FK_CEDER_OBJET_QUANTITE_UNITE_ID
      FOREIGN KEY (QUANTITE_UNITE_ID)
      REFERENCES UNITE (UNITE_ID);

ALTER TABLE CEDER_OBJET
  ADD CONSTRAINT FK_CEDER_OBJET_CESSION_ID
      FOREIGN KEY (CESSION_ID)
      REFERENCES CESSION (CESSION_ID);

ALTER TABLE RETOUR
  ADD CONSTRAINT FK_RETOUR_CESSION_ID
      FOREIGN KEY (CESSION_ID)
      REFERENCES CESSION (CESSION_ID);

ALTER TABLE RETOUR
  ADD CONSTRAINT FK_RETOUR_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE RETOUR
  ADD CONSTRAINT FK_RETOUR_TRANSFORMATION_ID
      FOREIGN KEY (TRANSFORMATION_ID)
      REFERENCES TRANSFORMATION (TRANSFORMATION_ID);

ALTER TABLE RETOUR
  ADD CONSTRAINT FK_RETOUR_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE RETOUR
  ADD CONSTRAINT FK_RETOUR_CONTENEUR_ID
      FOREIGN KEY (CONTENEUR_ID)
      REFERENCES CONTENEUR (CONTENEUR_ID);

ALTER TABLE RETOU
  ADD CONSTRAINT FK_RETOUR_INCIDENT_ID 
      FOREIGN KEY (INCIDENT_ID)
      REFERENCES INCIDENT (INCIDENT_ID);
      
ALTER TABLE RETOUR
  ADD CONSTRAINT FK_RETOUR_OBJET_STATUT_ID
      FOREIGN KEY (OBJET_STATUT_ID)
      REFERENCES OBJET_STATUT (OBJET_STATUT_ID);

ALTER TABLE CONTENEUR_BANQUE
  ADD CONSTRAINT FK_CONTENEUR_BANQUE_CONTENEUR_ID
      FOREIGN KEY (CONTENEUR_ID)
      REFERENCES CONTENEUR (CONTENEUR_ID);

ALTER TABLE CONTENEUR_BANQUE
  ADD CONSTRAINT FK_CONTENEUR_BANQUE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE CONTENEUR_PLATEFORME
  ADD CONSTRAINT FK_CONTENEUR_PLATEFORME_CONTENEUR_ID
      FOREIGN KEY (CONTENEUR_ID)
      REFERENCES CONTENEUR (CONTENEUR_ID);

ALTER TABLE CONTENEUR_PLATEFORME
  ADD CONSTRAINT FK_CONTENEUR_PLATEFORME_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE ENCEINTE_BANQUE
  ADD CONSTRAINT FK_ENCEINTE_BANQUE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE ENCEINTE_BANQUE
  ADD CONSTRAINT FK_ENCEINTE_BANQUE_ENCEINTE_ID
      FOREIGN KEY (ENCEINTE_ID)
      REFERENCES ENCEINTE (ENCEINTE_ID);

ALTER TABLE IMPRIMANTE
  ADD CONSTRAINT FK_IMPRIMANTE_IMPRIMANTE_API_ID
      FOREIGN KEY (IMPRIMANTE_API_ID)
      REFERENCES IMPRIMANTE_API (IMPRIMANTE_API_ID);

ALTER TABLE IMPRIMANTE
  ADD CONSTRAINT FK_IMPRIMANTE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE AFFECTATION_IMPRIMANTE
  ADD CONSTRAINT FK_AFFECTATION_IMPRIMANTE_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE AFFECTATION_IMPRIMANTE
  ADD CONSTRAINT FK_AFFECTATION_IMPRIMANTE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE AFFECTATION_IMPRIMANTE
  ADD CONSTRAINT FK_AFFECTATION_IMPRIMANTE_IMPRIMANTE_ID
      FOREIGN KEY (IMPRIMANTE_ID)
      REFERENCES IMPRIMANTE (IMPRIMANTE_ID);

ALTER TABLE AFFECTATION_IMPRIMANTE
  ADD CONSTRAINT FK_AFFECTATION_IMPRIMANTE_MODELE_ID
      FOREIGN KEY (MODELE_ID)
      REFERENCES MODELE (MODELE_ID);

ALTER TABLE PLATEFORME_ADMINISTRATEUR
  ADD CONSTRAINT FK_PLATEFORME_ADMINISTRATEUR_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE PLATEFORME_ADMINISTRATEUR
  ADD CONSTRAINT FK_PLATEFORME_ADMINISTRATEUR_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE PROFIL_UTILISATEUR
  ADD CONSTRAINT FK_PROFIL_UTILISATEUR_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE PROFIL_UTILISATEUR
  ADD CONSTRAINT FK_PROFIL_UTILISATEUR_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);
      
ALTER TABLE PROFIL
  ADD CONSTRAINT FK_PROFIL_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE PROFIL_UTILISATEUR
  ADD CONSTRAINT FK_PROFIL_UTILISATEUR_PROFIL_ID
      FOREIGN KEY (PROFIL_ID)
      REFERENCES PROFIL (PROFIL_ID);

ALTER TABLE DROIT_OBJET
  ADD CONSTRAINT FK_DROIT_OBJET_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE DROIT_OBJET
  ADD CONSTRAINT FK_DROIT_OBJET_PROFIL_ID
      FOREIGN KEY (PROFIL_ID)
      REFERENCES PROFIL (PROFIL_ID);

ALTER TABLE DROIT_OBJET
  ADD CONSTRAINT FK_DROIT_OBJET_OPERATION_TYPE_ID
      FOREIGN KEY (OPERATION_TYPE_ID)
      REFERENCES OPERATION_TYPE (OPERATION_TYPE_ID);

ALTER TABLE MESSAGE
  ADD CONSTRAINT FK_MESSAGE_DESTINATAIRE_ID
      FOREIGN KEY (DESTINATAIRE_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE MESSAGE
  ADD CONSTRAINT FK_MESSAGE_EXPEDITEUR_ID
      FOREIGN KEY (EXPEDITEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE PRELEVEMENT_RISQUE
  ADD CONSTRAINT FK_PRELEVEMENT_RISQUE_RISQUE_ID
      FOREIGN KEY (RISQUE_ID)
      REFERENCES RISQUE (RISQUE_ID);

ALTER TABLE PRELEVEMENT_RISQUE
  ADD CONSTRAINT FK_PRELEVEMENT_RISQUE_PRELEVEMENT_ID
      FOREIGN KEY (PRELEVEMENT_ID)
      REFERENCES PRELEVEMENT (PRELEVEMENT_ID);

ALTER TABLE LABO_INTER
  ADD CONSTRAINT FK_LABO_INTER_PRELEVEMENT_ID
      FOREIGN KEY (PRELEVEMENT_ID)
      REFERENCES PRELEVEMENT (PRELEVEMENT_ID);

ALTER TABLE LABO_INTER
  ADD CONSTRAINT FK_LABO_INTER_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE LABO_INTER
  ADD CONSTRAINT FK_LABO_INTER_TRANSPORTEUR_ID
      FOREIGN KEY (TRANSPORTEUR_ID)
      REFERENCES TRANSPORTEUR (TRANSPORTEUR_ID);

ALTER TABLE LABO_INTER
  ADD CONSTRAINT FK_LABO_INTER_SERVICE_ID
      FOREIGN KEY (SERVICE_ID)
      REFERENCES SERVICE (SERVICE_ID);

ALTER TABLE MALADIE_MEDECIN
  ADD CONSTRAINT FK_MALADIE_MEDECIN_MALADIE_ID
      FOREIGN KEY (MALADIE_ID)
      REFERENCES MALADIE (MALADIE_ID);

ALTER TABLE MALADIE_MEDECIN
  ADD CONSTRAINT FK_MALADIE_MEDECIN_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE PATIENT_MEDECIN
  ADD CONSTRAINT FK_PATIENT_MEDECIN_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE PATIENT_MEDECIN
  ADD CONSTRAINT FK_PATIENT_MEDECIN_PATIENT_ID
      FOREIGN KEY (PATIENT_ID)
      REFERENCES PATIENT (PATIENT_ID);

ALTER TABLE PATIENT_LIEN
  ADD CONSTRAINT FK_PATIENT_LIEN_LIEN_FAMILIAL_ID
      FOREIGN KEY (LIEN_FAMILIAL_ID)
      REFERENCES LIEN_FAMILIAL (LIEN_FAMILIAL_ID);

ALTER TABLE PATIENT_LIEN
  ADD CONSTRAINT FK_PATIENT_LIEN_PATIENT1_ID
      FOREIGN KEY (PATIENT1_ID)
      REFERENCES PATIENT (PATIENT_ID);

ALTER TABLE PATIENT_LIEN
  ADD CONSTRAINT FK_PATIENT_LIEN_PATIENT2_ID
      FOREIGN KEY (PATIENT2_ID)
      REFERENCES PATIENT (PATIENT_ID);

ALTER TABLE TABLE_ANNOTATION_BANQUE
  ADD CONSTRAINT FK_TABLE_ANNOTATION_BANQUE_TABLE_ANNOTATION_ID
      FOREIGN KEY (TABLE_ANNOTATION_ID)
      REFERENCES TABLE_ANNOTATION (TABLE_ANNOTATION_ID);

ALTER TABLE TABLE_ANNOTATION_BANQUE
  ADD CONSTRAINT FK_TABLE_ANNOTATION_BANQUE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE ANNOTATION_VALEUR
  ADD CONSTRAINT FK_ANNOTATION_VALEUR_ITEM_ID
      FOREIGN KEY (ITEM_ID)
      REFERENCES ITEM (ITEM_ID);
      
ALTER TABLE ANNOTATION_VALEUR
  ADD CONSTRAINT FK_ANNOTATION_VALEUR_FICHIER_ID
      FOREIGN KEY (FICHIER_ID)
      REFERENCES FICHIER (FICHIER_ID)
      ON DELETE SET NULL;

ALTER TABLE ANNOTATION_VALEUR
  ADD CONSTRAINT FK_ANNOTATION_VALEUR_CHAMP_ANNOTATION_ID
      FOREIGN KEY (CHAMP_ANNOTATION_ID)
      REFERENCES CHAMP_ANNOTATION (CHAMP_ANNOTATION_ID);
      
ALTER TABLE ANNOTATION_VALEUR
  ADD CONSTRAINT FK_ANNOTATION_VALEUR_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE ANNOTATION_DEFAUT
  ADD CONSTRAINT FK_ANNOTATION_DEFAUT_ITEM_ID
      FOREIGN KEY (ITEM_ID)
      REFERENCES ITEM (ITEM_ID);

ALTER TABLE ANNOTATION_DEFAUT
  ADD CONSTRAINT FK_ANNOTATION_DEFAUT_CHAMP_ANNOTATION_ID
      FOREIGN KEY (CHAMP_ANNOTATION_ID)
      REFERENCES CHAMP_ANNOTATION (CHAMP_ANNOTATION_ID);
      
ALTER TABLE ANNOTATION_DEFAUT
  ADD CONSTRAINT FK_ANNOTATION_DEFAUT_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE INDICATEUR_SQL
  ADD CONSTRAINT FK_INDICATEUR_SQL_INDICATEUR_ID
      FOREIGN KEY (INDICATEUR_ID)
      REFERENCES INDICATEUR (INDICATEUR_ID);

ALTER TABLE INDICATEUR_REQUETE
  ADD CONSTRAINT FK_INDICATEUR_REQUETE_INDICATEUR_ID
      FOREIGN KEY (INDICATEUR_ID)
      REFERENCES INDICATEUR (INDICATEUR_ID);

ALTER TABLE INDICATEUR_PLATEFORME
  ADD CONSTRAINT FK_INDICATEUR_PLATEFORME_INDICATEUR_ID
      FOREIGN KEY (INDICATEUR_ID)
      REFERENCES INDICATEUR (INDICATEUR_ID);

ALTER TABLE INDICATEUR_PLATEFORME
  ADD CONSTRAINT FK_INDICATEUR_PLATEFORME_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE INDICATEUR_BANQUE
  ADD CONSTRAINT FK_INDICATEUR_BANQUE_INDICATEUR_ID
      FOREIGN KEY (INDICATEUR_ID)
      REFERENCES INDICATEUR (INDICATEUR_ID);

ALTER TABLE INDICATEUR_BANQUE
  ADD CONSTRAINT FK_INDICATEUR_BANQUE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE OPERATION
  ADD CONSTRAINT FK_OPERATION_OPERATION_TYPE_ID
      FOREIGN KEY (OPERATION_TYPE_ID)
      REFERENCES OPERATION_TYPE (OPERATION_TYPE_ID);

ALTER TABLE OPERATION
  ADD CONSTRAINT FK_OPERATION_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE OPERATION
  ADD CONSTRAINT FK_OPERATION_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE CONTRAT
  ADD CONSTRAINT FK_CONTRAT_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE CONTRAT
  ADD CONSTRAINT FK_CONTRAT_PROTOCOLE_TYPE_ID
      FOREIGN KEY (PROTOCOLE_TYPE_ID)
      REFERENCES PROTOCOLE_TYPE (PROTOCOLE_TYPE_ID) 
      ON DELETE SET NULL;

ALTER TABLE CONTRAT
  ADD CONSTRAINT FK_CONTRAT_SERVICE_ID
      FOREIGN KEY (SERVICE_ID)
      REFERENCES SERVICE (SERVICE_ID);

ALTER TABLE CONTRAT
  ADD CONSTRAINT FK_CONTRAT_COLLABORATEUR_ID
      FOREIGN KEY (COLLABORATEUR_ID)
      REFERENCES COLLABORATEUR (COLLABORATEUR_ID);

ALTER TABLE CONTRAT
  ADD CONSTRAINT FK_CONTRAT_ETABLISSEMENT_ID 
	  FOREIGN KEY (ETABLISSEMENT_ID)
      REFERENCES ETABLISSEMENT (ETABLISSEMENT_ID);

ALTER TABLE COULEUR_ENTITE_TYPE
  ADD CONSTRAINT FK_COULEUR_ENTITE_TYPE_COULEUR_ID 
      FOREIGN KEY (COULEUR_ID)
      REFERENCES COULEUR (COULEUR_ID);

ALTER TABLE COULEUR_ENTITE_TYPE
  ADD CONSTRAINT FK_COULEUR_ENTITE_TYPE_BANQUE_ID 
	  FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE COULEUR_ENTITE_TYPE
  ADD CONSTRAINT FK_COULEUR_ENTITE_TYPE_ECHANTILLON_TYPE_ID 
	  FOREIGN KEY (ECHANTILLON_TYPE_ID)
      REFERENCES ECHANTILLON_TYPE (ECHANTILLON_TYPE_ID);

ALTER TABLE COULEUR_ENTITE_TYPE
  ADD CONSTRAINT FK_COULEUR_ENTITE_TYPE_PROD_TYPE_ID 
	  FOREIGN KEY (PROD_TYPE_ID)
      REFERENCES PROD_TYPE (PROD_TYPE_ID);
      
ALTER TABLE TRANSCODE_UTILISATEUR
  ADD CONSTRAINT FK_TRANSCODE_UTILISATEUR_CODE_UTILISATEUR_ID
      FOREIGN KEY (CODE_UTILISATEUR_ID)
      REFERENCES CODE_UTILISATEUR (CODE_UTILISATEUR_ID);

ALTER TABLE TRANSCODE_UTILISATEUR
  ADD CONSTRAINT FK_TRANSCODE_UTILISATEUR_TABLE_CODAGE_ID
      FOREIGN KEY (TABLE_CODAGE_ID)
      REFERENCES TABLE_CODAGE (TABLE_CODAGE_ID);
      
ALTER TABLE CHAMP_ENTITE
  ADD CONSTRAINT FK_CHAMP_ENTITE_CHAMP_ENTITE_ID
        FOREIGN KEY (ENTITE_ID)
        REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE CHAMP_ENTITE
  ADD CONSTRAINT FK_CHAMP_ENTITE_DATA_TYPE_ID
        FOREIGN KEY (DATA_TYPE_ID)
        REFERENCES DATA_TYPE (DATA_TYPE_ID);
        
ALTER TABLE CHAMP
  ADD CONSTRAINT FK_CHAMP_CHAMP_ANNOTATION_ID
        FOREIGN KEY (CHAMP_ANNOTATION_ID)
        REFERENCES CHAMP_ANNOTATION (CHAMP_ANNOTATION_ID);
        
ALTER TABLE CHAMP
  ADD CONSTRAINT FK_CHAMP_CHAMP_ENTITE_ID
        FOREIGN KEY (CHAMP_ENTITE_ID)
        REFERENCES CHAMP_ENTITE (CHAMP_ENTITE_ID);
        
ALTER TABLE CHAMP
   ADD CONSTRAINT FK_CHAMP_CHAMP_PARENT_ID
        FOREIGN KEY (CHAMP_PARENT_ID)
        REFERENCES CHAMP (CHAMP_ID);
        
ALTER TABLE COMBINAISON
  ADD CONSTRAINT FK_CRITERE_CHAMP1_ID
        FOREIGN KEY (CHAMP1_ID)
        REFERENCES CHAMP (CHAMP_ID);
        
ALTER TABLE COMBINAISON
  ADD CONSTRAINT FK_CRITERE_CHAMP2_ID
        FOREIGN KEY (CHAMP2_ID)
        REFERENCES CHAMP (CHAMP_ID);
        
ALTER TABLE CRITERE
  ADD CONSTRAINT FK_CRITERE_CHAMP_ID
        FOREIGN KEY (CHAMP_ID)
        REFERENCES CHAMP (CHAMP_ID);
        
ALTER TABLE CRITERE
  ADD CONSTRAINT FK_CRITERE_COMBINAISON_ID
        FOREIGN KEY (COMBINAISON_ID)
        REFERENCES COMBINAISON (COMBINAISON_ID)
        ON DELETE CASCADE;
        -- ON UPDATE CASCADE;
        
ALTER TABLE AFFICHAGE
  ADD CONSTRAINT FK_AFFICHAGE_CREATEUR_ID
        FOREIGN KEY (CREATEUR_ID)
        REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE AFFICHAGE
  ADD CONSTRAINT FK_AFFICHAGE_BANQUE_ID
        FOREIGN KEY (BANQUE_ID)
        REFERENCES BANQUE (BANQUE_ID);
-- 121        
ALTER TABLE RESULTAT
  ADD CONSTRAINT FK_RESULTAT_CHAMP_ID
        FOREIGN KEY (CHAMP_ID)
        REFERENCES CHAMP (CHAMP_ID);
--    
ALTER TABLE RESULTAT
  ADD CONSTRAINT FK_RESULTAT_AFFICHAGE_ID
        FOREIGN KEY (AFFICHAGE_ID)
        REFERENCES AFFICHAGE (AFFICHAGE_ID)
        ON DELETE CASCADE;
        -- ON UPDATE CASCADE;
  
ALTER TABLE GROUPEMENT
  ADD CONSTRAINT FK_GROUPEMENT_CRITERE1_ID
        FOREIGN KEY (CRITERE1_ID)
        REFERENCES CRITERE (CRITERE_ID)
		ON DELETE CASCADE;
		-- ON UPDATE CASCADE;
		
ALTER TABLE GROUPEMENT
  ADD CONSTRAINT FK_GROUPEMENT_CRITERE2_ID
        FOREIGN KEY (CRITERE2_ID)
        REFERENCES CRITERE (CRITERE_ID)
		ON DELETE CASCADE;
		-- ON UPDATE CASCADE;
-- 121		
ALTER TABLE REQUETE
  ADD CONSTRAINT FK_REQUETE_CREATEUR_ID
        FOREIGN KEY (CREATEUR_ID)
        REFERENCES UTILISATEUR (UTILISATEUR_ID);
--
ALTER TABLE REQUETE
  ADD CONSTRAINT FK_REQUETE_BANQUE_ID
        FOREIGN KEY (BANQUE_ID)
        REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE REQUETE
  ADD CONSTRAINT FK_REQUETE_GROUPEMENT_RACINE_ID
        FOREIGN KEY (GROUPEMENT_RACINE_ID)
        REFERENCES GROUPEMENT (GROUPEMENT_ID)
		ON DELETE CASCADE;
		-- ON UPDATE CASCADE;
		
ALTER TABLE RECHERCHE
  ADD CONSTRAINT FK_RECHERCHE_CREATEUR_ID
        FOREIGN KEY (CREATEUR_ID)
        REFERENCES UTILISATEUR (UTILISATEUR_ID);
        
ALTER TABLE RECHERCHE
  ADD CONSTRAINT FK_RECHERCHE_AFFICHAGE_ID
        FOREIGN KEY (AFFICHAGE_ID)
        REFERENCES AFFICHAGE (AFFICHAGE_ID);
        
ALTER TABLE RECHERCHE
  ADD CONSTRAINT FK_RECHERCHE_REQUETE_ID
        FOREIGN KEY (REQUETE_ID)
        REFERENCES REQUETE (REQUETE_ID);
        
ALTER TABLE RECHERCHE_BANQUE
  ADD CONSTRAINT FK_RECHERCHE_BANQUE_RECHERCHE_ID
        FOREIGN KEY (RECHERCHE_ID)
        REFERENCES RECHERCHE (RECHERCHE_ID);
        
ALTER TABLE RECHERCHE_BANQUE
  ADD CONSTRAINT FK_RECHERCHE_BANQUE_BANQUE_ID
        FOREIGN KEY (BANQUE_ID)
        REFERENCES BANQUE (BANQUE_ID);
        
ALTER TABLE BANQUE_TABLE_CODAGE
  ADD CONSTRAINT FK_BANQUE_TABLE_CODAGE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE BANQUE_TABLE_CODAGE
  ADD CONSTRAINT FK_BANQUE_TABLE_CODAGE_ID
      FOREIGN KEY (TABLE_CODAGE_ID)
      REFERENCES TABLE_CODAGE (TABLE_CODAGE_ID);
      
ALTER TABLE FANTOME
  ADD CONSTRAINT FK_FANTOME_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE IMPORT_TEMPLATE
  ADD CONSTRAINT FK_IMPORT_TEMPLATE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);

ALTER TABLE IMPORT_TEMPLATE_ENTITE
  ADD CONSTRAINT FK_IMPORT_TEMPLATE_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE IMPORT_TEMPLATE_ENTITE
  ADD CONSTRAINT FK_IMPORT_TEMPLATE_ENTITE_IMPORT_TEMPLATE_ID
      FOREIGN KEY (IMPORT_TEMPLATE_ID)
      REFERENCES IMPORT_TEMPLATE (IMPORT_TEMPLATE_ID);

ALTER TABLE IMPORT_COLONNE
  ADD CONSTRAINT FK_IMPORT_COLONNE_IMPORT_TEMPLATE_ID
      FOREIGN KEY (IMPORT_TEMPLATE_ID)
      REFERENCES IMPORT_TEMPLATE (IMPORT_TEMPLATE_ID);

ALTER TABLE IMPORT_COLONNE
  ADD CONSTRAINT FK_IMPORT_COLONNE_CHAMP_ID
      FOREIGN KEY (CHAMP_ID)
      REFERENCES CHAMP (CHAMP_ID);

ALTER TABLE IMPORT_HISTORIQUE
  ADD CONSTRAINT FK_IMPORT_HISTORIQUE_IMPORT_TEMPLATE_ID
      FOREIGN KEY (IMPORT_TEMPLATE_ID)
      REFERENCES IMPORT_TEMPLATE (IMPORT_TEMPLATE_ID);

ALTER TABLE IMPORT_HISTORIQUE
  ADD CONSTRAINT FK_IMPORT_HISTORIQUE_IMPORT_UTILISATEUR_ID
      FOREIGN KEY (UTILISATEUR_ID)
      REFERENCES UTILISATEUR (UTILISATEUR_ID);

ALTER TABLE IMPORTATION
  ADD CONSTRAINT FK_IMPORTATION_IMPORT_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE IMPORTATION
  ADD CONSTRAINT FK_IMPORTATION_IMPORT_HISTORIQUE_ID
      FOREIGN KEY (IMPORT_HISTORIQUE_ID)
      REFERENCES IMPORT_HISTORIQUE (IMPORT_HISTORIQUE_ID);

ALTER TABLE RISQUE
  ADD CONSTRAINT FK_RISQUE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE NATURE
  ADD CONSTRAINT FK_NATURE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE PRELEVEMENT_TYPE
  ADD CONSTRAINT FK_PRELEVEMENT_TYPE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE CONDIT_MILIEU
  ADD CONSTRAINT FK_CONDIT_MILIEU_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE CONDIT_TYPE
  ADD CONSTRAINT FK_CONDIT_TYPE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE CONSENT_TYPE
  ADD CONSTRAINT FK_CONSENT_TYPE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE ECHANTILLON_TYPE
  ADD CONSTRAINT FK_ECHANTILLON_TYPE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE ECHAN_QUALITE
  ADD CONSTRAINT FK_ECHAN_QUALITE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE MODE_PREPA
  ADD CONSTRAINT FK_MODE_PREPA_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE PROD_TYPE
  ADD CONSTRAINT FK_PROD_TYPE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE PROD_QUALITE
  ADD CONSTRAINT FK_PROD_QUALITE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE MODE_PREPA_DERIVE
  ADD CONSTRAINT FK_MODE_PREPA_DERIVE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE CESSION_EXAMEN
  ADD CONSTRAINT FK_CESSION_EXAMEN_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE DESTRUCTION_MOTIF
  ADD CONSTRAINT FK_DESTRUCTION_MOTIF_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE PROTOCOLE_TYPE
  ADD CONSTRAINT FK_PROTOCOLE_TYPE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE CONTENEUR_TYPE
  ADD CONSTRAINT FK_CONTENEUR_TYPE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE ENCEINTE_TYPE
  ADD CONSTRAINT FK_ENCEINTE_TYPE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE BANQUE_CATALOGUE
  ADD CONSTRAINT FK_BANQUE_CATALOGUE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);
      
ALTER TABLE BANQUE_CATALOGUE
  ADD CONSTRAINT FK_BANQUE_CATALOGUE_CATALOGUE_ID
      FOREIGN KEY (CATALOGUE_ID)
      REFERENCES CATALOGUE (CATALOGUE_ID);

ALTER TABLE NON_CONFORMITE
  ADD CONSTRAINT FK_NON_CONFORMITE_CONFORMITE_TYPE_ID
      FOREIGN KEY (CONFORMITE_TYPE_ID)
      REFERENCES CONFORMITE_TYPE (CONFORMITE_TYPE_ID);
      
ALTER TABLE CONFORMITE_TYPE
  ADD CONSTRAINT FK_CONFORMITE_TYPE_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);

ALTER TABLE NON_CONFORMITE
  ADD CONSTRAINT FK_NON_CONFORMITE_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

ALTER TABLE OBJET_NON_CONFORME
  ADD CONSTRAINT FK_OBJET_NON_CONFORME_NON_CONFORMITE_ID
      FOREIGN KEY (NON_CONFORMITE_ID)
      REFERENCES NON_CONFORMITE (NON_CONFORMITE_ID);

ALTER TABLE OBJET_NON_CONFORME
  ADD CONSTRAINT FK_OBJET_NON_CONFORME_ENTITE_ID
      FOREIGN KEY (ENTITE_ID)
      REFERENCES ENTITE (ENTITE_ID);
      
ALTER TABLE UTILISATEUR
  ADD CONSTRAINT FK_UTIL_PF_ORIG_ID
      FOREIGN KEY (PLATEFORME_ORIG_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);
      
ALTER TABLE CONSULTATION_INTF 
	ADD CONSTRAINT FK_CONSULT_INTF_UTIL_ID 
	FOREIGN KEY (UTILISATEUR_ID) 
	REFERENCES UTILISATEUR (UTILISATEUR_ID);
