ALTER TABLE ADICAP
  ADD CONSTRAINT FK_ADICAP_ADICAP_PARENT_ID
      FOREIGN KEY (ADICAP_PARENT_ID)
      REFERENCES ADICAP (ADICAP_ID);

ALTER TABLE ADICAP
  ADD CONSTRAINT FK_ADICAP_ADICAP_GROUPE_ID
      FOREIGN KEY (ADICAP_GROUPE_ID)
      REFERENCES ADICAP_GROUPE (ADICAP_GROUPE_ID);

ALTER TABLE CIM_LIBELLE
  ADD CONSTRAINT FK_LIBELLE_SID
      FOREIGN KEY (SID)
      REFERENCES CIM_MASTER (SID);

ALTER TABLE ADICAPCIM_TOPO
  ADD CONSTRAINT FK_ADICAPCIMO_TOPO_SID
      FOREIGN KEY (SID)
      REFERENCES CIM_MASTER (SID);

ALTER TABLE ADICAPCIM_TOPO
  ADD CONSTRAINT FK_ADICAPCIM_TOPO_ADICAP_ID
      FOREIGN KEY (ADICAP_ID)
      REFERENCES ADICAP (ADICAP_ID);

ALTER TABLE ADICAPCIMO_MORPHO
  ADD CONSTRAINT FK_ADICAPCIMO_MORPHO_ADICAP_ID
      FOREIGN KEY (ADICAP_ID)
      REFERENCES ADICAP (ADICAP_ID);

ALTER TABLE ADICAPCIMO_MORPHO
  ADD CONSTRAINT FK_ADICAPCIMO_MORPHO_CIMO_ID
      FOREIGN KEY (CIMO_MORPHO_ID)
      REFERENCES CIMO_MORPHO (CIMO_MORPHO_ID);

ALTER TABLE CIM_CHAPTER
  ADD CONSTRAINT FK_CIM_CHAPTER_SID
      FOREIGN KEY (SID)
      REFERENCES CIM_MASTER (SID);