update PRELEVEMENT set CONFORME_ARRIVEE=null where CONFORME_ARRIVEE=0;
update ECHANTILLON set CONFORME_TRAITEMENT=null where CONFORME_TRAITEMENT=0;
update ECHANTILLON set CONFORME_CESSION=null where CONFORME_CESSION=0;