-- H2 SQL insert statements created from XML data
-- Tables: PATIENT_SIP, PATIENT_SIP_SEJOUR, LOGICIEL, EMETTEUR, DOSSIER_EXTERNE,
-- BLOC_EXTERNE, VALEUR_EXTERNE, RECEPTEUR, SCAN_DEVICE, SCAN_TERMINALE, SCAN_TUBE

-- Clear existing data (if needed)
DELETE FROM VALEUR_EXTERNE;
DELETE FROM BLOC_EXTERNE;
DELETE FROM DOSSIER_EXTERNE;
DELETE FROM RECEPTEUR;
DELETE FROM EMETTEUR;
DELETE FROM LOGICIEL;
DELETE FROM PATIENT_SIP_SEJOUR;
DELETE FROM PATIENT_SIP;
DELETE FROM SCAN_TUBE;
DELETE FROM SCAN_TERMINALE;
DELETE FROM SCAN_DEVICE;

-- Insert data into PATIENT_SIP
INSERT INTO PATIENT_SIP (PATIENT_SIP_ID, NIP, NOM, NOM_NAISSANCE, PRENOM, SEXE, DATE_NAISSANCE, VILLE_NAISSANCE, PAYS_NAISSANCE, PATIENT_ETAT, DATE_ETAT, DATE_DECES, DATE_CREATION, DATE_MODIFICATION)
VALUES (1, '12345', 'FROMSIP1', NULL, 'Jean', 'M', '1975-12-25', 'Paris', 'FRANCE', 'V', NULL, NULL, '2011-04-30 17:10:00', NULL);

INSERT INTO PATIENT_SIP (PATIENT_SIP_ID, NIP, NOM, NOM_NAISSANCE, PRENOM, SEXE, DATE_NAISSANCE, VILLE_NAISSANCE, PAYS_NAISSANCE, PATIENT_ETAT, DATE_ETAT, DATE_DECES, DATE_CREATION, DATE_MODIFICATION)
VALUES (2, '666', 'Lucifer', 'Devil', 'Josee', 'F', '0666-06-06', NULL, NULL, 'V', NULL, NULL, '2011-04-30 18:10:00', '2011-04-31 06:06:06');

INSERT INTO PATIENT_SIP (PATIENT_SIP_ID, NIP, NOM, NOM_NAISSANCE, PRENOM, SEXE, DATE_NAISSANCE, VILLE_NAISSANCE, PAYS_NAISSANCE, PATIENT_ETAT, DATE_ETAT, DATE_DECES, DATE_CREATION, DATE_MODIFICATION)
VALUES (3, '713705', 'Sun', NULL, 'Heat', 'Ind', '1990-12-04', NULL, NULL, 'Inconnu', NULL, NULL, '2011-04-30 17:17:17', '2011-04-31 07:07:07');

-- Insert data into PATIENT_SIP_SEJOUR
INSERT INTO PATIENT_SIP_SEJOUR (PATIENT_SIP_SEJOUR_ID, NUMERO, DATE_SEJOUR, PATIENT_SIP_ID)
VALUES (1, 'LUCY_6661', '1911-12-21', 2);

INSERT INTO PATIENT_SIP_SEJOUR (PATIENT_SIP_SEJOUR_ID, NUMERO, DATE_SEJOUR, PATIENT_SIP_ID)
VALUES (2, 'LUCY_6662', '1961-12-21', 2);

INSERT INTO PATIENT_SIP_SEJOUR (PATIENT_SIP_SEJOUR_ID, NUMERO, DATE_SEJOUR, PATIENT_SIP_ID)
VALUES (3, 'LUCY_6663', '2011-12-21', 2);

INSERT INTO PATIENT_SIP_SEJOUR (PATIENT_SIP_SEJOUR_ID, NUMERO, DATE_SEJOUR, PATIENT_SIP_ID)
VALUES (4, '770000391', '2012-11-21', 3);

-- Insert data into LOGICIEL
INSERT INTO LOGICIEL (LOGICIEL_ID, NOM, EDITEUR, VERSION)
VALUES (1, 'APIX', 'TECHNIDATA', '1.0');

INSERT INTO LOGICIEL (LOGICIEL_ID, NOM, EDITEUR, VERSION)
VALUES (2, 'DIAMIC', 'Infologic-santé', '1.0');

INSERT INTO LOGICIEL (LOGICIEL_ID, NOM, EDITEUR, VERSION)
VALUES (3, 'Glims', 'MIPS', '1.0');

-- Insert data into EMETTEUR
INSERT INTO EMETTEUR (EMETTEUR_ID, LOGICIEL_ID, IDENTIFICATION, SERVICE, OBSERVATIONS)
VALUES (1, 3, 'Glims Hémato', 'Service Hématologie - Saint-Louis', 'SGL Glims pour le service d''Hématologie de l''Hôpital Saint-Louis');

INSERT INTO EMETTEUR (EMETTEUR_ID, LOGICIEL_ID, IDENTIFICATION, SERVICE, OBSERVATIONS)
VALUES (2, 1, 'Apix Anapath', 'ANAP', 'SGL APIX pour le service d''Anatomo-Patholgie de l''Hôpital Saint-Louis');

INSERT INTO EMETTEUR (EMETTEUR_ID, LOGICIEL_ID, IDENTIFICATION, SERVICE, OBSERVATIONS)
VALUES (3, 1, 'Apix Hémato', 'HEMATO', 'SGL APIX pour le service d''Hématologie de l''Hôpital Saint-Louis');

-- Insert data into DOSSIER_EXTERNE
INSERT INTO DOSSIER_EXTERNE (DOSSIER_EXTERNE_ID, EMETTEUR_ID, IDENTIFICATION_DOSSIER, DATE_OPERATION, OPERATION)
VALUES (1, 2, '758910000', '2011-08-04 08:12:00', 'CM');

INSERT INTO DOSSIER_EXTERNE (DOSSIER_EXTERNE_ID, EMETTEUR_ID, IDENTIFICATION_DOSSIER, DATE_OPERATION, OPERATION)
VALUES (2, 2, '10245XCDV56', '2011-08-17 14:31:00', 'HD');

INSERT INTO DOSSIER_EXTERNE (DOSSIER_EXTERNE_ID, EMETTEUR_ID, IDENTIFICATION_DOSSIER, DATE_OPERATION, OPERATION)
VALUES (3, 2, 'X459GCT', '2011-08-21 10:16:00', 'CM');

INSERT INTO DOSSIER_EXTERNE (DOSSIER_EXTERNE_ID, EMETTEUR_ID, IDENTIFICATION_DOSSIER, DATE_OPERATION, OPERATION)
VALUES (4, 3, 'X459GCT', '2011-08-22 90:29:00', 'DC');

INSERT INTO DOSSIER_EXTERNE (DOSSIER_EXTERNE_ID, EMETTEUR_ID, IDENTIFICATION_DOSSIER, DATE_OPERATION, OPERATION)
VALUES (5, 2, '1000047UI', '2011-09-04 08:58:00', 'HD');

INSERT INTO DOSSIER_EXTERNE (DOSSIER_EXTERNE_ID, EMETTEUR_ID, IDENTIFICATION_DOSSIER, DATE_OPERATION, OPERATION)
VALUES (6, 3, 'PRLVT1', '2010-10-03 16:01:00', 'CM');

-- Insert data into BLOC_EXTERNE
INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (1, 1, 1, 1);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (2, 1, 2, 2);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (3, 1, 3, 3);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (4, 1, 3, 4);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (5, 3, 1, 1);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (6, 3, 7, 2);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (7, 3, 2, 3);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (8, 6, 1, 1);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (9, 6, 2, 2);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (10, 4, 1, 1);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (11, 4, 7, 2);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (12, 4, 2, 3);

INSERT INTO BLOC_EXTERNE (BLOC_EXTERNE_ID, DOSSIER_EXTERNE_ID, ENTITE_ID, ORDRE)
VALUES (13, 4, 3, 4);

-- Insert data into VALEUR_EXTERNE
INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (1, 1, 'HOUSE', 3, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (2, 1, 'GREGORY', 5, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (3, 1, 'M', 6, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (4, 1, 'ANNO', NULL, 1);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (5, 2, '20110816102930', 30, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (6, 2, 'PRLVT_TEST', 23, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (7, 2, 'SANG', 24, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (8, 5, '1245380054', 2, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (9, 5, 'COBAIN', 3, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (10, 5, 'NIRVANA', 4, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (11, 5, 'KURT', 5, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (12, 5, 'M', 6, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (13, 5, '19670220000000', 7, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (14, 5, 'USA', 9, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (15, 5, 'SEATTLE', 8, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (16, 5, 'D', 10, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (17, 5, '19940405000000', 12, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (18, 5, '20100805000000', 11, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (19, 6, 'Addiction Héroine', 17, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (20, 6, 'ADH', 18, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (21, 6, '19860725000000', 20, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (22, 6, '19901113000000', 19, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (23, 7, 'X459GCT', 23, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (24, 7, 'SANG', 24, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (25, 7, 'TH112489200', 45, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (26, 7, 'NDA127896', 44, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (27, 7, '19900110124500', 30, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (28, 7, 'PONCTION', 31, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (29, 7, '0', 47, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (30, 7, 'TUBE', 32, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (31, 7, 'SEC', 33, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (32, 7, '1', 34, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (33, 7, 'DECEDE', 26, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (34, 7, '19940406000000', 27, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (35, 7, '19900110130000', 35, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (36, 7, '19900110131000', 38, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (37, 7, 'HOPITAL ST LOUIS - ANAPATH', 36, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (38, 7, '-40', 37, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (39, 7, '10', 40, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (40, 7, 'mg', 41, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (41, 7, '0', 242, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (42, 7, '1', 29, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (43, 7, '2', 28, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (44, 7, '1', 39, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (45, 10, '1245380054BB', 2, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (46, 10, 'COBAIN', 3, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (47, 10, NULL, 4, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (48, 10, 'KURT', 5, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (49, 10, 'M', 6, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (50, 10, '19670220000000', 7, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (51, 10, 'USA', 9, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (52, 10, 'SEATTLE', 8, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (53, 10, 'D', 10, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (54, 10, '19940405000000', 12, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (55, 10, '20100805000000', 11, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (56, 11, 'Addiction Héroine', 17, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (57, 11, 'ADH BIS', 18, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (58, 11, '19860725000000', 20, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (59, 11, '19901213000000', 19, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (60, 12, 'X459GCT', 23, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (61, 12, 'SANG', 24, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (62, 12, 'TH112489200', 45, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (63, 12, 'NDA127896 BI', 44, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (64, 12, '19900110124500', 30, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (65, 12, 'PONCTION', 31, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (66, 12, '1', 47, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (67, 12, 'TUBE', 32, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (68, 12, 'SEC', 33, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (69, 12, '5', 34, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (70, 12, 'EN ATTENTE', 26, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (71, 12, '19940406000000', 27, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (72, 12, '19900110130000', 35, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (73, 12, '19900110131000', 38, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (74, 12, 'HOPITAL ST LOUIS - ANAPATH', 36, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (75, 12, '-40', 37, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (76, 12, '10', 40, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (77, 12, 'mg', 41, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (78, 12, '0', 242, NULL);

-- Continuing VALEUR_EXTERNE inserts
INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (79, 12, '1', 29, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (80, 12, '2', 28, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (81, 12, '1', 39, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (82, 12, 'Valeur', NULL, 2);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (83, 12, '1', NULL, 3);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (84, 13, 'GHLOJ7F4;GHOTJMF4', 230, NULL);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (85, 7, 'Alpha', NULL, 2);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (86, 7, '3: métastase', NULL, 31);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (87, 10, 'Patient Test', NULL, 1);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (88, 10, '3 : maladie intercurrente', NULL, 26);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (89, 12, '2: récidive', NULL, 31);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (90, 13, 'Bloc paraffine miroir', NULL, 40);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (91, 13, '55', NULL, 41);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (92, 13, '19900110130000', NULL, 5);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (93, 13, 'Nouveau texte de test', NULL, 9);

INSERT INTO VALEUR_EXTERNE (VALEUR_EXTERNE_ID, BLOC_EXTERNE_ID, VALEUR, CHAMP_ENTITE_ID, CHAMP_ANNOTATION_ID)
VALUES (94, 13, 'AC!AP;CC!CI;PP-PLACENTA', 229, NULL);

-- Insert data into RECEPTEUR
INSERT INTO RECEPTEUR (RECEPTEUR_ID, LOGICIEL_ID, IDENTIFICATION, OBSERVATIONS, ENVOI_NUM)
VALUES (1, 2, 'DIAMIC-ACK', 'URD DIAMIC INTERFACE', 1);

INSERT INTO RECEPTEUR (RECEPTEUR_ID, LOGICIEL_ID, IDENTIFICATION, OBSERVATIONS, ENVOI_NUM)
VALUES (2, 3, 'DME', 'HOPITAL MANAGER TIS LIQ', 1);

-- Insert data into SCAN_DEVICE
INSERT INTO SCAN_DEVICE (SCAN_DEVICE_ID, NAME, VERSION)
VALUES (1, 'VISIONMATE', 'V4');


INSERT INTO `BLOC_EXTERNE` VALUES (1,1,1,1),(2,1,2,2),(3,1,3,3),(4,1,3,4),(5,6,1,1),(6,6,2,2);


-- Note: SCAN_TERMINALE and SCAN_TUBE tables are empty in the source XML
-- Create empty tables if they don't exist
CREATE TABLE IF NOT EXISTS SCAN_TERMINALE (
    SCAN_TERMINALE_ID INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS SCAN_TUBE (
    SCAN_TUBE_ID INT PRIMARY KEY
);