-- CONTRAT
drop table BANQUE_CONTRAT;

alter table CONTRAT add column PLATEFORME_ID int(10) after CONTRAT_ID;
update CONTRAT set PLATEFORME_ID = 1;
alter table CONTRAT modify PLATEFORME_ID int(10) not null;

ALTER TABLE CONTRAT
  ADD CONSTRAINT FK_CONTRAT_PLATEFORME_ID
      FOREIGN KEY (PLATEFORME_ID)
      REFERENCES PLATEFORME (PLATEFORME_ID);

-- Ajout de l'id du printer Mbio 
alter table IMPRIMANTE add column MBIO_PRINTER int(10) default null after ORIENTATION;

-- coherence avec validation SPRING
alter table TABLE_ANNOTATION modify NOM VARCHAR(50) NOT NULL;

-- champ_id devient INT(10)
alter table CHAMP_LIGNE_ETIQUETTE modify CHAMP_ID int(10);
alter table COMBINAISON modify CHAMP1_ID int(10);
alter table COMBINAISON modify CHAMP2_ID int(10);
alter table CRITERE modify CHAMP_ID int(10);
alter table RESULTAT modify CHAMP_ID int(10);
alter table IMPORT_COLONNE modify CHAMP_ID int(10);
alter table CHAMP modify CHAMP_ID int(10);

ALTER TABLE IMPORT_COLONNE
  ADD CONSTRAINT FK_IMPORT_COLONNE_CHAMP_ID
      FOREIGN KEY (CHAMP_ID)
      REFERENCES CHAMP (CHAMP_ID);
      
-- BANQUE CATALOGUE
CREATE TABLE BANQUE_CATALOGUE (
	BANQUE_ID INT(10) NOT NULL
	, CATALOGUE_ID INT(3) NOT NULL
     , PRIMARY KEY (BANQUE_ID, CATALOGUE_ID)
) ENGINE = InnoDB;


ALTER TABLE BANQUE_CATALOGUE
  ADD CONSTRAINT FK_BANQUE_CATALOGUE_BANQUE_ID
      FOREIGN KEY (BANQUE_ID)
      REFERENCES BANQUE (BANQUE_ID);
      
ALTER TABLE BANQUE_CATALOGUE
  ADD CONSTRAINT FK_BANQUE_CATALOGUE_CATALOGUE_ID
      FOREIGN KEY (CATALOGUE_ID)
      REFERENCES CATALOGUE (CATALOGUE_ID);
