alter table CODE_ASSIGNE add column EXPORT BOOLEAN NOT NULL default false;

alter table ECHANTILLON drop foreign key FK_ECHANTILLON_CODE_LES_EXPORT_ID;
alter table ECHANTILLON drop foreign key FK_ECHANTILLON_CODE_ORGANE_EXPORT_ID;
alter table ECHANTILLON drop column CODE_ORGANE_EXPORT_ID;
alter table ECHANTILLON drop column CODE_LES_EXPORT_ID;

alter table VERSION add column VERSION_ID int(10) not null after VERSION;
alter table VERSION modify VERSION varchar(20) not null after VERSION_ID;
alter table VERSION add primary key (VERSION_ID);

-- db recherche anapath
alter table REQUETE add column BANQUE_ID INT(10) NOT NULL;
alter table AFFICHAGE add column BANQUE_ID INT(10) NOT NULL;

ALTER TABLE AFFICHAGE ADD CONSTRAINT FK_AFFICHAGE_BANQUE_ID FOREIGN KEY (BANQUE_ID) REFERENCES BANQUE (BANQUE_ID);
ALTER TABLE REQUETE ADD CONSTRAINT FK_REQUETE_BANQUE_ID FOREIGN KEY (BANQUE_ID) REFERENCES BANQUE (BANQUE_ID);

-- db recherche hemato
alter table REQUETE add column BANQUE_ID INT(10) NOT NULL;
update REQUETE set BANQUE_ID = 2 where REQUETE_ID=1;

alter table AFFICHAGE add column BANQUE_ID INT(10) NOT NULL;

ALTER TABLE AFFICHAGE ADD CONSTRAINT FK_AFFICHAGE_BANQUE_ID FOREIGN KEY (BANQUE_ID) REFERENCES BANQUE (BANQUE_ID);
ALTER TABLE REQUETE ADD CONSTRAINT FK_REQUETE_BANQUE_ID FOREIGN KEY (BANQUE_ID) REFERENCES BANQUE (BANQUE_ID);



