CREATE TABLE `CATEGORIE` (
  `CATEGORIE_ID` int(2) NOT NULL DEFAULT '0',
  `NOM` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`CATEGORIE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `COORDONNEE` (
  `COORDONNEE_ID` int(10) NOT NULL DEFAULT '0',
  `ADRESSE` varchar(250) DEFAULT NULL,
  `CP` varchar(10) DEFAULT NULL,
  `VILLE` varchar(100) DEFAULT NULL,
  `PAYS` varchar(100) DEFAULT NULL,
  `TEL` varchar(15) DEFAULT NULL,
  `FAX` varchar(15) DEFAULT NULL,
  `MAIL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`COORDONNEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETABLISSEMENT` (
  `ETABLISSEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `COORDONNEE_ID` int(10) DEFAULT NULL,
  `CATEGORIE_ID` int(2) DEFAULT NULL,
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `FINESS` varchar(20) DEFAULT NULL,
  `LOCAL` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ETABLISSEMENT_ID`),
  CONSTRAINT `FK_ETABLISSEMENT_CATEGORIE_ID` FOREIGN KEY (`CATEGORIE_ID`) REFERENCES `categorie` (`CATEGORIE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ETABLISSEMENT_COORDONNEE_ID` FOREIGN KEY (`COORDONNEE_ID`) REFERENCES `coordonnee` (`COORDONNEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SERVICE` (
  `SERVICE_ID` int(10) NOT NULL DEFAULT '0',
  `coordonnee_id` int(10) DEFAULT NULL,
  `ETABLISSEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`SERVICE_ID`),
  CONSTRAINT `FK_SERVICE_COORDONNEE_ID` FOREIGN KEY (`coordonnee_id`) REFERENCES `coordonnee` (`COORDONNEE_ID`),
  CONSTRAINT `FK_SERVICE_ETABLISSEMENT_ID` FOREIGN KEY (`ETABLISSEMENT_ID`) REFERENCES `etablissement` (`ETABLISSEMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SPECIALITE` (
  `SPECIALITE_ID` int(3) NOT NULL DEFAULT '0',
  `NOM` varchar(200) NOT NULL,
  PRIMARY KEY (`SPECIALITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TITRE` (
  `TITRE_ID` int(2) NOT NULL DEFAULT '0',
  `TITRE` varchar(5) NOT NULL DEFAULT '',
  PRIMARY KEY (`TITRE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `COLLABORATEUR` (
  `COLLABORATEUR_ID` int(10) NOT NULL DEFAULT '0',
  `ETABLISSEMENT_ID` int(10) DEFAULT NULL,
  `SPECIALITE_ID` int(3) DEFAULT NULL,
  `NOM` varchar(30) NOT NULL DEFAULT '',
  `PRENOM` varchar(30) DEFAULT NULL,
  `INITIALES` varchar(4) DEFAULT NULL,
  `TITRE_ID` int(2) DEFAULT NULL,
  `ARCHIVE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_COLLABORATEUR_ETABLISSEMENT_ID` FOREIGN KEY (`ETABLISSEMENT_ID`) REFERENCES `etablissement` (`ETABLISSEMENT_ID`),
  CONSTRAINT `FK_COLLABORATEUR_SPECIALITE_ID` FOREIGN KEY (`SPECIALITE_ID`) REFERENCES `specialite` (`SPECIALITE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_COLLABORATEUR_TITRE_ID` FOREIGN KEY (`TITRE_ID`) REFERENCES `titre` (`TITRE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PLATEFORME` (
  `PLATEFORME_ID` int(10) NOT NULL DEFAULT '0',
  `NOM` varchar(50) NOT NULL DEFAULT '',
  `ALIAS` varchar(5) DEFAULT NULL,
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`PLATEFORME_ID`),
  CONSTRAINT `FK_PLATEFORME_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PROFIL` (
  `PROFIL_ID` int(10) NOT NULL DEFAULT '0',
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `ANONYME` tinyint(1) DEFAULT '0',
  `ADMIN` tinyint(1) NOT NULL DEFAULT '0',
  `ACCES_ADMINISTRATION` tinyint(1) NOT NULL DEFAULT '0',
  `PROFIL_EXPORT` int(11) DEFAULT '0',
  `ARCHIVE` tinyint(1) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`PROFIL_ID`),
  CONSTRAINT `FK_PROFIL_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `UTILISATEUR` (
  `UTILISATEUR_ID` int(10) NOT NULL DEFAULT '0',
  `LOGIN` varchar(100) NOT NULL DEFAULT '',
  `PASSWORD` varchar(100) NOT NULL DEFAULT '',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `ENCODED_PASSWORD` varchar(100) DEFAULT NULL,
  `DN_LDAP` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `TIMEOUT` date DEFAULT NULL,
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  `SUPER` tinyint(1) NOT NULL DEFAULT '0',
  `PLATEFORME_ORIG_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`UTILISATEUR_ID`),
  CONSTRAINT `FK_UTILISATEUR_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_UTIL_PF_ORIG_ID` FOREIGN KEY (`PLATEFORME_ORIG_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PLATEFORME_ADMINISTRATEUR` (
  `PLATEFORME_ID` int(10) NOT NULL DEFAULT '0',
  `UTILISATEUR_ID` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`PLATEFORME_ID`,`UTILISATEUR_ID`),
  CONSTRAINT `FK_PLATEFORME_ADMINISTRATEUR_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`),
  CONSTRAINT `FK_PLATEFORME_ADMINISTRATEUR_UTILISATEUR_ID` FOREIGN KEY (`UTILISATEUR_ID`) REFERENCES `utilisateur` (`UTILISATEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONTEXTE` (
  `CONTEXTE_ID` int(10) NOT NULL,
  `NOM` char(25) NOT NULL DEFAULT '',
  `LIBELLE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CONTEXTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `COULEUR` (
  `COULEUR_ID` int(10) NOT NULL DEFAULT '0',
  `COULEUR` varchar(25) NOT NULL,
  `HEXA` varchar(10) NOT NULL,
  `ORDRE_VISOTUBE` int(3) DEFAULT NULL,
  PRIMARY KEY (`COULEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `BANQUE` (
  `BANQUE_ID` int(10) NOT NULL DEFAULT '0',
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  `CONTACT_ID` int(10) DEFAULT NULL,
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `IDENTIFICATION` varchar(50) DEFAULT NULL,
  `DESCRIPTION` text,
  `PROPRIETAIRE_ID` int(10) DEFAULT NULL,
  `AUTORISE_CROSS_PATIENT` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `CONTEXTE_ID` int(2) DEFAULT NULL,
  `PLATEFORME_ID` int(10) NOT NULL DEFAULT '0',
  `DEFMALADIES` tinyint(1) NOT NULL DEFAULT '1',
  `DEFAUT_MALADIE` varchar(250) DEFAULT NULL,
  `DEFAUT_MALADIE_CODE` varchar(50) DEFAULT NULL,
  `ECHANTILLON_COULEUR_ID` int(10) DEFAULT NULL,
  `PROD_DERIVE_COULEUR_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`BANQUE_ID`),
  CONSTRAINT `FK_BANQUE_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_BANQUE_CONTACT_ID` FOREIGN KEY (`CONTACT_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_BANQUE_CONTEXTE_ID` FOREIGN KEY (`CONTEXTE_ID`) REFERENCES `contexte` (`CONTEXTE_ID`),
  CONSTRAINT `FK_BANQUE_ECHANTILLON_COULEUR_ID` FOREIGN KEY (`ECHANTILLON_COULEUR_ID`) REFERENCES `couleur` (`COULEUR_ID`),
  CONSTRAINT `FK_BANQUE_PLATERORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`),
  CONSTRAINT `FK_BANQUE_PROD_DERIVE_COULEUR_ID` FOREIGN KEY (`PROD_DERIVE_COULEUR_ID`) REFERENCES `couleur` (`COULEUR_ID`),
  CONSTRAINT `FK_BANQUE_PROPRIETAIRE_ID` FOREIGN KEY (`PROPRIETAIRE_ID`) REFERENCES `service` (`SERVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DATA_TYPE` (
  `DATA_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `TYPE` char(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`DATA_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ENTITE` (
  `ENTITE_ID` int(2) NOT NULL DEFAULT '0',
  `NOM` varchar(25) DEFAULT NULL,
  `MASC` tinyint(1) NOT NULL DEFAULT '0',
  `ANNOTABLE` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ENTITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CHAMP_ENTITE` (
  `CHAMP_ENTITE_ID` int(10) NOT NULL,
  `NOM` varchar(50) NOT NULL DEFAULT '',
  `DATA_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `IS_NULL` tinyint(1) NOT NULL DEFAULT '0',
  `IS_UNIQUE` tinyint(1) NOT NULL DEFAULT '0',
  `VALEUR_DEFAUT` varchar(50) DEFAULT NULL,
  `ENTITE_ID` int(2) NOT NULL DEFAULT '0',
  `CAN_IMPORT` tinyint(1) NOT NULL DEFAULT '0',
  `QUERY_CHAMP_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`CHAMP_ENTITE_ID`),
  CONSTRAINT `FK_CHAMP_ENTITE_CHAMP_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `entite` (`ENTITE_ID`),
  CONSTRAINT `FK_CHAMP_ENTITE_DATA_TYPE_ID` FOREIGN KEY (`DATA_TYPE_ID`) REFERENCES `data_type` (`DATA_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `subdivision` (
  `SUBDIVISION_ID` int(2) NOT NULL DEFAULT '0',
  `NOM` varchar(100) DEFAULT NULL,
  `CHAMP_ENTITE_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`SUBDIVISION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CATALOGUE` (
  `CATALOGUE_ID` int(10) NOT NULL,
  `NOM` char(25) NOT NULL,
  `DESCRIPTION` char(250) DEFAULT NULL,
  `ICONE` char(100) NOT NULL,
  PRIMARY KEY (`CATALOGUE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `BANQUE_CATALOGUE` (
  `BANQUE_ID` int(10) NOT NULL,
  `CATALOGUE_ID` int(3) NOT NULL,
  PRIMARY KEY (`BANQUE_ID`,`CATALOGUE_ID`),
  CONSTRAINT `FK_BANQUE_CATALOGUE_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `banque` (`BANQUE_ID`),
  CONSTRAINT `FK_BANQUE_CATALOGUE_CATALOGUE_ID` FOREIGN KEY (`CATALOGUE_ID`) REFERENCES `catalogue` (`CATALOGUE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TABLE_ANNOTATION` (
  `TABLE_ANNOTATION_ID` int(10) NOT NULL,
  `NOM` varchar(100) DEFAULT NULL,
  `DESCRIPTION` text,
  `ENTITE_ID` int(10) NOT NULL DEFAULT '1',
  `CATALOGUE_ID` int(3) DEFAULT NULL,
  `PLATEFORME_ID` int(10) DEFAULT NULL,
  `INLINE_DISPLAY` bit(1) DEFAULT '0',
  PRIMARY KEY (`TABLE_ANNOTATION_ID`),
  CONSTRAINT `FK_TABLE_ANNOTATION_CATALOGUE` FOREIGN KEY (`CATALOGUE_ID`) REFERENCES `catalogue` (`CATALOGUE_ID`),
  CONSTRAINT `FK_TABLE_ANNOTATION_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `entite` (`ENTITE_ID`),
  CONSTRAINT `FK_TABLE_ANNOTATION_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CHAMP_ANNOTATION` (
  `CHAMP_ANNOTATION_ID` int(10) NOT NULL,
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `DATA_TYPE_ID` int(10) NOT NULL DEFAULT '0',
  `TABLE_ANNOTATION_ID` int(10) NOT NULL DEFAULT '0',
  `COMBINE` tinyint(1) DEFAULT '0',
  `ORDRE` int(3) NOT NULL DEFAULT '0',
  `EDIT` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_CHAMP_ANNOTATION_DATA_TYPE_ID` FOREIGN KEY (`DATA_TYPE_ID`) REFERENCES `data_type` (`DATA_TYPE_ID`),
  CONSTRAINT `FK_CHAMP_ANNOTATION_TABLE_ANNOTATION_ID` FOREIGN KEY (`TABLE_ANNOTATION_ID`) REFERENCES `table_annotation` (`TABLE_ANNOTATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `FICHIER` (
  `FICHIER_ID` int(10) NOT NULL DEFAULT '0',
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `PATH` varchar(100) NOT NULL DEFAULT '',
  `MIMETYPE` varchar(100) NOT NULL,
  PRIMARY KEY (`FICHIER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ITEM` (
  `ITEM_ID` int(10) NOT NULL,
  `LABEL` varchar(100) NOT NULL DEFAULT '',
  `VALEUR` varchar(100) DEFAULT NULL,
  `CHAMP_ANNOTATION_ID` int(10) NOT NULL DEFAULT '0',
  `PLATEFORME_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`ITEM_ID`),
  CONSTRAINT `FK_ITEM_CHAMP_ANNOTATION_ID` FOREIGN KEY (`CHAMP_ANNOTATION_ID`) REFERENCES `champ_annotation` (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_ITEM_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ANNOTATION_VALEUR` (
  `ANNOTATION_VALEUR_ID` int(10) NOT NULL AUTO_INCREMENT,
  `CHAMP_ANNOTATION_ID` int(10) NOT NULL DEFAULT '0',
  `OBJET_ID` int(10) NOT NULL DEFAULT '0',
  `ALPHANUM` varchar(100) DEFAULT NULL,
  `TEXTE` text,
  `ANNO_DATE` datetime DEFAULT NULL,
  `BOOL` tinyint(1) DEFAULT NULL,
  `ITEM_ID` int(10) DEFAULT NULL,
  `FICHIER_ID` int(10) DEFAULT NULL,
  `BANQUE_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`ANNOTATION_VALEUR_ID`),
  UNIQUE KEY `FICHIER_ID` (`FICHIER_ID`),
  CONSTRAINT `FK_ANNOTATION_VALEUR_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `banque` (`BANQUE_ID`),
  CONSTRAINT `FK_ANNOTATION_VALEUR_CHAMP_ANNOTATION_ID` FOREIGN KEY (`CHAMP_ANNOTATION_ID`) REFERENCES `champ_annotation` (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_ANNOTATION_VALEUR_FICHIER_ID` FOREIGN KEY (`FICHIER_ID`) REFERENCES `fichier` (`FICHIER_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ANNOTATION_VALEUR_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `item` (`ITEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8;

CREATE TABLE `CHAMP` (
  `CHAMP_ID` int(10) NOT NULL,
  `CHAMP_ANNOTATION_ID` int(10) DEFAULT NULL,
  `CHAMP_ENTITE_ID` int(10) DEFAULT NULL,
  `CHAMP_PARENT_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`CHAMP_ID`),
  CONSTRAINT `FK_CHAMP_CHAMP_ANNOTATION_ID` FOREIGN KEY (`CHAMP_ANNOTATION_ID`) REFERENCES `champ_annotation` (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_CHAMP_CHAMP_ENTITE_ID` FOREIGN KEY (`CHAMP_ENTITE_ID`) REFERENCES `champ_entite` (`CHAMP_ENTITE_ID`),
  CONSTRAINT `FK_CHAMP_CHAMP_PARENT_ID` FOREIGN KEY (`CHAMP_PARENT_ID`) REFERENCES `champ` (`CHAMP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CHAMP_CALCULE` (
  `CHAMP_CALCULE_ID` int(10) NOT NULL,
  `CHAMP_ANNOTATION_ID` int(11) DEFAULT NULL,
  `CHAMP1_ID` int(11) DEFAULT NULL,
  `OPERATEUR` varchar(10) DEFAULT NULL,
  `CHAMP2_ID` int(11) DEFAULT NULL,
  `VALEUR` varchar(100) DEFAULT NULL,
  `DATA_TYPE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`CHAMP_CALCULE_ID`),
  CONSTRAINT `FK_CHAMP1_ID` FOREIGN KEY (`CHAMP1_ID`) REFERENCES `champ` (`CHAMP_ID`),
  CONSTRAINT `FK_CHAMP2_ID` FOREIGN KEY (`CHAMP2_ID`) REFERENCES `champ` (`CHAMP_ID`),
  CONSTRAINT `FK_CHAMP_ANNOTATION_ID` FOREIGN KEY (`CHAMP_ANNOTATION_ID`) REFERENCES `champ_annotation` (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_DATA_TYPE_ID` FOREIGN KEY (`DATA_TYPE_ID`) REFERENCES `data_type` (`DATA_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `NIVEAU_VALIDATION` (
  `NIVEAU_VALIDATION_ID` int(11) NOT NULL,
  `LIBELLE` varchar(200) DEFAULT NULL,
  `COULEUR` varchar(45) DEFAULT NULL,
  `CLE_MESSAGE` varchar(200) DEFAULT NULL,
  `CRITICITE` int(11) NOT NULL,
  PRIMARY KEY (`NIVEAU_VALIDATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CRITERE_VALIDATION` (
  `CRITERE_VALIDATION_ID` int(10) NOT NULL,
  `CHAMP_ID` int(11) NOT NULL,
  `OPERATEUR` varchar(45) NOT NULL,
  `VALEUR_REF` varchar(200) DEFAULT NULL,
  `CHAMP_REF_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`CRITERE_VALIDATION_ID`),
  CONSTRAINT `FK_CRITERE_VALIDATION_CHAMP_ID` FOREIGN KEY (`CHAMP_ID`) REFERENCES `champ` (`CHAMP_ID`),
  CONSTRAINT `FK_CRITERE_VALIDATION_CHAMP_REF_ID` FOREIGN KEY (`CHAMP_REF_ID`) REFERENCES `champ` (`CHAMP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `VALIDATION` (
  `VALIDATION_ID` int(10) NOT NULL,
  `LIBELLE` varchar(200) DEFAULT NULL,
  `OPERATEUR` varchar(4) DEFAULT NULL,
  `NIVEAU_VALIDATION_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`VALIDATION_ID`),
  CONSTRAINT `FK_VALIDATION_NIVEAU_VALIDATION_ID` FOREIGN KEY (`NIVEAU_VALIDATION_ID`) REFERENCES `niveau_validation` (`NIVEAU_VALIDATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SOUS_VALIDATION` (
  `VALIDATION_ID` int(11) NOT NULL,
  `SOUS_VALIDATION_ID` int(11) NOT NULL,
  CONSTRAINT `FK_SOUS_VALIDATION_SOUS_VALIDATION_ID` FOREIGN KEY (`SOUS_VALIDATION_ID`) REFERENCES `validation` (`VALIDATION_ID`),
  CONSTRAINT `FK_SOUS_VALIDATION_VALIDATION_ID` FOREIGN KEY (`VALIDATION_ID`) REFERENCES `validation` (`VALIDATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `VALIDATION_CRITERE_VALIDATION` (
  `VALIDATION_ID` int(11) NOT NULL,
  `CRITERE_VALIDATION_ID` int(11) NOT NULL,
  CONSTRAINT `FK_VALIDATION_CRITERE_VALIDATION_CRITERE_VALIDATION_ID` FOREIGN KEY (`CRITERE_VALIDATION_ID`) REFERENCES `critere_validation` (`CRITERE_VALIDATION_ID`),
  CONSTRAINT `FK_VALIDATION_CRITERE_VALIDATION_VALIDATION_ID` FOREIGN KEY (`VALIDATION_ID`) REFERENCES `validation` (`VALIDATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ACTION` (
  `ACTION_ID` int(10) NOT NULL,
  `ENTITE_ID` int(11) NOT NULL,
  `TYPE_ACTION` varchar(45) NOT NULL,
  `LIBELLE` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ACTION_ID`),
  UNIQUE KEY `ENTITE_ID` (`ENTITE_ID`,`TYPE_ACTION`),
  CONSTRAINT `FK_ACTION_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `entite` (`ENTITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ACTION_VALIDATION` (
  `ACTION_ID` int(11) NOT NULL,
  `VALIDATION_ID` int(11) NOT NULL,
  CONSTRAINT `ACTION_VALIDATION_ACTION_ID` FOREIGN KEY (`ACTION_ID`) REFERENCES `action` (`ACTION_ID`),
  CONSTRAINT `ACTION_VALIDATION_VALIDATION_ID` FOREIGN KEY (`VALIDATION_ID`) REFERENCES `validation` (`VALIDATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DETAIL_VALIDATION` (
  `DETAIL_VALIDATION_ID` int(11) NOT NULL,
  `UTILISATEUR_ID` int(11) NOT NULL,
  `NIVEAU_VALIDATION_ID` int(11) NOT NULL,
  `DATE_VALIDATION` datetime NOT NULL,
  `COMMENTAIRE_VALIDATION` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`DETAIL_VALIDATION_ID`),
  CONSTRAINT `FK_DETAIL_VALIDATION_NIVEAU_VALIDATION_ID` FOREIGN KEY (`NIVEAU_VALIDATION_ID`) REFERENCES `niveau_validation` (`NIVEAU_VALIDATION_ID`),
  CONSTRAINT `FK_DETAIL_VALIDATION_UTILISATEUR_ID` FOREIGN KEY (`UTILISATEUR_ID`) REFERENCES `utilisateur` (`UTILISATEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PATIENT` (
  `PATIENT_ID` int(10) NOT NULL DEFAULT '0',
  `NIP` varchar(20) DEFAULT NULL,
  `NOM` varchar(50) NOT NULL DEFAULT '',
  `NOM_NAISSANCE` varchar(50) DEFAULT NULL,
  `PRENOM` varchar(50) DEFAULT NULL,
  `SEXE` char(3) DEFAULT NULL,
  `DATE_NAISSANCE` date DEFAULT NULL,
  `VILLE_NAISSANCE` varchar(100) DEFAULT NULL,
  `PAYS_NAISSANCE` varchar(100) DEFAULT NULL,
  `PATIENT_ETAT` varchar(10) NOT NULL DEFAULT 'inconnu',
  `DATE_ETAT` date DEFAULT NULL,
  `DATE_DECES` date DEFAULT NULL,
  `ETAT_INCOMPLET` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`PATIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PATIENT_DELEGATE` (
  `PATIENT_DELEGATE_ID` int(11) NOT NULL,
  `PATIENT_ID` int(11) NOT NULL,
  PRIMARY KEY (`PATIENT_DELEGATE_ID`),
  UNIQUE KEY `PATIENT_ID` (`PATIENT_ID`),
  CONSTRAINT `FK_PATIENT_DELEGATE_PATIENT_ID` FOREIGN KEY (`PATIENT_ID`) REFERENCES `patient` (`PATIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PATIENT_BTO` (
  `PATIENT_DELEGATE_ID` int(11) NOT NULL,
  `DETAIL_VALIDATION_ID` int(11) DEFAULT NULL,
  `GROUPE_SANGUIN` varchar(3) DEFAULT NULL,
  UNIQUE KEY `PATIENT_DELEGATE_ID` (`PATIENT_DELEGATE_ID`),
  CONSTRAINT `FK_PATIENT_BTO_DETAIL_VALIDATION_ID` FOREIGN KEY (`DETAIL_VALIDATION_ID`) REFERENCES `detail_validation` (`DETAIL_VALIDATION_ID`),
  CONSTRAINT `FK_PATIENT_BTO_PATIENT_DELEGATE_ID` FOREIGN KEY (`PATIENT_DELEGATE_ID`) REFERENCES `patient_delegate` (`PATIENT_DELEGATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONDIT_MILIEU` (
  `CONDIT_MILIEU_ID` int(10) NOT NULL DEFAULT '0',
  `MILIEU` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`CONDIT_MILIEU_ID`),
  CONSTRAINT `FK_CONDIT_MILIEU_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONDIT_TYPE` (
  `CONDIT_TYPE_ID` int(10) NOT NULL DEFAULT '0',
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`CONDIT_TYPE_ID`),
  CONSTRAINT `FK_CONDIT_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONSENT_TYPE` (
  `CONSENT_TYPE_ID` int(10) NOT NULL,
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`CONSENT_TYPE_ID`),
  CONSTRAINT `FK_CONSENT_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MALADIE` (
  `MALADIE_ID` int(10) NOT NULL DEFAULT '0',
  `PATIENT_ID` int(10) NOT NULL DEFAULT '0',
  `LIBELLE` varchar(300) NOT NULL DEFAULT 'Inconnu',
  `CODE` varchar(50) DEFAULT NULL,
  `DATE_DIAGNOSTIC` date DEFAULT NULL,
  `DATE_DEBUT` date DEFAULT NULL,
  `SYSTEME_DEFAUT` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`MALADIE_ID`),
  CONSTRAINT `FK_MALADIE_PATIENT_ID` FOREIGN KEY (`PATIENT_ID`) REFERENCES `patient` (`PATIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `maladie_delegate` (
  `MALADIE_DELEGATE_ID` int(10) NOT NULL,
  `MALADIE_ID` int(10) NOT NULL,
  `CONTEXTE_ID` int(2) NOT NULL,
  PRIMARY KEY (`MALADIE_DELEGATE_ID`),
  UNIQUE KEY `MALADIE_ID` (`MALADIE_ID`),
  CONSTRAINT `FK_MALADIE_DEL_CONTEXTE_ID` FOREIGN KEY (`CONTEXTE_ID`) REFERENCES `contexte` (`CONTEXTE_ID`),
  CONSTRAINT `FK_MALADIE_DEL_MALADIE_ID` FOREIGN KEY (`MALADIE_ID`) REFERENCES `maladie` (`MALADIE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MALADIE_SERO` (
  `MALADIE_DELEGATE_ID` int(10) NOT NULL,
  `DIAGNOSTIC` char(1) NOT NULL,
  PRIMARY KEY (`MALADIE_DELEGATE_ID`),
  CONSTRAINT `FK_MAL_SERO_MAL_DEL_ID` FOREIGN KEY (`MALADIE_DELEGATE_ID`) REFERENCES `maladie_delegate` (`MALADIE_DELEGATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `NATURE` (
  `NATURE_ID` int(10) NOT NULL,
  `NATURE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`NATURE_ID`),
  CONSTRAINT `FK_NATURE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRELEVEMENT_TYPE` (
  `PRELEVEMENT_TYPE_ID` int(10) NOT NULL DEFAULT '0',
  `INCA_CAT` char(2) DEFAULT NULL,
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`PRELEVEMENT_TYPE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `UNITE` (
  `UNITE_ID` int(2) NOT NULL DEFAULT '0',
  `UNITE` varchar(30) NOT NULL DEFAULT '',
  `TYPE` varchar(15) NOT NULL DEFAULT 'masse',
  PRIMARY KEY (`UNITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TRANSPORTEUR` (
  `TRANSPORTEUR_ID` int(10) NOT NULL DEFAULT '0',
  `coordonnee_id` int(10) DEFAULT NULL,
  `NOM` varchar(50) NOT NULL DEFAULT '',
  `CONTACT_NOM` varchar(50) DEFAULT NULL,
  `CONTACT_PRENOM` varchar(50) DEFAULT NULL,
  `CONTACT_TEL` varchar(15) DEFAULT NULL,
  `CONTACT_FAX` varchar(15) DEFAULT NULL,
  `CONTACT_MAIL` varchar(100) DEFAULT NULL,
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`TRANSPORTEUR_ID`),
  CONSTRAINT `FK_TRANSPORTEUR_COORDONNEE_ID` FOREIGN KEY (`coordonnee_id`) REFERENCES `coordonnee` (`COORDONNEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRELEVEMENT` (
  `PRELEVEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `BANQUE_ID` int(10) NOT NULL DEFAULT '0',
  `CODE` varchar(50) NOT NULL DEFAULT '',
  `NATURE_ID` int(10) NOT NULL DEFAULT '0',
  `MALADIE_ID` int(10) DEFAULT NULL,
  `CONSENT_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `CONSENT_DATE` date DEFAULT NULL,
  `PRELEVEUR_ID` int(10) DEFAULT NULL,
  `SERVICE_PRELEVEUR_ID` int(10) DEFAULT NULL,
  `DATE_PRELEVEMENT` datetime DEFAULT NULL,
  `PRELEVEMENT_TYPE_ID` int(10) DEFAULT NULL,
  `CONDIT_TYPE_ID` int(10) DEFAULT NULL,
  `CONDIT_MILIEU_ID` int(3) DEFAULT NULL,
  `CONDIT_NBR` int(10) DEFAULT NULL,
  `DATE_DEPART` datetime DEFAULT NULL,
  `TRANSPORTEUR_ID` int(10) DEFAULT NULL,
  `TRANSPORT_TEMP` float DEFAULT NULL,
  `DATE_ARRIVEE` datetime DEFAULT NULL,
  `OPERATEUR_ID` int(10) DEFAULT NULL,
  `QUANTITE` decimal(12,3) DEFAULT NULL,
  `QUANTITE_UNITE_ID` int(10) DEFAULT NULL,
  `PATIENT_NDA` varchar(20) DEFAULT NULL,
  `NUMERO_LABO` varchar(50) DEFAULT NULL,
  `STERILE` tinyint(1) DEFAULT NULL,
  `CONG_ARRIVEE` tinyint(1) DEFAULT '1',
  `CONG_DEPART` tinyint(1) DEFAULT NULL,
  `CONFORME_ARRIVEE` tinyint(1) DEFAULT NULL,
  `ETAT_INCOMPLET` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `DATE_PEREMPTION` datetime DEFAULT NULL,
  `DATE_VALIDATION` datetime DEFAULT NULL,
  `NIVEAU_VALIDATION_ID` int(11) DEFAULT NULL,
  `COMMENTAIRE_VALIDATION` varchar(250) DEFAULT NULL,
  `VALIDEUR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_PRELEVEMENT_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `banque` (`BANQUE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_CONDIT_MILIEU_ID` FOREIGN KEY (`CONDIT_MILIEU_ID`) REFERENCES `condit_milieu` (`CONDIT_MILIEU_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_PRELEVEMENT_CONDIT_TYPE_ID` FOREIGN KEY (`CONDIT_TYPE_ID`) REFERENCES `condit_type` (`CONDIT_TYPE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_PRELEVEMENT_CONSENT_TYPE_ID` FOREIGN KEY (`CONSENT_TYPE_ID`) REFERENCES `consent_type` (`CONSENT_TYPE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_MALADIE_ID` FOREIGN KEY (`MALADIE_ID`) REFERENCES `maladie` (`MALADIE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_NATURE_ID` FOREIGN KEY (`NATURE_ID`) REFERENCES `nature` (`NATURE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_OPERATEUR_ID` FOREIGN KEY (`OPERATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_PRELEVEMENT_PRELEVEMENT_TYPE_ID` FOREIGN KEY (`PRELEVEMENT_TYPE_ID`) REFERENCES `prelevement_type` (`PRELEVEMENT_TYPE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_PRELEVEMENT_PRELEVEUR_ID` FOREIGN KEY (`PRELEVEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_PRELEVEMENT_QUANTITE_UNITE_ID` FOREIGN KEY (`QUANTITE_UNITE_ID`) REFERENCES `unite` (`UNITE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_SERVICE_PRELEVEUR_ID` FOREIGN KEY (`SERVICE_PRELEVEUR_ID`) REFERENCES `service` (`SERVICE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_TRANSPORTEUR_ID` FOREIGN KEY (`TRANSPORTEUR_ID`) REFERENCES `transporteur` (`TRANSPORTEUR_ID`),
  CONSTRAINT `FK_PRELEVEMENT_VALIDEUR_ID` FOREIGN KEY (`VALIDEUR_ID`) REFERENCES `utilisateur` (`UTILISATEUR_ID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LABO_INTER` (
  `LABO_INTER_ID` int(10) NOT NULL DEFAULT '0',
  `PRELEVEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `ORDRE` int(2) NOT NULL DEFAULT '1',
  `SERVICE_ID` int(10) DEFAULT NULL,
  `DATE_ARRIVEE` datetime DEFAULT NULL,
  `CONSERV_TEMP` float DEFAULT NULL,
  `STERILE` tinyint(1) DEFAULT NULL,
  `CONGELATION` tinyint(1) DEFAULT NULL,
  `TRANSPORT_TEMP` float DEFAULT NULL,
  `DATE_DEPART` datetime DEFAULT NULL,
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  `TRANSPORTEUR_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`LABO_INTER_ID`),
  CONSTRAINT `FK_LABO_INTER_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_LABO_INTER_PRELEVEMENT_ID` FOREIGN KEY (`PRELEVEMENT_ID`) REFERENCES `prelevement` (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_LABO_INTER_SERVICE_ID` FOREIGN KEY (`SERVICE_ID`) REFERENCES `service` (`SERVICE_ID`),
  CONSTRAINT `FK_LABO_INTER_TRANSPORTEUR_ID` FOREIGN KEY (`TRANSPORTEUR_ID`) REFERENCES `transporteur` (`TRANSPORTEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRELEVEMENT_DELEGATE` (
  `PRELEVEMENT_DELEGATE_ID` int(10) NOT NULL,
  `PRELEVEMENT_ID` int(10) NOT NULL,
  PRIMARY KEY (`PRELEVEMENT_DELEGATE_ID`),
  UNIQUE KEY `PRELEVEMENT_ID` (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_PREL_DEL_PRELEVEMENT_ID` FOREIGN KEY (`PRELEVEMENT_ID`) REFERENCES `prelevement` (`PRELEVEMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRELEVEMENT_BTO` (
  `PRELEVEMENT_DELEGATE_ID` int(11) NOT NULL,
  `DETAIL_VALIDATION_ID` int(11) DEFAULT NULL,
  UNIQUE KEY `PRELEVEMENT_DELEGATE_ID` (`PRELEVEMENT_DELEGATE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_BTO_DETAIL_VALIDATION_ID` FOREIGN KEY (`DETAIL_VALIDATION_ID`) REFERENCES `detail_validation` (`DETAIL_VALIDATION_ID`),
  CONSTRAINT `FK_PRELEVEMENT_BTO_PRELEVEMENT_DELEGATE_ID` FOREIGN KEY (`PRELEVEMENT_DELEGATE_ID`) REFERENCES `prelevement_delegate` (`PRELEVEMENT_DELEGATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRELEVEMENT_SERO` (
  `PRELEVEMENT_DELEGATE_ID` int(10) NOT NULL,
  `LIBELLE` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`PRELEVEMENT_DELEGATE_ID`),
  CONSTRAINT `FK_PREL_SERO_PREL_DEL_ID` FOREIGN KEY (`PRELEVEMENT_DELEGATE_ID`) REFERENCES `prelevement_delegate` (`PRELEVEMENT_DELEGATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PROTOCOLE` (
  `PROTOCOLE_ID` int(3) NOT NULL,
  `NOM` varchar(200) NOT NULL,
  `DESCRIPTION` text,
  `PLATEFORME_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`PROTOCOLE_ID`),
  CONSTRAINT `FK_PROTOCOLE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRELEVEMENT_SERO_PROTOCOLE` (
  `PRELEVEMENT_DELEGATE_ID` int(10) NOT NULL,
  `PROTOCOLE_ID` int(10) NOT NULL,
  PRIMARY KEY (`PRELEVEMENT_DELEGATE_ID`,`PROTOCOLE_ID`),
  CONSTRAINT `FK_PREL_PROTO_PREL_ID` FOREIGN KEY (`PRELEVEMENT_DELEGATE_ID`) REFERENCES `prelevement_sero` (`PRELEVEMENT_DELEGATE_ID`),
  CONSTRAINT `FK_PREL_PROTO_PROTO_ID` FOREIGN KEY (`PROTOCOLE_ID`) REFERENCES `protocole` (`PROTOCOLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRELEVEMENT_XENO` (
  `PRELEVEMENT_DELEGATE_ID` int(10) NOT NULL,
  `SOURIS` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`PRELEVEMENT_DELEGATE_ID`),
  CONSTRAINT `FK_PREL_XENO_PREL_DEL_ID` FOREIGN KEY (`PRELEVEMENT_DELEGATE_ID`) REFERENCES `prelevement_delegate` (`PRELEVEMENT_DELEGATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
