--DROP TABLE IF EXISTS `CATEGORIE`;
CREATE TABLE `CATEGORIE` (
  `CATEGORIE_ID` int(2) NOT NULL DEFAULT '0',
  `NOM` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`CATEGORIE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `COORDONNEE`;
CREATE TABLE `COORDONNEE` (
  `COORDONNEE_ID` int(10) NOT NULL DEFAULT '0',
  `ADRESSE` varchar(250) DEFAULT NULL,
  `CP` varchar(10) DEFAULT NULL,
  `VILLE` varchar(100) DEFAULT NULL,
  `PAYS` varchar(100) DEFAULT NULL,
  `TEL` varchar(15) DEFAULT NULL,
  `FAX` varchar(15) DEFAULT NULL,
  `MAIL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`COORDONNEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `ETABLISSEMENT`;
CREATE TABLE `ETABLISSEMENT` (
  `ETABLISSEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `COORDONNEE_ID` int(10) DEFAULT NULL,
  `CATEGORIE_ID` int(2) DEFAULT NULL,
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `FINESS` varchar(20) DEFAULT NULL,
  `LOCAL` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ETABLISSEMENT_ID`),
  CONSTRAINT `FK_ETABLISSEMENT_CATEGORIE_ID` FOREIGN KEY (`CATEGORIE_ID`) REFERENCES `CATEGORIE` (`CATEGORIE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ETABLISSEMENT_COORDONNEE_ID` FOREIGN KEY (`COORDONNEE_ID`) REFERENCES `COORDONNEE` (`COORDONNEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `SERVICE`;
CREATE TABLE `SERVICE` (
  `SERVICE_ID` int(10) NOT NULL DEFAULT '0',
  `coordonnee_id` int(10) DEFAULT NULL,
  `ETABLISSEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`SERVICE_ID`),
  CONSTRAINT `FK_SERVICE_COORDONNEE_ID` FOREIGN KEY (`coordonnee_id`) REFERENCES `coordonnee` (`COORDONNEE_ID`),
  CONSTRAINT `FK_SERVICE_ETABLISSEMENT_ID` FOREIGN KEY (`ETABLISSEMENT_ID`) REFERENCES `etablissement` (`ETABLISSEMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `SPECIALITE`;
CREATE TABLE `SPECIALITE` (
  `SPECIALITE_ID` int(3) NOT NULL DEFAULT '0',
  `NOM` varchar(200) NOT NULL,
  PRIMARY KEY (`SPECIALITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `TITRE`;
CREATE TABLE `TITRE` (
  `TITRE_ID` int(2) NOT NULL DEFAULT '0',
  `TITRE` varchar(5) NOT NULL DEFAULT '',
  PRIMARY KEY (`TITRE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `COLLABORATEUR`;
CREATE TABLE `COLLABORATEUR` (
  `COLLABORATEUR_ID` int(10) NOT NULL DEFAULT '0',
  `ETABLISSEMENT_ID` int(10) DEFAULT NULL,
  `SPECIALITE_ID` int(3) DEFAULT NULL,
  `NOM` varchar(30) NOT NULL DEFAULT '',
  `PRENOM` varchar(30) DEFAULT NULL,
  `INITIALES` varchar(4) DEFAULT NULL,
  `TITRE_ID` int(2) DEFAULT NULL,
  `ARCHIVE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_COLLABORATEUR_ETABLISSEMENT_ID` FOREIGN KEY (`ETABLISSEMENT_ID`) REFERENCES `etablissement` (`ETABLISSEMENT_ID`),
  CONSTRAINT `FK_COLLABORATEUR_SPECIALITE_ID` FOREIGN KEY (`SPECIALITE_ID`) REFERENCES `specialite` (`SPECIALITE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_COLLABORATEUR_TITRE_ID` FOREIGN KEY (`TITRE_ID`) REFERENCES `titre` (`TITRE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PLATEFORME`;
CREATE TABLE `PLATEFORME` (
  `PLATEFORME_ID` int(10) NOT NULL DEFAULT '0',
  `NOM` varchar(50) NOT NULL DEFAULT '',
  `ALIAS` varchar(5) DEFAULT NULL,
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`PLATEFORME_ID`),
  CONSTRAINT `FK_PLATEFORME_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `DESTRUCTION_MOTIF`;
CREATE TABLE `DESTRUCTION_MOTIF` (
  `DESTRUCTION_MOTIF_ID` int(3) NOT NULL DEFAULT '0',
  `MOTIF` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`DESTRUCTION_MOTIF_ID`),
  KEY `FK_DESTRUCTION_MOTIF_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_DESTRUCTION_MOTIF_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CESSION_STATUT`;
CREATE TABLE `CESSION_STATUT` (
  `CESSION_STATUT_ID` int(2) NOT NULL DEFAULT '0',
  `STATUT` char(15) NOT NULL DEFAULT '',
  PRIMARY KEY (`CESSION_STATUT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CESSION_TYPE`;
CREATE TABLE `CESSION_TYPE` (
  `CESSION_TYPE_ID` int(2) NOT NULL,
  `TYPE` char(15) NOT NULL DEFAULT '',
  PRIMARY KEY (`CESSION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `CESSION_EXAMEN`;
CREATE TABLE `CESSION_EXAMEN` (
  `CESSION_EXAMEN_ID` int(3) NOT NULL DEFAULT '0',
  `EXAMEN` varchar(200) NOT NULL,
  `EXAMEN_EN` varchar(50) DEFAULT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`CESSION_EXAMEN_ID`),
  KEY `FK_CESSION_EXAMEN_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_CESSION_EXAMEN_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `PROFIL`;
CREATE TABLE `PROFIL` (
  `PROFIL_ID` int(10) NOT NULL DEFAULT '0',
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `ANONYME` tinyint(1) DEFAULT '0',
  `ADMIN` tinyint(1) NOT NULL DEFAULT '0',
  `ACCES_ADMINISTRATION` tinyint(1) NOT NULL DEFAULT '0',
  `PROFIL_EXPORT` int(11) DEFAULT '0',
  `ARCHIVE` tinyint(1) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`PROFIL_ID`),
  CONSTRAINT `FK_PROFIL_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `UTILISATEUR`;
CREATE TABLE `UTILISATEUR` (
  `UTILISATEUR_ID`     INT(10)      NOT NULL DEFAULT '0',
  `LOGIN`              VARCHAR(100) NOT NULL DEFAULT '',
  `PASSWORD`           VARCHAR(100) NOT NULL DEFAULT '',
  `ARCHIVE`            TINYINT(1)            DEFAULT '0',
  `LDAP` 			   BIT(1) 		NOT NULL DEFAULT '0',
  `EMAIL`              VARCHAR(50)           DEFAULT NULL,
  `TIMEOUT`            DATE                  DEFAULT NULL,
  `COLLABORATEUR_ID`   INT(10)               DEFAULT NULL,
  `SUPER`              TINYINT(1)   NOT NULL DEFAULT '0',
  `PLATEFORME_ORIG_ID` INT(10)               DEFAULT NULL,
  PRIMARY KEY (`UTILISATEUR_ID`),
  KEY `FK_UTILISATEUR_COLLABORATEUR_ID` (`COLLABORATEUR_ID`),
  KEY `FK_UTIL_PF_ORIG_ID` (`PLATEFORME_ORIG_ID`),
  CONSTRAINT `FK_UTILISATEUR_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `COLLABORATEUR` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_UTIL_PF_ORIG_ID` FOREIGN KEY (`PLATEFORME_ORIG_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

--DROP TABLE IF EXISTS `PLATEFORME_ADMINISTRATEUR`;
CREATE TABLE `PLATEFORME_ADMINISTRATEUR` (
  `PLATEFORME_ID` int(10) NOT NULL DEFAULT '0',
  `UTILISATEUR_ID` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`PLATEFORME_ID`,`UTILISATEUR_ID`),
  CONSTRAINT `FK_PLATEFORME_ADMINISTRATEUR_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`),
  CONSTRAINT `FK_PLATEFORME_ADMINISTRATEUR_UTILISATEUR_ID` FOREIGN KEY (`UTILISATEUR_ID`) REFERENCES `utilisateur` (`UTILISATEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CONTEXTE`;
CREATE TABLE `CONTEXTE` (
  `CONTEXTE_ID` int(10) NOT NULL,
  `NOM` char(25) NOT NULL DEFAULT '',
  `LIBELLE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CONTEXTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `COULEUR`;
CREATE TABLE `COULEUR` (
  `COULEUR_ID` int(10) NOT NULL DEFAULT '0',
  `COULEUR` varchar(25) NOT NULL,
  `HEXA` varchar(10) NOT NULL,
  `ORDRE_VISOTUBE` int(3) DEFAULT NULL,
  PRIMARY KEY (`COULEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `BANQUE`;
CREATE TABLE `BANQUE` (
  `BANQUE_ID` int(10) NOT NULL DEFAULT '0',
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  `CONTACT_ID` int(10) DEFAULT NULL,
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `IDENTIFICATION` varchar(50) DEFAULT NULL,
  `DESCRIPTION` text,
  `PROPRIETAIRE_ID` int(10) DEFAULT NULL,
  `AUTORISE_CROSS_PATIENT` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `CONTEXTE_ID` int(2) DEFAULT NULL,
  `PLATEFORME_ID` int(10) NOT NULL DEFAULT '0',
  `DEFMALADIES` tinyint(1) NOT NULL DEFAULT '1',
  `DEFAUT_MALADIE` varchar(250) DEFAULT NULL,
  `DEFAUT_MALADIE_CODE` varchar(50) DEFAULT NULL,
  `ECHANTILLON_COULEUR_ID` int(10) DEFAULT NULL,
  `PROD_DERIVE_COULEUR_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`BANQUE_ID`),
  CONSTRAINT `FK_BANQUE_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_BANQUE_CONTACT_ID` FOREIGN KEY (`CONTACT_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_BANQUE_CONTEXTE_ID` FOREIGN KEY (`CONTEXTE_ID`) REFERENCES `contexte` (`CONTEXTE_ID`),
  CONSTRAINT `FK_BANQUE_ECHANTILLON_COULEUR_ID` FOREIGN KEY (`ECHANTILLON_COULEUR_ID`) REFERENCES `couleur` (`COULEUR_ID`),
  CONSTRAINT `FK_BANQUE_PLATERORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`),
  CONSTRAINT `FK_BANQUE_PROD_DERIVE_COULEUR_ID` FOREIGN KEY (`PROD_DERIVE_COULEUR_ID`) REFERENCES `couleur` (`COULEUR_ID`),
  CONSTRAINT `FK_BANQUE_PROPRIETAIRE_ID` FOREIGN KEY (`PROPRIETAIRE_ID`) REFERENCES `service` (`SERVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `DATA_TYPE`;
CREATE TABLE `DATA_TYPE` (
  `DATA_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `TYPE` char(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`DATA_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `ENTITE`;
CREATE TABLE `ENTITE` (
  `ENTITE_ID` int(2) NOT NULL DEFAULT '0',
  `NOM` varchar(25) DEFAULT NULL,
  `MASC` tinyint(1) NOT NULL DEFAULT '0',
  `ANNOTABLE` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ENTITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CHAMP_ENTITE`;
CREATE TABLE `CHAMP_ENTITE` (
  `CHAMP_ENTITE_ID` int(10) NOT NULL,
  `NOM` varchar(50) NOT NULL DEFAULT '',
  `DATA_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `IS_NULL` tinyint(1) NOT NULL DEFAULT '0',
  `IS_UNIQUE` tinyint(1) NOT NULL DEFAULT '0',
  `VALEUR_DEFAUT` varchar(50) DEFAULT NULL,
  `ENTITE_ID` int(2) NOT NULL DEFAULT '0',
  `CAN_IMPORT` tinyint(1) NOT NULL DEFAULT '0',
  `QUERY_CHAMP_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`CHAMP_ENTITE_ID`),
  CONSTRAINT `FK_CHAMP_ENTITE_CHAMP_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `entite` (`ENTITE_ID`),
  CONSTRAINT `FK_CHAMP_ENTITE_DATA_TYPE_ID` FOREIGN KEY (`DATA_TYPE_ID`) REFERENCES `data_type` (`DATA_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `SUBDIVISION`;
CREATE TABLE `SUBDIVISION` (
  `SUBDIVISION_ID` int(2) NOT NULL DEFAULT '0',
  `NOM` varchar(100) DEFAULT NULL,
  `CHAMP_ENTITE_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`SUBDIVISION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CATALOGUE`;
CREATE TABLE `CATALOGUE` (
  `CATALOGUE_ID` int(10) NOT NULL,
  `NOM` char(25) NOT NULL,
  `DESCRIPTION` char(250) DEFAULT NULL,
  `ICONE` char(100) NOT NULL,
  PRIMARY KEY (`CATALOGUE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `BANQUE_CATALOGUE`;
CREATE TABLE `BANQUE_CATALOGUE` (
  `BANQUE_ID` int(10) NOT NULL,
  `CATALOGUE_ID` int(3) NOT NULL,
  PRIMARY KEY (`BANQUE_ID`,`CATALOGUE_ID`),
  CONSTRAINT `FK_BANQUE_CATALOGUE_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `banque` (`BANQUE_ID`),
  CONSTRAINT `FK_BANQUE_CATALOGUE_CATALOGUE_ID` FOREIGN KEY (`CATALOGUE_ID`) REFERENCES `catalogue` (`CATALOGUE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `TABLE_ANNOTATION`;
CREATE TABLE `TABLE_ANNOTATION` (
  `TABLE_ANNOTATION_ID` int(10) NOT NULL,
  `NOM` varchar(100) DEFAULT NULL,
  `DESCRIPTION` text,
  `ENTITE_ID` int(10) NOT NULL DEFAULT '1',
  `CATALOGUE_ID` int(3) DEFAULT NULL,
  `PLATEFORME_ID` int(10) DEFAULT NULL,
  `INLINE_DISPLAY` bit(1) DEFAULT '0',
  PRIMARY KEY (`TABLE_ANNOTATION_ID`),
  CONSTRAINT `FK_TABLE_ANNOTATION_CATALOGUE` FOREIGN KEY (`CATALOGUE_ID`) REFERENCES `catalogue` (`CATALOGUE_ID`),
  CONSTRAINT `FK_TABLE_ANNOTATION_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `entite` (`ENTITE_ID`),
  CONSTRAINT `FK_TABLE_ANNOTATION_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CHAMP_ANNOTATION`;
CREATE TABLE `CHAMP_ANNOTATION` (
  `CHAMP_ANNOTATION_ID` int(10) NOT NULL,
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `DATA_TYPE_ID` int(10) NOT NULL DEFAULT '0',
  `TABLE_ANNOTATION_ID` int(10) NOT NULL DEFAULT '0',
  `COMBINE` tinyint(1) DEFAULT '0',
  `ORDRE` int(3) NOT NULL DEFAULT '0',
  `EDIT` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_CHAMP_ANNOTATION_DATA_TYPE_ID` FOREIGN KEY (`DATA_TYPE_ID`) REFERENCES `data_type` (`DATA_TYPE_ID`),
  CONSTRAINT `FK_CHAMP_ANNOTATION_TABLE_ANNOTATION_ID` FOREIGN KEY (`TABLE_ANNOTATION_ID`) REFERENCES `table_annotation` (`TABLE_ANNOTATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `FICHIER`;
CREATE TABLE `FICHIER` (
  `FICHIER_ID` int(10) NOT NULL DEFAULT '0',
  `NOM` varchar(100) NOT NULL DEFAULT '',
  `PATH` varchar(100) NOT NULL DEFAULT '',
  `MIMETYPE` varchar(100) NOT NULL,
  PRIMARY KEY (`FICHIER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `ITEM`;
CREATE TABLE `ITEM` (
  `ITEM_ID` int(10) NOT NULL,
  `LABEL` varchar(100) NOT NULL DEFAULT '',
  `VALEUR` varchar(100) DEFAULT NULL,
  `CHAMP_ANNOTATION_ID` int(10) NOT NULL DEFAULT '0',
  `PLATEFORME_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`ITEM_ID`),
  CONSTRAINT `FK_ITEM_CHAMP_ANNOTATION_ID` FOREIGN KEY (`CHAMP_ANNOTATION_ID`) REFERENCES `champ_annotation` (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_ITEM_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `ANNOTATION_VALEUR`;
CREATE TABLE `ANNOTATION_VALEUR` (
  `ANNOTATION_VALEUR_ID` int(10) NOT NULL AUTO_INCREMENT,
  `CHAMP_ANNOTATION_ID` int(10) NOT NULL DEFAULT '0',
  `OBJET_ID` int(10) NOT NULL DEFAULT '0',
  `ALPHANUM` varchar(100) DEFAULT NULL,
  `TEXTE` text,
  `ANNO_DATE` datetime DEFAULT NULL,
  `BOOL` tinyint(1) DEFAULT NULL,
  `ITEM_ID` int(10) DEFAULT NULL,
  `FICHIER_ID` int(10) DEFAULT NULL,
  `BANQUE_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`ANNOTATION_VALEUR_ID`),
  UNIQUE KEY `FICHIER_ID` (`FICHIER_ID`),
  CONSTRAINT `FK_ANNOTATION_VALEUR_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `banque` (`BANQUE_ID`),
  CONSTRAINT `FK_ANNOTATION_VALEUR_CHAMP_ANNOTATION_ID` FOREIGN KEY (`CHAMP_ANNOTATION_ID`) REFERENCES `champ_annotation` (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_ANNOTATION_VALEUR_FICHIER_ID` FOREIGN KEY (`FICHIER_ID`) REFERENCES `fichier` (`FICHIER_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ANNOTATION_VALEUR_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `item` (`ITEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8;

CREATE TABLE `CHAMP_DELEGUE` (
  `CHAMP_DELEGUE_ID` int(11) NOT NULL,
  `NOM` varchar(100) NOT NULL,
  `DATA_TYPE_ID` int(11) NOT NULL,
  `ENTITE_ID` int(11) NOT NULL,
  `CONTEXTE` varchar(50) NOT NULL,
  PRIMARY KEY (`CHAMP_DELEGUE_ID`),
  UNIQUE KEY `FK_CHAMP_DELEGUE_ENTITE_ID_CONTEXTE_NOM_UNIQUE_idx` (`ENTITE_ID`,`CONTEXTE`, `NOM`),
  CONSTRAINT `FK_CHAMP_DELEGUE_DATA_TYPE_ID` FOREIGN KEY (`DATA_TYPE_ID`) REFERENCES `DATA_TYPE` (`DATA_TYPE_ID`),
  CONSTRAINT `FK_CHAMP_DELEGUE_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `ENTITE` (`ENTITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CHAMP`;
CREATE TABLE `CHAMP` (
  `CHAMP_ID` int(10) NOT NULL,
  `CHAMP_ANNOTATION_ID` int(10) DEFAULT NULL,
  `CHAMP_ENTITE_ID` int(10) DEFAULT NULL,
  `CHAMP_PARENT_ID` int(10) DEFAULT NULL,
  `CHAMP_DELEGUE_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`CHAMP_ID`),
  CONSTRAINT `FK_CHAMP_CHAMP_ANNOTATION_ID` FOREIGN KEY (`CHAMP_ANNOTATION_ID`) REFERENCES `CHAMP_ANNOTATION` (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_CHAMP_CHAMP_ENTITE_ID` FOREIGN KEY (`CHAMP_ENTITE_ID`) REFERENCES `CHAMP_ENTITE` (`CHAMP_ENTITE_ID`),
  CONSTRAINT `FK_CHAMP_CHAMP_PARENT_ID` FOREIGN KEY (`CHAMP_PARENT_ID`) REFERENCES `CHAMP` (`CHAMP_ID`),
  CONSTRAINT `FK_CHAMP_CHAMP_DELEGUE_ID` FOREIGN KEY (`CHAMP_DELEGUE_ID`) REFERENCES `CHAMP_DELEGUE` (`CHAMP_DELEGUE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CHAMP_CALCULE`;
CREATE TABLE `CHAMP_CALCULE` (
  `CHAMP_CALCULE_ID` int(10) NOT NULL,
  `CHAMP_ANNOTATION_ID` int(11) DEFAULT NULL,
  `CHAMP1_ID` int(11) DEFAULT NULL,
  `OPERATEUR` varchar(10) DEFAULT NULL,
  `CHAMP2_ID` int(11) DEFAULT NULL,
  `VALEUR` varchar(100) DEFAULT NULL,
  `DATA_TYPE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`CHAMP_CALCULE_ID`),
  CONSTRAINT `FK_CHAMP1_ID` FOREIGN KEY (`CHAMP1_ID`) REFERENCES `champ` (`CHAMP_ID`),
  CONSTRAINT `FK_CHAMP2_ID` FOREIGN KEY (`CHAMP2_ID`) REFERENCES `champ` (`CHAMP_ID`),
  CONSTRAINT `FK_CHAMP_ANNOTATION_ID` FOREIGN KEY (`CHAMP_ANNOTATION_ID`) REFERENCES `champ_annotation` (`CHAMP_ANNOTATION_ID`),
  CONSTRAINT `FK_DATA_TYPE_ID` FOREIGN KEY (`DATA_TYPE_ID`) REFERENCES `data_type` (`DATA_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PATIENT`;
CREATE TABLE `PATIENT` (
  `PATIENT_ID` int(10) NOT NULL DEFAULT '0',
  `NIP` varchar(20) DEFAULT NULL,
  `NOM` varchar(50) NOT NULL DEFAULT '',
  `NOM_NAISSANCE` varchar(50) DEFAULT NULL,
  `PRENOM` varchar(50) DEFAULT NULL,
  `SEXE` char(3) DEFAULT NULL,
  `DATE_NAISSANCE` date DEFAULT NULL,
  `VILLE_NAISSANCE` varchar(100) DEFAULT NULL,
  `PAYS_NAISSANCE` varchar(100) DEFAULT NULL,
  `PATIENT_ETAT` varchar(10) NOT NULL DEFAULT 'inconnu',
  `DATE_ETAT` date DEFAULT NULL,
  `DATE_DECES` date DEFAULT NULL,
  `ETAT_INCOMPLET` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`PATIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PATIENT_DELEGATE`;
CREATE TABLE `PATIENT_DELEGATE` (
  `PATIENT_DELEGATE_ID` int(11) NOT NULL,
  `PATIENT_ID` int(11) NOT NULL,
  PRIMARY KEY (`PATIENT_DELEGATE_ID`),
  UNIQUE KEY `PATIENT_ID` (`PATIENT_ID`),
  CONSTRAINT `FK_PATIENT_DELEGATE_PATIENT_ID` FOREIGN KEY (`PATIENT_ID`) REFERENCES `patient` (`PATIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CONDIT_MILIEU`;
CREATE TABLE `CONDIT_MILIEU` (
  `CONDIT_MILIEU_ID` int(10) NOT NULL DEFAULT '0',
  `MILIEU` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`CONDIT_MILIEU_ID`),
  CONSTRAINT `FK_CONDIT_MILIEU_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CONDIT_TYPE`;
CREATE TABLE `CONDIT_TYPE` (
  `CONDIT_TYPE_ID` int(10) NOT NULL DEFAULT '0',
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`CONDIT_TYPE_ID`),
  CONSTRAINT `FK_CONDIT_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CONSENT_TYPE`;
CREATE TABLE `CONSENT_TYPE` (
  `CONSENT_TYPE_ID` int(10) NOT NULL,
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`CONSENT_TYPE_ID`),
  CONSTRAINT `FK_CONSENT_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `MALADIE`;
CREATE TABLE `MALADIE` (
  `MALADIE_ID` int(10) NOT NULL DEFAULT '0',
  `PATIENT_ID` int(10) NOT NULL DEFAULT '0',
  `LIBELLE` varchar(300) NOT NULL DEFAULT 'Inconnu',
  `CODE` varchar(50) DEFAULT NULL,
  `DATE_DIAGNOSTIC` date DEFAULT NULL,
  `DATE_DEBUT` date DEFAULT NULL,
  `SYSTEME_DEFAUT` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`MALADIE_ID`),
  CONSTRAINT `FK_MALADIE_PATIENT_ID` FOREIGN KEY (`PATIENT_ID`) REFERENCES `patient` (`PATIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `maladie_delegate`;
CREATE TABLE `MALADIE_DELEGATE` (
  `MALADIE_DELEGATE_ID` int(10) NOT NULL,
  `MALADIE_ID` int(10) NOT NULL,
  `CONTEXTE_ID` int(2) NOT NULL,
  PRIMARY KEY (`MALADIE_DELEGATE_ID`),
  UNIQUE KEY `MALADIE_ID` (`MALADIE_ID`),
  CONSTRAINT `FK_MALADIE_DEL_CONTEXTE_ID` FOREIGN KEY (`CONTEXTE_ID`) REFERENCES `contexte` (`CONTEXTE_ID`),
  CONSTRAINT `FK_MALADIE_DEL_MALADIE_ID` FOREIGN KEY (`MALADIE_ID`) REFERENCES `maladie` (`MALADIE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `NATURE`;
CREATE TABLE `NATURE` (
  `NATURE_ID` int(10) NOT NULL,
  `NATURE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`NATURE_ID`),
  CONSTRAINT `FK_NATURE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PRELEVEMENT_TYPE`;
CREATE TABLE `PRELEVEMENT_TYPE` (
  `PRELEVEMENT_TYPE_ID` int(10) NOT NULL DEFAULT '0',
  `INCA_CAT` char(2) DEFAULT NULL,
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`PRELEVEMENT_TYPE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `UNITE`;
CREATE TABLE `UNITE` (
  `UNITE_ID` int(2) NOT NULL DEFAULT '0',
  `UNITE` varchar(30) NOT NULL DEFAULT '',
  `TYPE` varchar(15) NOT NULL DEFAULT 'masse',
  PRIMARY KEY (`UNITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `TRANSPORTEUR`;
CREATE TABLE `TRANSPORTEUR` (
  `TRANSPORTEUR_ID` int(10) NOT NULL DEFAULT '0',
  `coordonnee_id` int(10) DEFAULT NULL,
  `NOM` varchar(50) NOT NULL DEFAULT '',
  `CONTACT_NOM` varchar(50) DEFAULT NULL,
  `CONTACT_PRENOM` varchar(50) DEFAULT NULL,
  `CONTACT_TEL` varchar(15) DEFAULT NULL,
  `CONTACT_FAX` varchar(15) DEFAULT NULL,
  `CONTACT_MAIL` varchar(100) DEFAULT NULL,
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`TRANSPORTEUR_ID`),
  CONSTRAINT `FK_TRANSPORTEUR_COORDONNEE_ID` FOREIGN KEY (`coordonnee_id`) REFERENCES `coordonnee` (`COORDONNEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PRELEVEMENT`;
CREATE TABLE `PRELEVEMENT` (
  `PRELEVEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `BANQUE_ID` int(10) NOT NULL DEFAULT '0',
  `CODE` varchar(50) NOT NULL DEFAULT '',
  `NATURE_ID` int(10) NOT NULL DEFAULT '0',
  `MALADIE_ID` int(10) DEFAULT NULL,
  `CONSENT_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `CONSENT_DATE` date DEFAULT NULL,
  `PRELEVEUR_ID` int(10) DEFAULT NULL,
  `SERVICE_PRELEVEUR_ID` int(10) DEFAULT NULL,
  `DATE_PRELEVEMENT` datetime DEFAULT NULL,
  `PRELEVEMENT_TYPE_ID` int(10) DEFAULT NULL,
  `CONDIT_TYPE_ID` int(10) DEFAULT NULL,
  `CONDIT_MILIEU_ID` int(3) DEFAULT NULL,
  `CONDIT_NBR` int(10) DEFAULT NULL,
  `DATE_DEPART` datetime DEFAULT NULL,
  `TRANSPORTEUR_ID` int(10) DEFAULT NULL,
  `TRANSPORT_TEMP` float DEFAULT NULL,
  `DATE_ARRIVEE` datetime DEFAULT NULL,
  `OPERATEUR_ID` int(10) DEFAULT NULL,
  `QUANTITE` decimal(12,3) DEFAULT NULL,
  `QUANTITE_UNITE_ID` int(10) DEFAULT NULL,
  `PATIENT_NDA` varchar(20) DEFAULT NULL,
  `NUMERO_LABO` varchar(50) DEFAULT NULL,
  `STERILE` tinyint(1) DEFAULT NULL,
  `CONG_ARRIVEE` tinyint(1) DEFAULT '1',
  `CONG_DEPART` tinyint(1) DEFAULT NULL,
  `CONFORME_ARRIVEE` tinyint(1) DEFAULT NULL,
  `ETAT_INCOMPLET` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `DATE_PEREMPTION` datetime DEFAULT NULL,
  `DATE_VALIDATION` datetime DEFAULT NULL,
  `NIVEAU_VALIDATION_ID` int(11) DEFAULT NULL,
  `COMMENTAIRE_VALIDATION` varchar(250) DEFAULT NULL,
  `VALIDEUR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_PRELEVEMENT_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `banque` (`BANQUE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_CONDIT_MILIEU_ID` FOREIGN KEY (`CONDIT_MILIEU_ID`) REFERENCES `condit_milieu` (`CONDIT_MILIEU_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_PRELEVEMENT_CONDIT_TYPE_ID` FOREIGN KEY (`CONDIT_TYPE_ID`) REFERENCES `condit_type` (`CONDIT_TYPE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_PRELEVEMENT_CONSENT_TYPE_ID` FOREIGN KEY (`CONSENT_TYPE_ID`) REFERENCES `consent_type` (`CONSENT_TYPE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_MALADIE_ID` FOREIGN KEY (`MALADIE_ID`) REFERENCES `maladie` (`MALADIE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_NATURE_ID` FOREIGN KEY (`NATURE_ID`) REFERENCES `nature` (`NATURE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_OPERATEUR_ID` FOREIGN KEY (`OPERATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_PRELEVEMENT_PRELEVEMENT_TYPE_ID` FOREIGN KEY (`PRELEVEMENT_TYPE_ID`) REFERENCES `prelevement_type` (`PRELEVEMENT_TYPE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_PRELEVEMENT_PRELEVEUR_ID` FOREIGN KEY (`PRELEVEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_PRELEVEMENT_QUANTITE_UNITE_ID` FOREIGN KEY (`QUANTITE_UNITE_ID`) REFERENCES `unite` (`UNITE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_SERVICE_PRELEVEUR_ID` FOREIGN KEY (`SERVICE_PRELEVEUR_ID`) REFERENCES `service` (`SERVICE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_TRANSPORTEUR_ID` FOREIGN KEY (`TRANSPORTEUR_ID`) REFERENCES `transporteur` (`TRANSPORTEUR_ID`),
  CONSTRAINT `FK_PRELEVEMENT_VALIDEUR_ID` FOREIGN KEY (`VALIDEUR_ID`) REFERENCES `utilisateur` (`UTILISATEUR_ID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `RISQUE`;
CREATE TABLE `RISQUE` (
  `RISQUE_ID`     INT(3)       NOT NULL DEFAULT '0',
  `NOM`           VARCHAR(200) NOT NULL,
  `INFECTIEUX`    TINYINT(1)   NOT NULL DEFAULT '0',
  `PLATEFORME_ID` INT(10)      NOT NULL,
  PRIMARY KEY (`RISQUE_ID`),
  KEY `FK_RISQUE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_RISQUE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

--DROP TABLE IF EXISTS `PRELEVEMENT_RISQUE`;
CREATE TABLE `PRELEVEMENT_RISQUE` (
  `PRELEVEMENT_ID` INT(10) NOT NULL DEFAULT '0',
  `RISQUE_ID`      INT(3)  NOT NULL DEFAULT '0',
  PRIMARY KEY (`PRELEVEMENT_ID`, `RISQUE_ID`),
  KEY `FK_PRELEVEMENT_RISQUE_RISQUE_ID` (`RISQUE_ID`),
  CONSTRAINT `FK_PRELEVEMENT_RISQUE_PRELEVEMENT_ID` FOREIGN KEY (`PRELEVEMENT_ID`) REFERENCES `PRELEVEMENT` (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_PRELEVEMENT_RISQUE_RISQUE_ID` FOREIGN KEY (`RISQUE_ID`) REFERENCES `RISQUE` (`RISQUE_ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

--DROP TABLE IF EXISTS `LABO_INTER`;
CREATE TABLE `LABO_INTER` (
  `LABO_INTER_ID` int(10) NOT NULL DEFAULT '0',
  `PRELEVEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `ORDRE` int(2) NOT NULL DEFAULT '1',
  `SERVICE_ID` int(10) DEFAULT NULL,
  `DATE_ARRIVEE` datetime DEFAULT NULL,
  `CONSERV_TEMP` float DEFAULT NULL,
  `STERILE` tinyint(1) DEFAULT NULL,
  `CONGELATION` tinyint(1) DEFAULT NULL,
  `TRANSPORT_TEMP` float DEFAULT NULL,
  `DATE_DEPART` datetime DEFAULT NULL,
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  `TRANSPORTEUR_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`LABO_INTER_ID`),
  CONSTRAINT `FK_LABO_INTER_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `collaborateur` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_LABO_INTER_PRELEVEMENT_ID` FOREIGN KEY (`PRELEVEMENT_ID`) REFERENCES `prelevement` (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_LABO_INTER_SERVICE_ID` FOREIGN KEY (`SERVICE_ID`) REFERENCES `service` (`SERVICE_ID`),
  CONSTRAINT `FK_LABO_INTER_TRANSPORTEUR_ID` FOREIGN KEY (`TRANSPORTEUR_ID`) REFERENCES `transporteur` (`TRANSPORTEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PRELEVEMENT_DELEGATE`;
CREATE TABLE `PRELEVEMENT_DELEGATE` (
  `PRELEVEMENT_DELEGATE_ID` int(10) NOT NULL,
  `PRELEVEMENT_ID` int(10) NOT NULL,
  PRIMARY KEY (`PRELEVEMENT_DELEGATE_ID`),
  UNIQUE KEY `PRELEVEMENT_ID` (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_PREL_DEL_PRELEVEMENT_ID` FOREIGN KEY (`PRELEVEMENT_ID`) REFERENCES `prelevement` (`PRELEVEMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PRELEVEMENT_SERO`;
CREATE TABLE `PRELEVEMENT_SERO` (
  `PRELEVEMENT_DELEGATE_ID` int(10) NOT NULL,
  `LIBELLE` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`PRELEVEMENT_DELEGATE_ID`),
  CONSTRAINT `FK_PREL_SERO_PREL_DEL_ID` FOREIGN KEY (`PRELEVEMENT_DELEGATE_ID`) REFERENCES `prelevement_delegate` (`PRELEVEMENT_DELEGATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PROTOCOLE`;
CREATE TABLE `PROTOCOLE` (
  `PROTOCOLE_ID` int(3) NOT NULL,
  `NOM` varchar(200) NOT NULL,
  `DESCRIPTION` text,
  `PLATEFORME_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`PROTOCOLE_ID`),
  CONSTRAINT `FK_PROTOCOLE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `plateforme` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PROTOCOLE_TYPE`;
CREATE TABLE `PROTOCOLE_TYPE` (
  `PROTOCOLE_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`PROTOCOLE_TYPE_ID`),
  KEY `FK_PROTOCOLE_TYPE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_PROTOCOLE_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `DIAGNOSTIC`
--

DROP TABLE IF EXISTS `DIAGNOSTIC`;
/*!40101 SET @saved_cs_client = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DIAGNOSTIC` (
  `DIAGNOSTIC_ID`  INT(3)       NOT NULL,
  `NOM`           VARCHAR(200) NOT NULL,
  `DESCRIPTION`   TEXT,
  `PLATEFORME_ID` INT(10) DEFAULT NULL,
  PRIMARY KEY (`DIAGNOSTIC_ID`),
  KEY `FK_DIAGNOSTIC_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_DIAGNOSTIC_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
  
 --DROP TABLE IF EXISTS `MALADIE_SERO`;
CREATE TABLE `MALADIE_SERO` (
  `MALADIE_DELEGATE_ID` INT(10) NOT NULL,
  `DIAGNOSTIC_ID`          INT(10) NOT NULL,
  PRIMARY KEY (`MALADIE_DELEGATE_ID`, `DIAGNOSTIC_ID`),
  CONSTRAINT `FK_MAL_SERO_MAL_DEL_ID` FOREIGN KEY (`MALADIE_DELEGATE_ID`) REFERENCES `MALADIE_DELEGATE` (`MALADIE_DELEGATE_ID`),
  CONSTRAINT `FK_MAL_SERO_DIAG_ID` FOREIGN KEY (`DIAGNOSTIC_ID`) REFERENCES `DIAGNOSTIC` (`DIAGNOSTIC_ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

--DROP TABLE IF EXISTS `PRELEVEMENT_SERO_PROTOCOLE`;
CREATE TABLE `PRELEVEMENT_SERO_PROTOCOLE` (
  `PRELEVEMENT_DELEGATE_ID` int(10) NOT NULL,
  `PROTOCOLE_ID` int(10) NOT NULL,
  PRIMARY KEY (`PRELEVEMENT_DELEGATE_ID`,`PROTOCOLE_ID`),
  CONSTRAINT `FK_PREL_PROTO_PREL_ID` FOREIGN KEY (`PRELEVEMENT_DELEGATE_ID`) REFERENCES `prelevement_sero` (`PRELEVEMENT_DELEGATE_ID`),
  CONSTRAINT `FK_PREL_PROTO_PROTO_ID` FOREIGN KEY (`PROTOCOLE_ID`) REFERENCES `protocole` (`PROTOCOLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PRELEVEMENT_XENO`;
CREATE TABLE `PRELEVEMENT_XENO` (
  `PRELEVEMENT_DELEGATE_ID` int(10) NOT NULL,
  `SOURIS` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`PRELEVEMENT_DELEGATE_ID`),
  CONSTRAINT `FK_PREL_XENO_PREL_DEL_ID` FOREIGN KEY (`PRELEVEMENT_DELEGATE_ID`) REFERENCES `prelevement_delegate` (`PRELEVEMENT_DELEGATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CONTRAT`;
CREATE TABLE `CONTRAT` (
  `CONTRAT_ID` int(10) NOT NULL DEFAULT '0',
  `PLATEFORME_ID` int(10) NOT NULL,
  `NUMERO` varchar(50) NOT NULL,
  `DATE_DEMANDE_CESSION` date DEFAULT NULL,
  `DATE_VALIDATION` date DEFAULT NULL,
  `DATE_DEMANDE_REDACTION` date DEFAULT NULL,
  `DATE_ENVOI_CONTRAT` date DEFAULT NULL,
  `DATE_SIGNATURE` date DEFAULT NULL,
  `TITRE_PROJET` varchar(100) DEFAULT NULL,
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  `SERVICE_ID` int(10) DEFAULT NULL,
  `PROTOCOLE_TYPE_ID` int(2) DEFAULT NULL,
  `DESCRIPTION` text,
  `ETABLISSEMENT_ID` int(10) DEFAULT NULL,
  `MONTANT` float DEFAULT NULL,
  PRIMARY KEY (`CONTRAT_ID`),
  KEY `FK_CONTRAT_PROTOCOLE_TYPE_ID` (`PROTOCOLE_TYPE_ID`),
  KEY `FK_CONTRAT_SERVICE_ID` (`SERVICE_ID`),
  KEY `FK_CONTRAT_COLLABORATEUR_ID` (`COLLABORATEUR_ID`),
  KEY `FK_CONTRAT_ETABLISSEMENT_ID` (`ETABLISSEMENT_ID`),
  KEY `FK_CONTRAT_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_CONTRAT_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `COLLABORATEUR` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_CONTRAT_ETABLISSEMENT_ID` FOREIGN KEY (`ETABLISSEMENT_ID`) REFERENCES `ETABLISSEMENT` (`ETABLISSEMENT_ID`),
  CONSTRAINT `FK_CONTRAT_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`),
  CONSTRAINT `FK_CONTRAT_PROTOCOLE_TYPE_ID` FOREIGN KEY (`PROTOCOLE_TYPE_ID`) REFERENCES `PROTOCOLE_TYPE` (`PROTOCOLE_TYPE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_CONTRAT_SERVICE_ID` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`SERVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CESSION`;
CREATE TABLE `CESSION` (
  `CESSION_ID` int(10) NOT NULL DEFAULT '0',
  `NUMERO` varchar(100) NOT NULL,
  `BANQUE_ID` int(11) DEFAULT NULL,
  `CESSION_TYPE_ID` int(11) DEFAULT NULL,
  `DEMANDE_DATE` date DEFAULT NULL,
  `CESSION_EXAMEN_ID` int(3) DEFAULT NULL,
  `CONTRAT_ID` int(10) DEFAULT NULL,
  `ETUDE_TITRE` varchar(100) DEFAULT NULL,
  `DESTINATAIRE_ID` int(10) DEFAULT NULL,
  `SERVICE_DEST_ID` int(10) DEFAULT NULL,
  `DESCRIPTION` text,
  `DEMANDEUR_ID` int(10) DEFAULT NULL,
  `CESSION_STATUT_ID` int(2) NOT NULL DEFAULT '0',
  `VALIDATION_DATE` date DEFAULT NULL,
  `EXECUTANT_ID` int(10) DEFAULT NULL,
  `TRANSPORTEUR_ID` int(10) DEFAULT NULL,
  `DEPART_DATE` datetime DEFAULT NULL,
  `ARRIVEE_DATE` datetime DEFAULT NULL,
  `OBSERVATIONS` varchar(250) DEFAULT NULL,
  `TEMPERATURE` float DEFAULT NULL,
  `DESTRUCTION_MOTIF_ID` int(3) DEFAULT NULL,
  `DESTRUCTION_DATE` datetime DEFAULT NULL,
  `ETAT_INCOMPLET` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `LAST_SCAN_CHECK_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`CESSION_ID`),
  KEY `FK_CESSION_BANQUE_ID` (`BANQUE_ID`),
  KEY `FK_CESSION_CESSION_TYPE_ID` (`CESSION_TYPE_ID`),
  KEY `FK_CESSION_CESSION_EXAMEN_ID` (`CESSION_EXAMEN_ID`),
  KEY `FK_CESSION_CONTRAT_ID` (`CONTRAT_ID`),
  KEY `FK_CESSION_DESTINATAIRE_ID` (`DESTINATAIRE_ID`),
  KEY `FK_CESSION_SERVICE_DEST_ID` (`SERVICE_DEST_ID`),
  KEY `FK_CESSION_DEMANDEUR_ID` (`DEMANDEUR_ID`),
  KEY `FK_CESSION_CESSION_STATUT_ID` (`CESSION_STATUT_ID`),
  KEY `FK_CESSION_EXECUTANT_ID` (`EXECUTANT_ID`),
  KEY `FK_CESSION_TRANSPORTEUR_ID` (`TRANSPORTEUR_ID`),
  KEY `FK_CESSION_DESTRUCTION_MOTIF_ID` (`DESTRUCTION_MOTIF_ID`),
  CONSTRAINT `FK_CESSION_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `BANQUE` (`BANQUE_ID`),
  CONSTRAINT `FK_CESSION_CESSION_EXAMEN_ID` FOREIGN KEY (`CESSION_EXAMEN_ID`) REFERENCES `CESSION_EXAMEN` (`CESSION_EXAMEN_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_CESSION_CESSION_STATUT_ID` FOREIGN KEY (`CESSION_STATUT_ID`) REFERENCES `CESSION_STATUT` (`CESSION_STATUT_ID`),
  CONSTRAINT `FK_CESSION_CESSION_TYPE_ID` FOREIGN KEY (`CESSION_TYPE_ID`) REFERENCES `CESSION_TYPE` (`CESSION_TYPE_ID`),
  CONSTRAINT `FK_CESSION_CONTRAT_ID` FOREIGN KEY (`CONTRAT_ID`) REFERENCES `CONTRAT` (`CONTRAT_ID`),
  CONSTRAINT `FK_CESSION_DEMANDEUR_ID` FOREIGN KEY (`DEMANDEUR_ID`) REFERENCES `COLLABORATEUR` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_CESSION_DESTINATAIRE_ID` FOREIGN KEY (`DESTINATAIRE_ID`) REFERENCES `COLLABORATEUR` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_CESSION_DESTRUCTION_MOTIF_ID` FOREIGN KEY (`DESTRUCTION_MOTIF_ID`) REFERENCES `DESTRUCTION_MOTIF` (`DESTRUCTION_MOTIF_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_CESSION_EXECUTANT_ID` FOREIGN KEY (`EXECUTANT_ID`) REFERENCES `COLLABORATEUR` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_CESSION_SERVICE_DEST_ID` FOREIGN KEY (`SERVICE_DEST_ID`) REFERENCES `SERVICE` (`SERVICE_ID`),
  CONSTRAINT `FK_CESSION_TRANSPORTEUR_ID` FOREIGN KEY (`TRANSPORTEUR_ID`) REFERENCES `TRANSPORTEUR` (`TRANSPORTEUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CESSION_DELEGATE` (
  `CESSION_DELEGATE_ID` int(11) NOT NULL,
  `CESSION_ID` int(11) NOT NULL,
  PRIMARY KEY (`CESSION_DELEGATE_ID`),
  UNIQUE KEY `CESSION_ID` (`CESSION_ID`),
  CONSTRAINT `FK_CESSION_DELEGATE_CESSION_ID` FOREIGN KEY (`CESSION_ID`) REFERENCES `CESSION` (`CESSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CONTENEUR_TYPE`;
CREATE TABLE `CONTENEUR_TYPE` (
  `CONTENEUR_TYPE_ID` int(10) NOT NULL DEFAULT '0',
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`CONTENEUR_TYPE_ID`),
  KEY `FK_CONTENEUR_TYPE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_CONTENEUR_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CONTENEUR`;
CREATE TABLE `CONTENEUR` (
  `CONTENEUR_ID` int(10) NOT NULL DEFAULT '0',
  `CONTENEUR_TYPE_ID` int(2) DEFAULT NULL,
  `CODE` varchar(5) NOT NULL DEFAULT '',
  `NOM` varchar(50) DEFAULT NULL,
  `TEMP` float DEFAULT NULL,
  `PIECE` varchar(20) DEFAULT NULL,
  `NBR_NIV` int(2) DEFAULT NULL,
  `NBR_ENC` int(2) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `SERVICE_ID` int(10) NOT NULL DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `PLATEFORME_ORIG_ID` int(2) NOT NULL DEFAULT '1',
  `PARTAGE` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`CONTENEUR_ID`),
  KEY `FK_CONTENEUR_CONTENEUR_TYPE_ID` (`CONTENEUR_TYPE_ID`),
  KEY `FK_CONTENEUR_SERVICE_ID` (`SERVICE_ID`),
  KEY `FK_CONTENEUR_PF_ORIG_ID` (`PLATEFORME_ORIG_ID`),
  CONSTRAINT `FK_CONTENEUR_CONTENEUR_TYPE_ID` FOREIGN KEY (`CONTENEUR_TYPE_ID`) REFERENCES `CONTENEUR_TYPE` (`CONTENEUR_TYPE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_CONTENEUR_PF_ORIG_ID` FOREIGN KEY (`PLATEFORME_ORIG_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`),
  CONSTRAINT `FK_CONTENEUR_SERVICE_ID` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`SERVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `ENCEINTE_TYPE`;
CREATE TABLE `ENCEINTE_TYPE` (
  `ENCEINTE_TYPE_ID` int(10) NOT NULL DEFAULT '0',
  `TYPE` varchar(200) NOT NULL,
  `PREFIXE` varchar(5) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`ENCEINTE_TYPE_ID`),
  KEY `FK_ENCEINTE_TYPE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_ENCEINTE_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `ENCEINTE`;
CREATE TABLE `ENCEINTE` (
  `ENCEINTE_ID` int(10) NOT NULL DEFAULT '0',
  `ENCEINTE_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `CONTENEUR_ID` int(10) DEFAULT NULL,
  `ENCEINTE_PERE_ID` int(10) DEFAULT NULL,
  `NOM` varchar(50) NOT NULL,
  `POSITION` int(10) NOT NULL DEFAULT '0',
  `ALIAS` varchar(50) DEFAULT NULL,
  `NB_PLACES` int(4) NOT NULL DEFAULT '0',
  `ENTITE_ID` int(2) DEFAULT NULL,
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `COULEUR_ID` int(3) DEFAULT NULL,
  PRIMARY KEY (`ENCEINTE_ID`),
  KEY `FK_ENCEINTE_CONTENEUR_ID` (`CONTENEUR_ID`),
  KEY `FK_ENCEINTE_ENCEINTE_PERE_ID` (`ENCEINTE_PERE_ID`),
  KEY `FK_ENCEINTE_ENTITE_ID` (`ENTITE_ID`),
  KEY `FK_ENCEINTE_ENCEINTE_TYPE_ID` (`ENCEINTE_TYPE_ID`),
  KEY `FK_ENCEINTE_COULEUR_ID` (`COULEUR_ID`),
  CONSTRAINT `FK_ENCEINTE_CONTENEUR_ID` FOREIGN KEY (`CONTENEUR_ID`) REFERENCES `CONTENEUR` (`CONTENEUR_ID`),
  CONSTRAINT `FK_ENCEINTE_COULEUR_ID` FOREIGN KEY (`COULEUR_ID`) REFERENCES `COULEUR` (`COULEUR_ID`),
  CONSTRAINT `FK_ENCEINTE_ENCEINTE_PERE_ID` FOREIGN KEY (`ENCEINTE_PERE_ID`) REFERENCES `ENCEINTE` (`ENCEINTE_ID`),
  CONSTRAINT `FK_ENCEINTE_ENCEINTE_TYPE_ID` FOREIGN KEY (`ENCEINTE_TYPE_ID`) REFERENCES `ENCEINTE_TYPE` (`ENCEINTE_TYPE_ID`),
  CONSTRAINT `FK_ENCEINTE_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `ENTITE` (`ENTITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `TERMINALE_NUMEROTATION`;
CREATE TABLE `TERMINALE_NUMEROTATION` (
  `TERMINALE_NUMEROTATION_ID` int(10) NOT NULL DEFAULT '0',
  `LIGNE` char(3) NOT NULL DEFAULT '',
  `COLONNE` char(3) NOT NULL DEFAULT '',
  PRIMARY KEY (`TERMINALE_NUMEROTATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `TERMINALE_TYPE`;
CREATE TABLE `TERMINALE_TYPE` (
  `TERMINALE_TYPE_ID` int(2) NOT NULL,
  `TYPE` varchar(25) NOT NULL DEFAULT '',
  `NB_PLACES` int(5) NOT NULL DEFAULT '0',
  `HAUTEUR` int(3) NOT NULL DEFAULT '0',
  `LONGUEUR` int(3) NOT NULL DEFAULT '0',
  `SCHEME` varchar(100) DEFAULT NULL,
  `DEPART_NUM_HAUT` tinyint(1) NOT NULL,
  PRIMARY KEY (`TERMINALE_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `TERMINALE`;
CREATE TABLE `TERMINALE` (
  `TERMINALE_ID` int(10) NOT NULL DEFAULT '0',
  `ENCEINTE_ID` int(10) NOT NULL DEFAULT '0',
  `TERMINALE_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `NOM` varchar(50) NOT NULL,
  `POSITION` int(10) NOT NULL DEFAULT '0',
  `ALIAS` varchar(50) DEFAULT NULL,
  `BANQUE_ID` int(10) DEFAULT NULL,
  `ENTITE_ID` int(2) DEFAULT NULL,
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `TERMINALE_NUMEROTATION_ID` int(10) NOT NULL DEFAULT '0',
  `COULEUR_ID` int(3) DEFAULT NULL,
  PRIMARY KEY (`TERMINALE_ID`),
  KEY `FK_TERMINALE_TERMINALE_TYPE_ID` (`TERMINALE_TYPE_ID`),
  KEY `FK_TERMINALE_ENCEINTE_ID` (`ENCEINTE_ID`),
  KEY `FK_TERMINALE_BANQUE_ID` (`BANQUE_ID`),
  KEY `FK_TERMINALE_ENTITE_ID` (`ENTITE_ID`),
  KEY `FK_TERMINALE_TERMINALE_NUMEROTATION_ID` (`TERMINALE_NUMEROTATION_ID`),
  KEY `FK_TERMINALE_COULEUR_ID` (`COULEUR_ID`),
  CONSTRAINT `FK_TERMINALE_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `BANQUE` (`BANQUE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_TERMINALE_COULEUR_ID` FOREIGN KEY (`COULEUR_ID`) REFERENCES `COULEUR` (`COULEUR_ID`),
  CONSTRAINT `FK_TERMINALE_ENCEINTE_ID` FOREIGN KEY (`ENCEINTE_ID`) REFERENCES `ENCEINTE` (`ENCEINTE_ID`),
  CONSTRAINT `FK_TERMINALE_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `ENTITE` (`ENTITE_ID`),
  CONSTRAINT `FK_TERMINALE_TERMINALE_NUMEROTATION_ID` FOREIGN KEY (`TERMINALE_NUMEROTATION_ID`) REFERENCES `TERMINALE_NUMEROTATION` (`TERMINALE_NUMEROTATION_ID`),
  CONSTRAINT `FK_TERMINALE_TERMINALE_TYPE_ID` FOREIGN KEY (`TERMINALE_TYPE_ID`) REFERENCES `TERMINALE_TYPE` (`TERMINALE_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `EMPLACEMENT`;
CREATE TABLE `EMPLACEMENT` (
  `EMPLACEMENT_ID` int(10) NOT NULL DEFAULT '0',
  `TERMINALE_ID` int(10) NOT NULL DEFAULT '0',
  `POSITION` int(10) NOT NULL DEFAULT '0',
  `OBJET_ID` int(10) DEFAULT NULL,
  `ENTITE_ID` int(2) DEFAULT NULL,
  `VIDE` tinyint(1) DEFAULT '1',
  `ADRL` varchar(50) DEFAULT NULL,
  `ADRP` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`EMPLACEMENT_ID`),
  KEY `FK_EMPLACEMENT_TERMINALE_ID` (`TERMINALE_ID`),
  KEY `FK_EMPLACEMENT_ENTITE_ID` (`ENTITE_ID`),
  CONSTRAINT `FK_EMPLACEMENT_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `ENTITE` (`ENTITE_ID`),
  CONSTRAINT `FK_EMPLACEMENT_TERMINALE_ID` FOREIGN KEY (`TERMINALE_ID`) REFERENCES `TERMINALE` (`TERMINALE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `MODE_PREPA`;
CREATE TABLE `MODE_PREPA` (
  `MODE_PREPA_ID` int(3) NOT NULL DEFAULT '0',
  `NOM` varchar(200) NOT NULL,
  `NOM_EN` varchar(25) DEFAULT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`MODE_PREPA_ID`),
  KEY `FK_MODE_PREPA_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_MODE_PREPA_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `MODE_PREPA_DERIVE`;
CREATE TABLE `MODE_PREPA_DERIVE` (
  `MODE_PREPA_DERIVE_ID` int(3) NOT NULL,
  `NOM` varchar(200) NOT NULL,
  `NOM_EN` varchar(25) DEFAULT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`MODE_PREPA_DERIVE_ID`),
  KEY `FK_MODE_PREPA_DERIVE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_MODE_PREPA_DERIVE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PROD_QUALITE`;
CREATE TABLE `PROD_QUALITE` (
  `PROD_QUALITE_ID` int(3) NOT NULL DEFAULT '0',
  `PROD_QUALITE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`PROD_QUALITE_ID`),
  KEY `FK_PROD_QUALITE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_PROD_QUALITE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `PROD_TYPE`;
CREATE TABLE `PROD_TYPE` (
  `PROD_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `TYPE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`PROD_TYPE_ID`),
  KEY `FK_PROD_TYPE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_PROD_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `TRANSFORMATION`;
CREATE TABLE `TRANSFORMATION` (
  `TRANSFORMATION_ID` int(10) NOT NULL DEFAULT '0',
  `OBJET_ID` int(10) NOT NULL DEFAULT '0',
  `ENTITE_ID` int(2) NOT NULL DEFAULT '0',
  `QUANTITE` decimal(12,3) DEFAULT NULL,
  `QUANTITE_UNITE_ID` int(2) DEFAULT NULL,
  PRIMARY KEY (`TRANSFORMATION_ID`),
  KEY `FK_TRANSFORMATION_QUANTITE_UNITE_ID` (`QUANTITE_UNITE_ID`),
  KEY `FK_TRANSFORMATION_ENTITE_ID` (`ENTITE_ID`),
  CONSTRAINT `FK_TRANSFORMATION_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `ENTITE` (`ENTITE_ID`),
  CONSTRAINT `FK_TRANSFORMATION_QUANTITE_UNITE_ID` FOREIGN KEY (`QUANTITE_UNITE_ID`) REFERENCES `UNITE` (`UNITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `OBJET_STATUT`;
CREATE TABLE `OBJET_STATUT` (
  `OBJET_STATUT_ID` int(2) NOT NULL DEFAULT '0',
  `STATUT` varchar(20) NOT NULL DEFAULT '',
  PRIMARY KEY (`OBJET_STATUT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `PROD_DERIVE`;
CREATE TABLE `PROD_DERIVE` (
  `PROD_DERIVE_ID` int(10) NOT NULL DEFAULT '0',
  `BANQUE_ID` int(10) NOT NULL DEFAULT '0',
  `PROD_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `CODE` varchar(50) NOT NULL DEFAULT '',
  `CODE_LABO` varchar(50) DEFAULT NULL,
  `OBJET_STATUT_ID` int(2) DEFAULT NULL,
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  `VOLUME_INIT` decimal(12,3) DEFAULT NULL,
  `VOLUME` decimal(12,3) DEFAULT NULL,
  `CONC` decimal(12,3) DEFAULT NULL,
  `DATE_STOCK` datetime DEFAULT NULL,
  `EMPLACEMENT_ID` int(10) DEFAULT NULL,
  `VOLUME_UNITE_ID` int(2) DEFAULT NULL,
  `CONC_UNITE_ID` int(2) DEFAULT NULL,
  `QUANTITE_INIT` decimal(12,3) DEFAULT NULL,
  `QUANTITE` decimal(12,3) DEFAULT NULL,
  `QUANTITE_UNITE_ID` int(2) DEFAULT NULL,
  `PROD_QUALITE_ID` int(10) DEFAULT NULL,
  `TRANSFORMATION_ID` int(10) DEFAULT NULL,
  `DATE_TRANSFORMATION` datetime DEFAULT NULL,
  `ETAT_INCOMPLET` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  `MODE_PREPA_DERIVE_ID` int(3) DEFAULT NULL,
  `CONFORME_TRAITEMENT` tinyint(1) DEFAULT NULL,
  `CONFORME_CESSION` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`PROD_DERIVE_ID`),
  UNIQUE KEY `EMPLACEMENT_ID_UNIQUE` (`EMPLACEMENT_ID`),
  KEY `FK_PROD_DERIVE_BANQUE_ID` (`BANQUE_ID`),
  KEY `FK_PROD_DERIVE_QUANTITE_UNITE_ID` (`QUANTITE_UNITE_ID`),
  KEY `FK_PROD_DERIVE_CONC_UNITE_ID` (`CONC_UNITE_ID`),
  KEY `FK_PROD_DERIVE_PROD_TYPE_ID` (`PROD_TYPE_ID`),
  KEY `FK_PROD_DERIVE_OBJET_STATUT_ID` (`OBJET_STATUT_ID`),
  KEY `FK_PROD_DERIVE_PROD_QUALITE_ID` (`PROD_QUALITE_ID`),
  KEY `FK_PROD_DERIVE_COLLABORATEUR_ID` (`COLLABORATEUR_ID`),
  KEY `FK_PROD_DERIVE_EMPLACEMENT_ID` (`EMPLACEMENT_ID`),
  KEY `FK_PROD_DERIVE_VOLUME_UNITE_ID` (`VOLUME_UNITE_ID`),
  KEY `FK_PROD_DERIVE_TRANSFORMATION_ID` (`TRANSFORMATION_ID`),
  KEY `FK_PROD_DERIVE_MODE_PREPA_DERIVE_ID` (`MODE_PREPA_DERIVE_ID`),
  CONSTRAINT `FK_PROD_DERIVE_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `BANQUE` (`BANQUE_ID`),
  CONSTRAINT `FK_PROD_DERIVE_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `COLLABORATEUR` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_PROD_DERIVE_CONC_UNITE_ID` FOREIGN KEY (`CONC_UNITE_ID`) REFERENCES `UNITE` (`UNITE_ID`),
  CONSTRAINT `FK_PROD_DERIVE_EMPLACEMENT_ID` FOREIGN KEY (`EMPLACEMENT_ID`) REFERENCES `EMPLACEMENT` (`EMPLACEMENT_ID`),
  CONSTRAINT `FK_PROD_DERIVE_MODE_PREPA_DERIVE_ID` FOREIGN KEY (`MODE_PREPA_DERIVE_ID`) REFERENCES `MODE_PREPA_DERIVE` (`MODE_PREPA_DERIVE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_PROD_DERIVE_OBJET_STATUT_ID` FOREIGN KEY (`OBJET_STATUT_ID`) REFERENCES `OBJET_STATUT` (`OBJET_STATUT_ID`),
  CONSTRAINT `FK_PROD_DERIVE_PROD_QUALITE_ID` FOREIGN KEY (`PROD_QUALITE_ID`) REFERENCES `PROD_QUALITE` (`PROD_QUALITE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_PROD_DERIVE_PROD_TYPE_ID` FOREIGN KEY (`PROD_TYPE_ID`) REFERENCES `PROD_TYPE` (`PROD_TYPE_ID`),
  CONSTRAINT `FK_PROD_DERIVE_QUANTITE_UNITE_ID` FOREIGN KEY (`QUANTITE_UNITE_ID`) REFERENCES `UNITE` (`UNITE_ID`),
  CONSTRAINT `FK_PROD_DERIVE_TRANSFORMATION_ID` FOREIGN KEY (`TRANSFORMATION_ID`) REFERENCES `TRANSFORMATION` (`TRANSFORMATION_ID`),
  CONSTRAINT `FK_PROD_DERIVE_VOLUME_UNITE_ID` FOREIGN KEY (`VOLUME_UNITE_ID`) REFERENCES `UNITE` (`UNITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `CEDER_OBJET`;
CREATE TABLE `CEDER_OBJET` (
  `CESSION_ID` int(10) NOT NULL DEFAULT '0',
  `OBJET_ID` int(10) NOT NULL DEFAULT '0',
  `ENTITE_ID` int(10) NOT NULL DEFAULT '3',
  `QUANTITE` decimal(12,3) DEFAULT NULL,
  `QUANTITE_UNITE_ID` int(2) DEFAULT NULL,
  `STATUT` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CESSION_ID`,`OBJET_ID`,`ENTITE_ID`),
  KEY `FK_CEDER_OBJET_ENTITE_ID` (`ENTITE_ID`),
  KEY `FK_CEDER_OBJET_QUANTITE_UNITE_ID` (`QUANTITE_UNITE_ID`),
  CONSTRAINT `FK_CEDER_OBJET_CESSION_ID` FOREIGN KEY (`CESSION_ID`) REFERENCES `CESSION` (`CESSION_ID`),
  CONSTRAINT `FK_CEDER_OBJET_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `ENTITE` (`ENTITE_ID`),
  CONSTRAINT `FK_CEDER_OBJET_QUANTITE_UNITE_ID` FOREIGN KEY (`QUANTITE_UNITE_ID`) REFERENCES `UNITE` (`UNITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `CEDER_OBJET_PROD_DERIVE`;
CREATE TABLE `CEDER_OBJET_PROD_DERIVE` (
  `CESSION_ID` int(11) NOT NULL,
  `OBJET_ID` int(11) NOT NULL,
  `ENTITE_ID` int(11) NOT NULL,
  `PROD_DERIVE_ID` int(11) NOT NULL,
  KEY `CEDER_OBJET_PROD_DERIVE_CEDER_OBJET_FK` (`CESSION_ID`,`OBJET_ID`,`ENTITE_ID`),
  KEY `CEDER_OBJET_PROD_DERIVE_PROD_DERIVE_FK` (`PROD_DERIVE_ID`),
  CONSTRAINT `CEDER_OBJET_PROD_DERIVE_PROD_DERIVE_FK` FOREIGN KEY (`PROD_DERIVE_ID`) REFERENCES `PROD_DERIVE` (`PROD_DERIVE_ID`),
  CONSTRAINT `CEDER_OBJET_PROD_DERIVE_CEDER_OBJET_FK` FOREIGN KEY (`CESSION_ID`, `OBJET_ID`, `ENTITE_ID`) REFERENCES `CEDER_OBJET` (`CESSION_ID`, `OBJET_ID`, `ENTITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `ECHANTILLON_TYPE`;
CREATE TABLE `ECHANTILLON_TYPE` (
  `ECHANTILLON_TYPE_ID` int(2) NOT NULL,
  `TYPE` varchar(200) NOT NULL,
  `INCA_CAT` varchar(10) DEFAULT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`ECHANTILLON_TYPE_ID`),
  KEY `FK_ECHANTILLON_TYPE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_ECHANTILLON_TYPE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `ECHAN_QUALITE`;
CREATE TABLE `ECHAN_QUALITE` (
  `ECHAN_QUALITE_ID` int(3) NOT NULL DEFAULT '0',
  `ECHAN_QUALITE` varchar(200) NOT NULL,
  `PLATEFORME_ID` int(10) NOT NULL,
  PRIMARY KEY (`ECHAN_QUALITE_ID`),
  KEY `FK_ECHAN_QUALITE_PLATEFORME_ID` (`PLATEFORME_ID`),
  CONSTRAINT `FK_ECHAN_QUALITE_PLATEFORME_ID` FOREIGN KEY (`PLATEFORME_ID`) REFERENCES `PLATEFORME` (`PLATEFORME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS `ECHANTILLON`;
CREATE TABLE `ECHANTILLON` (
  `ECHANTILLON_ID` int(10) NOT NULL AUTO_INCREMENT,
  `BANQUE_ID` int(10) NOT NULL DEFAULT '0',
  `PRELEVEMENT_ID` int(10) DEFAULT '0',
  `COLLABORATEUR_ID` int(10) DEFAULT NULL,
  `CODE` varchar(50) NOT NULL DEFAULT '',
  `OBJET_STATUT_ID` int(2) DEFAULT NULL,
  `DATE_STOCK` datetime DEFAULT NULL,
  `EMPLACEMENT_ID` int(10) DEFAULT NULL,
  `ECHANTILLON_TYPE_ID` int(2) NOT NULL DEFAULT '0',
  `LATERALITE` char(1) DEFAULT NULL,
  `QUANTITE` decimal(12,3) DEFAULT NULL,
  `QUANTITE_INIT` decimal(12,3) DEFAULT NULL,
  `QUANTITE_UNITE_ID` int(2) DEFAULT NULL,
  `DELAI_CGL` decimal(9,2) DEFAULT NULL,
  `ECHAN_QUALITE_ID` int(3) DEFAULT NULL,
  `TUMORAL` tinyint(1) DEFAULT NULL,
  `MODE_PREPA_ID` int(3) DEFAULT NULL,
  `CR_ANAPATH_ID` int(10) DEFAULT NULL,
  `STERILE` tinyint(1) DEFAULT NULL,
  `CONFORME_TRAITEMENT` tinyint(1) DEFAULT NULL,
  `CONFORME_CESSION` tinyint(1) DEFAULT NULL,
  `ETAT_INCOMPLET` tinyint(1) DEFAULT '0',
  `ARCHIVE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ECHANTILLON_ID`),
  UNIQUE KEY `EMPLACEMENT_ID` (`EMPLACEMENT_ID`),
  UNIQUE KEY `CR_ANAPATH_ID` (`CR_ANAPATH_ID`),
  KEY `FK_ECHANTILLON_OBJET_STATUT_ID` (`OBJET_STATUT_ID`),
  KEY `FK_ECHANTILLON_BANQUE_ID` (`BANQUE_ID`),
  KEY `FK_ECHANTILLON_ECHAN_QUALITE_ID` (`ECHAN_QUALITE_ID`),
  KEY `FK_ECHANTILLON_MODE_PREPA_ID` (`MODE_PREPA_ID`),
  KEY `FK_ECHANTILLON_QUANTITE_UNITE_ID` (`QUANTITE_UNITE_ID`),
  KEY `FK_ECHANTILLON_COLLABORATEUR_ID` (`COLLABORATEUR_ID`),
  KEY `FK_ECHANTILLON_EMPLACEMENT_ID` (`EMPLACEMENT_ID`),
  KEY `FK_ECHANTILLON_ECHANTILLON_TYPE_ID` (`ECHANTILLON_TYPE_ID`),
  KEY `FK_ECHANTILLON_PRELEVEMENT_ID` (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_ECHANTILLON_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `BANQUE` (`BANQUE_ID`),
  CONSTRAINT `FK_ECHANTILLON_COLLABORATEUR_ID` FOREIGN KEY (`COLLABORATEUR_ID`) REFERENCES `COLLABORATEUR` (`COLLABORATEUR_ID`),
  CONSTRAINT `FK_ECHANTILLON_CR_ANAPATH_ID` FOREIGN KEY (`CR_ANAPATH_ID`) REFERENCES `FICHIER` (`FICHIER_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ECHANTILLON_ECHANTILLON_TYPE_ID` FOREIGN KEY (`ECHANTILLON_TYPE_ID`) REFERENCES `ECHANTILLON_TYPE` (`ECHANTILLON_TYPE_ID`),
  CONSTRAINT `FK_ECHANTILLON_ECHAN_QUALITE_ID` FOREIGN KEY (`ECHAN_QUALITE_ID`) REFERENCES `ECHAN_QUALITE` (`ECHAN_QUALITE_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ECHANTILLON_EMPLACEMENT_ID` FOREIGN KEY (`EMPLACEMENT_ID`) REFERENCES `EMPLACEMENT` (`EMPLACEMENT_ID`),
  CONSTRAINT `FK_ECHANTILLON_MODE_PREPA_ID` FOREIGN KEY (`MODE_PREPA_ID`) REFERENCES `MODE_PREPA` (`MODE_PREPA_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ECHANTILLON_OBJET_STATUT_ID` FOREIGN KEY (`OBJET_STATUT_ID`) REFERENCES `OBJET_STATUT` (`OBJET_STATUT_ID`),
  CONSTRAINT `FK_ECHANTILLON_PRELEVEMENT_ID` FOREIGN KEY (`PRELEVEMENT_ID`) REFERENCES `PRELEVEMENT` (`PRELEVEMENT_ID`),
  CONSTRAINT `FK_ECHANTILLON_QUANTITE_UNITE_ID` FOREIGN KEY (`QUANTITE_UNITE_ID`) REFERENCES `UNITE` (`UNITE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `TEMPLATE`;
CREATE TABLE `TEMPLATE` (
  `TEMPLATE_ID` int(10) NOT NULL,
  `TYPE` varchar(100) NOT NULL,
  `BANQUE_ID` int(10) NOT NULL,
  `NOM` varchar(50) NOT NULL,
  `ENTITE_ID` int(2) NOT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `EN_TETE` varchar(50) DEFAULT NULL,
  `PIED_PAGE` varchar(50) DEFAULT NULL,
  `FICHIER` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`TEMPLATE_ID`),
  KEY `FK_TEMPLATE_ENTITE_ID` (`ENTITE_ID`),
  KEY `FK_TEMPLATE_BANQUE_ID` (`BANQUE_ID`),
  CONSTRAINT `FK_TEMPLATE_BANQUE_ID` FOREIGN KEY (`BANQUE_ID`) REFERENCES `BANQUE` (`BANQUE_ID`),
  CONSTRAINT `FK_TEMPLATE_ENTITE_ID` FOREIGN KEY (`ENTITE_ID`) REFERENCES `ENTITE` (`ENTITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--DROP TABLE IF EXISTS CLE_IMPRESSION`;
CREATE TABLE `CLE_IMPRESSION` (
  `CLE_IMPRESSION_ID` int(11) NOT NULL,
  `NOM` varchar(100) NOT NULL,
  `CHAMP_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`CLE_IMPRESSION_ID`),
  KEY `FK_CHAMP_ID` (`CHAMP_ID`),
  CONSTRAINT `FK_CHAMP_ID` FOREIGN KEY (`CHAMP_ID`) REFERENCES `CHAMP` (`CHAMP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--DROP TABLE IF EXISTS `CLE_IMPRESSION_TEMPLATE`;
CREATE TABLE `CLE_IMPRESSION_TEMPLATE` (
  `CLE_IMPRESSION_ID` int(11) NOT NULL,
  `TEMPLATE_ID` int(11) NOT NULL,
  KEY `CLE_IMPRESSION_TEMPLATE_CLE_IMPRESSION_FK` (`CLE_IMPRESSION_ID`),
  KEY `CLE_IMPRESSION_TEMPLATE_TEMPLATE_FK` (`TEMPLATE_ID`),
  CONSTRAINT `CLE_IMPRESSION_TEMPLATE_CLE_IMPRESSION_FK` FOREIGN KEY (`CLE_IMPRESSION_ID`) REFERENCES `CLE_IMPRESSION` (`CLE_IMPRESSION_ID`),
  CONSTRAINT `CLE_IMPRESSION_TEMPLATE_TEMPLATE_FK` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `TEMPLATE` (`TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
