//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.10.23 at 04:30:23 PM CEST
//

package fr.aphp.tumorotek.interfacage.jaxb.inclusion;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for genderType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="genderType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="m"/>
 *     &lt;enumeration value="f"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "genderType")
@XmlEnum
public enum GenderType
{

   @XmlEnumValue("m") M("m"), @XmlEnumValue("f") F("f");
   private final String value;

   GenderType(final String v){
      value = v;
   }

   public String value(){
      return value;
   }

   public static GenderType fromValue(final String v){
      for(final GenderType c : GenderType.values()){
         if(c.value.equals(v)){
            return c;
         }
      }
      throw new IllegalArgumentException(v);
   }

}
