//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.10.23 at 04:30:23 PM CEST
//

package fr.aphp.tumorotek.interfacage.jaxb.inclusion;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the fr.aphp.tumorotek.interfacage.jaxb.inclusion package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{

   /**
    * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.aphp.tumorotek.interfacage.jaxb.inclusion
    *
    */
   public ObjectFactory(){}

   /**
    * Create an instance of {@link CreateResponse }
    *
    */
   public CreateResponse createCreateResponse(){
      return new CreateResponse();
   }

   /**
    * Create an instance of {@link CreateRequest }
    *
    */
   public CreateRequest createCreateRequest(){
      return new CreateRequest();
   }

   /**
    * Create an instance of {@link StudySubjectType }
    *
    */
   public StudySubjectType createStudySubjectType(){
      return new StudySubjectType();
   }

   /**
    * Create an instance of {@link SiteRefType }
    *
    */
   public SiteRefType createSiteRefType(){
      return new SiteRefType();
   }

   /**
    * Create an instance of {@link StudySubjectRefType }
    *
    */
   public StudySubjectRefType createStudySubjectRefType(){
      return new StudySubjectRefType();
   }

   /**
    * Create an instance of {@link SubjectType }
    *
    */
   public SubjectType createSubjectType(){
      return new SubjectType();
   }

   /**
    * Create an instance of {@link EventType }
    *
    */
   public EventType createEventType(){
      return new EventType();
   }

   /**
    * Create an instance of {@link StudyRefType }
    *
    */
   public StudyRefType createStudyRefType(){
      return new StudyRefType();
   }

}
