alter table PROD_DERIVE modify CODE_LABO varchar2(50);
alter table CONTENEUR modify PIECE varchar2(20);

-- ZPL
alter table IMPRIMANTE add ADRESSEIP varchar2(20);
alter table IMPRIMANTE add RESOLUTION NUMBER(5);
alter table IMPRIMANTE add PORT NUMBER(5);

-- import dérivés dérivés
alter table IMPORT_TEMPLATE add DERIVE_PARENT_ENTITE_ID NUMBER(22);

-- FICHIER
alter table ECHANTILLON modify CR_ANAPATH_ID NUMBER(22) unique;
alter table ANNOTATION_VALEUR modify FICHIER_ID NUMBER(22) unique;

alter table ANNOTATION_VALEUR drop constraint FK_ANNO_VALEUR_FICHIER_ID;

ALTER TABLE ANNOTATION_VALEUR
  ADD CONSTRAINT FK_ANNO_VALEUR_FICHIER_ID
      FOREIGN KEY (FICHIER_ID)
      REFERENCES FICHIER (FICHIER_ID)
      ON DELETE SET NULL;
      
alter table ECHANTILLON drop constraint FK_ECHANTILLON_CR_ANAPATH_ID;
      
ALTER TABLE ECHANTILLON
  ADD CONSTRAINT FK_ECHANTILLON_CR_ANAPATH_ID
      FOREIGN KEY (CR_ANAPATH_ID)
      REFERENCES FICHIER (FICHIER_ID)
      ON DELETE SET NULL;
      