CREATE PROCEDURE create_tmp_prelevement_sero_table()
  BEGIN
    DROP TEMPORARY TABLE IF EXISTS TMP_PRELEVEMENT_EXPORT;
    CREATE TEMPORARY TABLE TMP_PRELEVEMENT_EXPORT (
      PRELEVEMENT_ID       int(10),
      BANQUE               varchar(300),
      CODE                 varchar(50),
      NUMERO_LABO          varchar(50),
      NATURE               varchar(200),
      PROTOCOLES           varchar(1000),
      DATE_PRELEVEMENT     datetime,
      PRELEVEMENT_TYPE     varchar(200),
      STERILE              boolean,
      RISQUE               varchar(200),
      CONFORME_ARRIVEE     boolean,
      RAISON_NC_TRAITEMENT varchar(1000),
      ETABLISSEMENT        varchar(100),
      SERVICE_PRELEVEUR    varchar(100),
      PRELEVEUR            varchar(100),
      CONDIT_TYPE          varchar(200),
      CONDIT_NBR           int(11),
      CONDIT_MILIEU        varchar(200),
      CONSENT_TYPE         varchar(200),
      CONSENT_DATE         date,
      COMPLEMENT_DIAG      varchar(300),
      DATE_DEPART          datetime,
      TRANSPORTEUR         varchar(50),
      TRANSPORT_TEMP       DECIMAL(12, 3),
      DATE_ARRIVEE         datetime,
      OPERATEUR            varchar(50),
      CONG_DEPART          boolean,
      CONG_ARRIVEE         boolean,
      LABO_INTER           varchar(3),
      QUANTITE             DECIMAL(12, 3),
      PATIENT_NDA          varchar(20),
      DIAGNOSTIC           varchar(500),
      ECHAN_TOTAL          int(4),
      ECHAN_RESTANT        int(4),
      ECHAN_STOCKE         int(4),
      AGE_PREL             int(4),
      NOMBRE_DERIVES       int(4),
      DATE_HEURE_SAISIE    datetime,
      UTILISATEUR_SAISIE   varchar(100),
      MALADIE_ID           int(10),
      LIBELLE              varchar(300),
      CODE_MALADIE         varchar(50),
      DATE_DIAGNOSTIC      date,
      DATE_DEBUT           date,
      MEDECIN_MALADIE      varchar(300),
      PATIENT_ID           int(10),
      PRIMARY KEY (PRELEVEMENT_ID),
      INDEX (PATIENT_ID),
      INDEX (MALADIE_ID)
    )
      ENGINE = MYISAM, default character SET = utf8;

  END;