ALTER TABLE tumorotek_interfacages.SCAN_TUBE CHANGE `ROW` LIGNE VARCHAR(10);
ALTER TABLE tumorotek_interfacages.SCAN_TUBE CHANGE CELL CELLULE VARCHAR(10);
ALTER TABLE tumorotek_interfacages.SCAN_TUBE CHANGE COL COLONNE VARCHAR(10);
