-- suite au probleme de performances observé par Fabien HCLs 
-- lors récupération > 700 000 fichiers 
create index sipNipIdx on tumo2interfacages.PATIENT_SIP(NIP);

-- indexes must exists
ALTER TABLE ANNOTATION_VALEUR ADD INDEX objIdx (OBJET_ID, CHAMP_ANNOTATION_ID);
alter table OPERATION add index OBJ_ID_IDX_OPERATION (OBJET_ID);

-- 2.0.13.1
CREATE TABLE CONSULTATION_INTF (
  	CONSULTATION_INTF_ID INT(10) NOT NULL,
  	IDENTIFICATION VARCHAR(100) NOT NULL,
	DATE_ DATETIME NOT NULL,
 	UTILISATEUR_ID INT(10) NOT NULL,
 	EMETTEUR_IDENT VARCHAR(100) NOT NULL,
  	PRIMARY KEY (CONSULTATION_INTF_ID)
) ENGINE=InnoDB;

ALTER TABLE CONSULTATION_INTF 
	ADD CONSTRAINT FK_CONSULT_INTF_UTIL_ID 
	FOREIGN KEY (UTILISATEUR_ID) 
	REFERENCES UTILISATEUR (UTILISATEUR_ID);
