# Imports
importTemplate.liste.title=List of templates used
importTemplate.filtre.nonUtilises=Shared templates not used
importTemplate.fiche.title=Template of a data import
importTemplate.nom=Name
importTemplate.type=Type
# s'appuie sur le code du type défini dans EimportTemplate.java
importTemplate.type.NEW_MULTI=Creation
importTemplate.type.NEW_DERIVE=Creation of a byproduct with parent
importTemplate.type.MODIF_ANNO=Modification of annotations
importTemplate.banque=Original collection
importTemplate.description=Description
importTemplate.entites=Entities to import
importTemplate.entite.Maladie=Disease (makes the like between the sampling and the patient)
importTemplate.colonnes.title=Columns present in the file
importColonne.nom=Column name
importColonne.copy=Copy Fields
importColonne.champ=Associated field
importColonne.format=Format required
importColonne.entite=Entity
importColonne.obligatoire=Mandatory
importColonne.Type.Emplacement=Storage address
importTemplate.new.entite=Assign a new entity to the import
importTemplate.entite.remove.warning=Do you really want to delete the reference to this entity?
importTemplate.maladie.remove.warning=The deletion of the reference to the entity disease will result in the import of the samplings uncoupled to the patient! 
importTemplate.add.column.help=Add a new column by choosing the field to import depending on its entity :
importTemplate.entite=Entity :
importTemplate.champ=Field to import :
importTemplate.import.champ=Import the field
importTemplate.creation.encours=Saving the import template in progress...
importHistorique.title=Import history
importHistorique.date=Date
importHistorique.utilisateur=User
importHistorique.nb.patients=Number of patients
importHistorique.nb.prelevements=Number of samplings
importHistorique.nb.echantillons=Number of samples
importHistorique.nb.prodDerives=Number of by-products
importHistorique.affichage.patients=Preparing the display of the imported patients...
importHistorique.affichage.prelevements=Preparing the display of the imported samplings...
importHistorique.affichage.echantillons=Preparing the display of the imported samples...
importHistorique.affichage.prodDerives=Preparing the display of the imported by-products...
importTemplate.execute.import=Make an import
importTemplate.export.header=Export the header
importTemplate.new.from=New from this template
importTemplate.partager.template=Share
importTemplate.supprimer.partage=Delete share
importTemplate.partage.modale.title=Template sharing
importTemplate.partage.modale.succes=Model {1} is now shared
importTemplate.partage.modale.echec=Sharing template {1} failed
importTemplate.suppressionPartage.modale.title=Deleting sharing
importTemplate.suppressionPartage.modale.succes=Template {1} is no longer shared
importTemplate.suppressionPartage.modale.echec=Removing share from template {1} failed. It is therefore always shared
importTemplate.archivage.modale.title=Template Archiving
importTemplate.archivage.modale.succes=Template {1} is archived
importTemplate.alerte.modeleArchive=Please note, this template is archived
importTemplate.alerte.modeleModifie=Please note, this template has been modified since your last run
importTemplate.tooltip.partageParBanqueCourante=Shared with other collections
importTemplate.tooltip.partageParAutreBanque=Shared by another collection
importTemplate.tooltip.modificationAnnotation=Template of type "Modification of annotation"
importTemplate.file.upload.title=Load the file hosting the date to import
importTemplate.wait.import=Import in progress...
importTemplate.resultats.ok.title=The import was successful. All the data of datasheet <span class="formBlueLabel">{1}</span> are saved.
importTemplate.resultats.warn.title=Errors were detected in the datasheet <span class="formBlueLabel">{1}</span>. You must correct them for the import to be successful.
importTemplate.resultats.warn.title.warning.ecrasement=A risk of overwriting existing values was detected while processing the <span class="formBlueLabel">{1}</span> sheet. Please see the details to confirm or reject updates.
importTemplate.resultats.warn.title.warning.ecrasement.importPartiel=The first {1} lines of sheet <span class="formBlueLabel">{2}</span> could be imported, but A risk of overwriting existing values was detected in the following lines. Please see the details to confirm or reject updates.
importTemplate.resultats.warn.title.transactionKO=A technical error occurred while processing the datasheet <span class="formBlueLabel">{1}</span>. No data was saved. Please try again.
importTemplate.resultats.warn.title.transactionKO.importPartiel=The first {1} lines of sheet <span class="formBlueLabel">{2}</span> could be imported, but a technical error occurred while processing the following lines. More details below.
importTemplate.resultats.warn.detail.transactionKO.importPartiel=Technical detail : {1}
importTemplate.resultats.empty.title=All the objects defined by the data of the datasheet <span class="formBlueLabel">{1}</span> already exist. None of the data was saved.
importTemplate.statistiques=Data available on this import :
importTemplate.statistiques.errors.infos=Details
importTemplate.statistiques.ok=Import of datasheet <span class="formBlueLabel">{1}</span>, completed on the {2}, included :
importTemplate.statistiques.errors=The import tool detected {1} line(s) in error in the provided datasheet. You must correct these errors for the import to be successful.
importTemplate.statistiques.errors.doublon=The import process detected {1} duplicate entries in the provided datasheet. You must correct these errors before the import can be successful.
importTemplate.statistiques.errors.lot=The first {1} lines could be imported, but {2} of the following lines are in error. You must correct these errors, then delete the {1} lines that were processed, and import this new file.
importTemplate.statistiques.errors.colonnes=Some columns defined in the import template were not found in the datasheet provided. Here is the list of the columns to add for the import to be sucessfull : {1}.
importTemplate.statistiques.errors.colonnes.doublon=Columns are present multiple times in the file. These are: {1}.
importTemplate.statistiques.errors.file=The file provided for the import was unreadable. You must verify that it was not corrupted and that it is an xls or xlsx format.
importTemplate.statistiques.errors.warning.ecrasement=For {1} rows, at least one existing data item will be modified: you can download a file below showing the existing values. Then you can click Continue to make the updates or Exit to modify the import file.
importTemplate.statistiques.errors.warning.ecrasement.importPartiel=For {1} rows, at least one existing data item will be modified: you can download a file below showing the existing values. Then you can click Continue to make the updates or Exit to modify the import file (and delete the {2} processed lines).
importTemplate.dl.correctif=You can download a corrections file. It is the same as the file provided for the import, with an added column about the reason of a line rejection.
importTemplate.dl.correctif.codesInexistants=You can download a correction file containing all the codes that do not exist in the database.
importTemplate.dl.correctif.button=Download the corrections file
importTemplate.dl.warning.ecrasement=You can download the existing values of the data that will be changed.
importTemplate.dl.warning.ecrasement.button=Download the details of the before/after data
importTemplate.dl.importPatiel=You can download the details of the imported lines. This file corresponds to the sheet provided during the import, with an additional column filled in if the line has been processed.
importTemplate.dl.importPatiel.button=Download the import details
importTemplate.header.colonne.erreurs=Errors
importTemplate.header.colonne.avertissements=Warnings
importTemplate.header.colonne.detailTraitement=Processing detail
importTemplate.header.illegal=The header of the column {1} of the import datasheet is inoperable.
importTemplate.correctif.error.doublon=Duplicate : {1} '{2}' is present on rows : {3}
importTemplate.correctif.error.codeInexistant=List of '{1}' not present in database for the current bank.
importTemplate.correctif.error.codeInexistant.patient=List of '{1}' not present in the database or associated with patients who does not have a sample in the current collection
importTemplate.correctif.error.codeInexploitable=The code in column {1} is unusable. The expected format is alphanumeric.
importTemplate.correctif.error.dataControleInexploitable=The value in column '{1}' is unusable. The expected format is alphanumeric.
importTemplate.correctif.error.codeIncorrect=In the database, the field '{1}' with the value of {2} is associated with the value of {3} and not {4}, for the field '{5}'.
importTemplate.correctif.warning.ecrasement={1} : existing value '{2}' to be replaced with '{3}'
importTemplate.correctif.warning.ecrasement.continuer.button=Continue
importTemplate.correctif.warning.ecrasement.fermer.button=Exit
importTemplate.correctif.info.importFait=Import done
#Normalement le message suivant n'est jamais affiché car le bouton "Modifier" est bloqué dans ce cas. Géré par sécurité
importTemplate.modale.edit.templateUsed.titre=Editing a shared template
importTemplate.modale.edit.collectionIncorrecte=This template belongs to the {1} collection. Please switch to this collection to edit it.
importTemplate.modale.edit.templateUsed=The template is used by the following collections {1}. 
importTemplate.modale.edit.templateUsed.plusDeDix=The template is used by {1} collections including {2}.
importTemplate.modale.edit.continuer=Do you want to continue?
importTemplate.modale.action.impossible=This action is therefore impossible.
importTemplate.modale.delete.impossible=It is therefore impossible to delete it.
importTemplate.modale.delete.templateUsed.titre=Deleting a used shared template

import.choose.sheet.title=Choice of the datasheet to import.
import.choose.sheet.title.embed=Import another datasheet :
import.choose.sheet=The file in table form has more than one datasheet. Select the one to be imported:
import.choose.sheet.display={1} ({2} lines)

profil.import.restriction.rules=The date import functionality is accessible to the profile with admin rights and with the rights of annotations creation and modification for the tab Patient, Sampling, Sample and By-Product. 

importTemplate.subderive.fiche.title=Import template specific to by-products
importTemplate.modification.annotation.fiche.title=Import template for updating annotations
importTemplate.subderive.entite.parent=Related entity
importTemplate.new.subderive=New template for by-product
importTemplate.new.modification.annotation=New for modify annotations
import.colonne.subderive.header=<i>By-product header</i>
import.colonne.subderive.parent=Related code
import.colonne.subderive.qte.transf=Transformed quantity
import.colonne.subderive.evt.date=Storage event date
